<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Curl.Cryptography.UnitLibrary\Curl.Cryptography.UnitLibrary.csproj" />
    <ProjectReference Include="..\Curl.Protocol.Abstractions.UnitLibrary\Curl.Protocol.Abstractions.UnitLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Curl.Protocol.Ssh.UnitTests" />
  </ItemGroup>

</Project>
