using System.Globalization;
using System.Text;

namespace Curl.Cookies;

/// <summary>
/// Reads and writes the Netscape cookie file format the way libcurl 8.21.0 does: the file <c>-b</c>
/// loads and the jar <c>-c</c> writes. Every rule here was measured on curl 8.21.0 on 2026-09-26 by
/// loading a file with <c>-b</c> and reading curl's <c>-c</c> jar back, as
/// <c>NetscapeCookieFileTests</c> records.
/// </summary>
/// <remarks>
/// A line is seven fields separated by tabs: domain, includes-subdomains, path, secure, expiry, name and
/// value. The text is handled one character per byte, so a caller reads and writes the file as Latin-1
/// to keep its bytes as they are. A line starting <c>Set-Cookie:</c> is instead read as a header, by
/// <see cref="SetCookieParser.ParseFromCookieFile"/>.
/// </remarks>
public static class NetscapeCookieFile
{
    /// <summary>
    /// The longest line curl reads, in characters, counting a carriage return but not the line feed.
    /// A longer line ends the reading: it and every line after it are ignored.
    /// </summary>
    public const int LongestLine = 4998;

    private const string HttpOnlyPrefix = "#HttpOnly_";

    private const string SetCookiePrefix = "Set-Cookie:";

    private const int FieldsWithValue = 7;

    /// <summary>The lines curl writes at the top of every jar, the last one empty, even when it holds no cookie.</summary>
    public static IReadOnlyList<string> HeaderLines { get; } =
    [
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# This file was generated by libcurl! Edit at your own risk.",
        string.Empty,
    ];

    /// <summary>Reads every cookie in <paramref name="reader"/>, in the order written, skipping each line curl refuses.</summary>
    /// <remarks>
    /// Lines end at a line feed. A line longer than <see cref="LongestLine"/> ends the reading; each
    /// shorter one is read by <see cref="ParseLine"/>.
    /// </remarks>
    /// <param name="reader">The file's text, one character per byte.</param>
    /// <param name="now">The time the file is read, which a <c>Set-Cookie:</c> line's <c>Max-Age</c> counts from.</param>
    /// <returns>The cookies read, oldest (first in the file) first. Expired cookies are included.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="reader"/> is <see langword="null"/>.</exception>
    public static IReadOnlyList<Cookie> Read(TextReader reader, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(reader);

        List<Cookie> cookies = [];
        StringBuilder line = new();
        while (TryReadLine(reader, line))
        {
            Cookie? cookie = ParseLine(line.ToString(), now);
            if (cookie is not null)
            {
                cookies.Add(cookie);
            }
        }

        return cookies;
    }

    /// <summary>Reads the next line, without its line feed; <see langword="false"/> at the end of the text or at a line that is too long.</summary>
    private static bool TryReadLine(TextReader reader, StringBuilder line)
    {
        line.Clear();
        int character = reader.Read();
        if (character < 0)
        {
            return false;
        }

        while (character >= 0 && character != '\n')
        {
            line.Append((char)character);
            character = reader.Read();
        }

        return line.Length <= LongestLine;
    }

    /// <summary>Reads one line of a cookie file as curl does, or refuses it.</summary>
    /// <remarks>
    /// <para>
    /// The line ends at its first carriage return. A line starting <c>Set-Cookie:</c>, in any case, is a
    /// header: the blanks after the colon are skipped and the rest is read by
    /// <see cref="SetCookieParser.ParseFromCookieFile"/>. A line starting <c>#HttpOnly_</c> (that case only) is
    /// an <c>HttpOnly</c> cookie with the prefix removed; any other line starting <c>#</c> is a comment.
    /// The rest is split at every tab, empty fields included:
    /// </para>
    /// <list type="bullet">
    /// <item>The domain loses one leading dot.</item>
    /// <item>Includes-subdomains and secure are <see langword="true"/> when the field starts
    /// <c>TRUE</c>, in any case, and is no longer: <c>T</c>, <c>tru</c> and an empty field all count.</item>
    /// <item>A path field that starts <c>TRUE</c> or <c>FALSE</c>, in that case, and is no longer
    /// (an empty one included) is taken to be a missing path: the path is <c>/</c> and that field is the
    /// secure field. Any other path is sanitized as a <c>Path</c> attribute is: one pair of quotes
    /// removed, <c>/</c> when it does not start with <c>/</c>, and one trailing <c>/</c> removed.</item>
    /// <item>The expiry is the field's leading digits, which must be at least one and fit a
    /// <see cref="long"/>; <c>0</c> is a session cookie.</item>
    /// <item>A line of six fields has an empty value; any count but six or seven is refused.</item>
    /// </list>
    /// <para>
    /// A control character other than tab, or DEL, in the name or the value refuses the line, and so does
    /// a name starting <c>__Secure-</c> that is not secure, or <c>__Host-</c> that is not secure, host-only
    /// and on the path <c>/</c>. The expiry is not capped, and the domain and path may hold anything else.
    /// </para>
    /// </remarks>
    /// <param name="line">One line of the file, without its line feed.</param>
    /// <param name="now">The time the file is read, which a <c>Set-Cookie:</c> line's <c>Max-Age</c> counts from.</param>
    /// <returns>The cookie, or <see langword="null"/> when curl would skip the line.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="line"/> is <see langword="null"/>.</exception>
    public static Cookie? ParseLine(string line, DateTimeOffset now)
    {
        ArgumentNullException.ThrowIfNull(line);

        int carriageReturn = line.IndexOf('\r');
        string text = carriageReturn < 0 ? line : line[..carriageReturn];
        if (text.StartsWith(SetCookiePrefix, StringComparison.OrdinalIgnoreCase))
        {
            return SetCookieParser.ParseFromCookieFile(text[SetCookiePrefix.Length..].TrimStart(' ', '\t'), now);
        }

        bool isHttpOnly = text.StartsWith(HttpOnlyPrefix, StringComparison.Ordinal);
        if (isHttpOnly)
        {
            return ParseFields(text[HttpOnlyPrefix.Length..], isHttpOnly: true);
        }

        return text.StartsWith('#') ? null : ParseFields(text, isHttpOnly: false);
    }

    private static Cookie? ParseFields(string text, bool isHttpOnly)
    {
        List<string> fields = [.. text.Split('\t')];
        if (fields.Count > 2 && IsBooleanWord(fields[2]))
        {
            fields.Insert(2, "/");
        }

        if (fields.Count == FieldsWithValue - 1)
        {
            fields.Add(string.Empty);
        }

        if (fields.Count != FieldsWithValue || !TryParseExpiry(fields[4], out long expiresUnixSeconds))
        {
            return null;
        }

        return BuildCookie(fields, isHttpOnly, expiresUnixSeconds);
    }

    private static Cookie? BuildCookie(List<string> fields, bool isHttpOnly, long expiresUnixSeconds)
    {
        string name = fields[5];
        string value = fields[6];
        bool includesSubdomains = StartsTrue(fields[1]);
        string path = CookieFieldRules.SanitizePath(fields[2]);
        bool isSecure = StartsTrue(fields[3]);
        if (CookieFieldRules.ContainsRefusedControlCharacter(name)
            || CookieFieldRules.ContainsRefusedControlCharacter(value)
            || !CookieFieldRules.SatisfiesNamePrefix(name, isSecure, path, includesSubdomains))
        {
            return null;
        }

        string domain = fields[0].StartsWith('.') ? fields[0][1..] : fields[0];
        return new Cookie(name, value, domain, includesSubdomains, path, isSecure, isHttpOnly, expiresUnixSeconds);
    }

    /// <summary>curl's test for a path field that is really the secure field: the start of <c>TRUE</c> or <c>FALSE</c>, case-sensitively.</summary>
    private static bool IsBooleanWord(string field) =>
        "TRUE".StartsWith(field, StringComparison.Ordinal) || "FALSE".StartsWith(field, StringComparison.Ordinal);

    /// <summary>curl's <c>strncasecompare(field, "TRUE", len)</c>: the start of <c>TRUE</c>, in any case.</summary>
    private static bool StartsTrue(string field) => "TRUE".StartsWith(field, StringComparison.OrdinalIgnoreCase);

    private static bool TryParseExpiry(string field, out long expiresUnixSeconds)
    {
        string digits = new([.. field.TakeWhile(char.IsAsciiDigit)]);
        expiresUnixSeconds = 0;
        return digits.Length > 0 && long.TryParse(digits, NumberStyles.None, CultureInfo.InvariantCulture, out expiresUnixSeconds);
    }

    /// <summary>
    /// Writes a jar as curl does: <see cref="HeaderLines"/>, then one line per cookie, in the order given,
    /// leaving out each cookie without a domain (one read from a <c>Set-Cookie:</c> line without a <c>Domain</c>).
    /// </summary>
    /// <remarks>
    /// Every line, the empty one included, ends with <paramref name="writer"/>'s
    /// <see cref="TextWriter.NewLine"/>: curl writes the jar in text mode, which ends lines with CR LF on
    /// Windows and LF elsewhere.
    /// </remarks>
    /// <param name="writer">Where the jar is written, one character per byte.</param>
    /// <param name="cookies">The cookies, in the order curl writes them: newest first.</param>
    /// <exception cref="ArgumentNullException"><paramref name="writer"/> or <paramref name="cookies"/> is <see langword="null"/>.</exception>
    public static void Write(TextWriter writer, IEnumerable<Cookie> cookies)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(cookies);

        foreach (string headerLine in HeaderLines)
        {
            writer.WriteLine(headerLine);
        }

        foreach (Cookie cookie in cookies.Where(cookie => cookie.Domain is not null))
        {
            writer.WriteLine(FormatLine(cookie));
        }
    }

    /// <summary>One jar line for <paramref name="cookie"/>, without a line ending, as curl writes it.</summary>
    /// <remarks>
    /// <c>#HttpOnly_</c> first for an <c>HttpOnly</c> cookie; the domain, with a leading dot when it
    /// includes subdomains and does not already start with one; then <c>TRUE</c> or <c>FALSE</c>, the
    /// path (<c>/</c> for an empty one), <c>TRUE</c> or <c>FALSE</c> for secure, the expiry, the name and the value, separated by tabs.
    /// </remarks>
    /// <exception cref="ArgumentNullException"><paramref name="cookie"/> is <see langword="null"/>.</exception>
    public static string FormatLine(Cookie cookie)
    {
        ArgumentNullException.ThrowIfNull(cookie);

        string httpOnly = cookie.IsHttpOnly ? HttpOnlyPrefix : string.Empty;
        string dot = cookie.IncludesSubdomains && !cookie.Domain!.StartsWith('.') ? "." : string.Empty;
        return string.Create(
            CultureInfo.InvariantCulture,
            $"{httpOnly}{dot}{cookie.Domain}\t{Flag(cookie.IncludesSubdomains)}\t{(cookie.Path.Length == 0 ? "/" : cookie.Path)}\t{Flag(cookie.IsSecure)}\t{cookie.ExpiresUnixSeconds}\t{cookie.Name}\t{cookie.Value}");
    }

    private static string Flag(bool value) => value ? "TRUE" : "FALSE";
}
