using Curl.Testing;

namespace Curl.Cli;

/// <summary>
/// Pins <see cref="LibcurlSourceCode" /> and the <c>--libcurl</c> option against curl 8.21.0 (mingw,
/// Schannel) measured on 2026-10-01 with <c>Record-CurlExchange.ps1</c> (BL-652 Notes): the skeleton for
/// one URL and for two URLs under <c>-s</c> byte for byte, the scheme's own lines, and how strings are quoted.
/// </summary>
[TestClass]
public sealed class LibcurlSourceCodeTests
{
    private const string Header =
        "/********* Sample code generated by the curl command line tool **********\n"
        + " * All curl_easy_setopt() options are documented at:\n"
        + " * https://curl.se/libcurl/c/curl_easy_setopt.html\n"
        + " ************************************************************************/\n"
        + "#include <curl/curl.h>\n"
        + "\n"
        + "int main(int argc, char *argv[])\n"
        + "{\n"
        + "  CURLcode result;\n"
        + "  CURL *curl;\n"
        + "\n"
        + "  curl = curl_easy_init();\n";

    private const string Perform =
        "\n"
        + "  /* Here is a list of options the curl code used that cannot get generated\n"
        + "     as source easily. You may choose to either not use them or implement\n"
        + "     them yourself.\n"
        + "\n"
        + "  CURLOPT_WRITEDATA was set to an object pointer\n"
        + "  CURLOPT_INTERLEAVEDATA was set to an object pointer\n"
        + "  CURLOPT_WRITEFUNCTION was set to a function pointer\n"
        + "  CURLOPT_READDATA was set to an object pointer\n"
        + "  CURLOPT_READFUNCTION was set to a function pointer\n"
        + "  CURLOPT_SEEKDATA was set to an object pointer\n"
        + "  CURLOPT_SEEKFUNCTION was set to a function pointer\n"
        + "  CURLOPT_HEADERFUNCTION was set to a function pointer\n"
        + "  CURLOPT_HEADERDATA was set to an object pointer\n"
        + "  CURLOPT_ERRORBUFFER was set to an object pointer\n"
        + "  CURLOPT_STDERR was set to an object pointer\n"
        + "\n"
        + "  */\n"
        + "\n"
        + "  result = curl_easy_perform(curl);\n"
        + "\n";

    private const string Footer =
        "  curl_easy_cleanup(curl);\n"
        + "  curl = NULL;\n"
        + "\n"
        + "  return (int)result;\n"
        + "}\n"
        + "/**** End of sample code ****/\n";

    private const string TlsAndKeepAlive =
        "  curl_easy_setopt(curl, CURLOPT_SSLVERSION, (long)CURL_SSLVERSION_TLSv1_2);\n"
        + "  curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);\n";

    public TestContext TestContext { get; set; } = null!;

    private TestDiagnostics Diagnostics => TestDiagnostics.For(TestContext);

    [TestMethod]
    public void Generate_OneHttpUrl_IsCurlsSkeletonByteForByte()
    {
        CommandLineOptions options = Parse("--libcurl", "-", "http://127.0.0.1:47652/");

        string source = GenerateSource([(options, "http://127.0.0.1:47652/")]);

        string expected =
            Header
            + "  curl_easy_setopt(curl, CURLOPT_BUFFERSIZE, 102400L);\n"
            + "  curl_easy_setopt(curl, CURLOPT_URL, \"http://127.0.0.1:47652/\");\n"
            + "  curl_easy_setopt(curl, CURLOPT_USERAGENT, \"curl/8.21.0\");\n"
            + "  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);\n"
            + TlsAndKeepAlive
            + Perform
            + Footer;
        Diagnostics.Diff("source", expected, source);
        Assert.AreEqual(expected, source);
    }

    [TestMethod]
    public void Generate_TwoUrlsUnderSilent_RepeatsTheSetoptsAndPerformForEach()
    {
        CommandLineOptions options = Parse("-s", "--libcurl", "-", "http://127.0.0.1:47652/a", "http://127.0.0.1:47652/b");

        string source = GenerateSource([(options, "http://127.0.0.1:47652/a"), (options, "http://127.0.0.1:47652/b")]);

        string expected = Header + SilentHttpTransfer("a") + SilentHttpTransfer("b") + Footer;
        Diagnostics.Diff("source", expected, source);
        Assert.AreEqual(expected, source);
    }

    [TestMethod]
    public void Generate_NoProgressMeter_SetsNoProgressAsSilentDoes()
    {
        CommandLineOptions options = Parse("--no-progress-meter", "http://x/");

        string source = GenerateSource([(options, "http://x/")]);

        const string Expected = "  curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L);\n";
        Diagnostics.Assert("contains NOPROGRESS line", true, source.Contains(Expected, StringComparison.Ordinal));
        Assert.Contains(Expected, source);
    }

    [TestMethod]
    public void Generate_NoTransfers_IsTheHeaderAndFooterAlone()
    {
        Diagnostics.Arrange("transfers", "[]");

        string source = LibcurlSourceCode.Generate(Array.Empty<LibcurlTransfer>());
        Diagnostics.Act("source", source);

        Diagnostics.Diff("source", Header + Footer, source);
        Assert.AreEqual(Header + Footer, source);
    }

    [TestMethod]
    public void Generate_Null_Throws()
    {
        Diagnostics.Arrange("transfers", "null");

        ArgumentNullException exception = Assert.ThrowsExactly<ArgumentNullException>(() => LibcurlSourceCode.Generate((IReadOnlyList<(CommandLineOptions, string)>)null!));

        Diagnostics.Act("exception", exception.GetType().Name);
        Diagnostics.Assert("exception", nameof(ArgumentNullException), exception.GetType().Name);
    }

    [TestMethod]
    [DataRow("ftp://127.0.0.1:1/", "  curl_easy_setopt(curl, CURLOPT_FTP_SKIP_PASV_IP, 1L);\n")]
    [DataRow("ftps://127.0.0.1:1/", "  curl_easy_setopt(curl, CURLOPT_FTP_SKIP_PASV_IP, 1L);\n")]
    [DataRow("ftp.example.invalid/x", "  curl_easy_setopt(curl, CURLOPT_FTP_SKIP_PASV_IP, 1L);\n")]
    [DataRow("https://127.0.0.1:1/", "  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);\n")]
    [DataRow("HTTP://127.0.0.1:1/", "  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);\n")]
    [DataRow("127.0.0.1:1/", "  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);\n")]
    [DataRow("dict://127.0.0.1:1/", "")]
    [DataRow("file:///nonexist/x", "")]
    [DataRow("wss://127.0.0.1:1/", "")]
    [DataRow("http://a b/", "")]
    [DataRow("http://a\u007Fb/", "")]
    public void Generate_Scheme_AddsItsOwnLinesBetweenUserAgentAndTls(string url, string schemeLines)
    {
        Diagnostics.Arrange("url", url);
        Diagnostics.Arrange("scheme lines", schemeLines);

        string source = GenerateSource([(Parse(url), url)]);

        string expected = "  curl_easy_setopt(curl, CURLOPT_USERAGENT, \"curl/8.21.0\");\n" + schemeLines + TlsAndKeepAlive;
        Diagnostics.Assert("contains user agent, scheme lines and TLS lines", true, source.Contains(expected, StringComparison.Ordinal));
        StringAssert.Contains(source, expected);
    }

    [TestMethod]
    public void Generate_ProtoDefault_DecidesTheSchemeOfAUrlWithoutOne()
    {
        CommandLineOptions options = Parse("--proto-default", "ftp", "127.0.0.1:1/");

        string source = GenerateSource([(options, "127.0.0.1:1/")]);

        Diagnostics.Assert("contains CURLOPT_FTP_SKIP_PASV_IP", true, source.Contains("CURLOPT_FTP_SKIP_PASV_IP", StringComparison.Ordinal));
        Diagnostics.Assert("contains CURLOPT_MAXREDIRS", false, source.Contains("CURLOPT_MAXREDIRS", StringComparison.Ordinal));
        Assert.Contains("CURLOPT_FTP_SKIP_PASV_IP", source);
        Assert.DoesNotContain("CURLOPT_MAXREDIRS", source);
    }

    [TestMethod]
    [DataRow("127.0.0.1:47652/q?x=1&y=\\\"z\\\"", "\"127.0.0.1:47652/q\\?x=1&y=\\\\\\\"z\\\\\\\"\"")]
    [DataRow("a\nb\rc\td", "\"a\\nb\\rc\\td\"")]
    [DataRow("é\u0001\u007F~ ", "\"\\xc3\\xa9\\x01\\x7f~ \"")]
    [DataRow("", "\"\"")]
    public void QuoteCString_EscapesAsCurlDoes(string value, string expected)
    {
        Diagnostics.Arrange("value", value);

        string actual = LibcurlSourceCode.QuoteCString(value);
        Diagnostics.Act("quoted", actual);

        Diagnostics.Diff("quoted", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    [TestMethod]
    public void QuoteCString_Null_Throws()
    {
        Diagnostics.Arrange("value", "null");

        ArgumentNullException exception = Assert.ThrowsExactly<ArgumentNullException>(() => LibcurlSourceCode.QuoteCString(null!));

        Diagnostics.Act("exception", exception.GetType().Name);
        Diagnostics.Assert("exception", nameof(ArgumentNullException), exception.GetType().Name);
    }

    [TestMethod]
    public void QuoteCString_LongerThanTheLimit_IsCutAndEndsInDots()
    {
        Diagnostics.Arrange("value lengths", "2001 and 2000 characters of 'a'");

        string cut = LibcurlSourceCode.QuoteCString(new string('a', 2001));
        string whole = LibcurlSourceCode.QuoteCString(new string('a', 2000));
        Diagnostics.Act("quoted length of 2001 characters", cut.Length);
        Diagnostics.Act("quoted length of 2000 characters", whole.Length);

        Diagnostics.Assert("2001 characters cut", "\"" + new string('a', 2000) + "...\"", cut);
        Diagnostics.Assert("2000 characters whole", "\"" + new string('a', 2000) + "\"", whole);
        Assert.AreEqual("\"" + new string('a', 2000) + "...\"", cut);
        Assert.AreEqual("\"" + new string('a', 2000) + "\"", whole);
    }

    [TestMethod]
    public void Parse_Libcurl_IsGlobalAndTheLastValueWins()
    {
        string[] arguments = ["--libcurl", "a.c", "http://x/", "--next", "--libcurl", "b.c", "http://y/"];
        Diagnostics.ArrangeArguments(arguments);

        CommandLineParseResult result = CommandLineParser.Parse(arguments);
        Diagnostics.ActParse(result);

        Diagnostics.Assert("accepted", true, result.IsAccepted);
        Diagnostics.Assert("first group file", "b.c", result.Groups[0].LibcurlFile);
        Diagnostics.Assert("second group file", "b.c", result.Groups[1].LibcurlFile);
        Assert.IsTrue(result.IsAccepted);
        Assert.AreEqual("b.c", result.Groups[0].LibcurlFile);
        Assert.AreEqual("b.c", result.Groups[1].LibcurlFile);
        string? withoutOption = Parse("http://x/").LibcurlFile;
        Diagnostics.Assert("file without the option", "null", withoutOption ?? "null");
        Assert.IsNull(withoutOption);
    }

    [TestMethod]
    public void AiHelp_Libcurl_NoLongerSaysItIsUnsupported()
    {
        Diagnostics.Arrange("topic", "all");

        bool found = CurlAiHelpText.TryGetMarkdown("all", out string markdown);
        Diagnostics.Act("found", found);
        Assert.IsTrue(found);
        string section = markdown[markdown.IndexOf("## --libcurl", StringComparison.Ordinal)..];
        section = section[..section.IndexOf("\n## ", 1, StringComparison.Ordinal)];
        Diagnostics.Act("section length", section.Length);

        Diagnostics.Assert("contains unsupported text", false, section.Contains("Not supported by this build yet", StringComparison.Ordinal));
        Assert.DoesNotContain("Not supported by this build yet", section);
    }

    private static string SilentHttpTransfer(string path) =>
        "  curl_easy_setopt(curl, CURLOPT_BUFFERSIZE, 102400L);\n"
        + $"  curl_easy_setopt(curl, CURLOPT_URL, \"http://127.0.0.1:47652/{path}\");\n"
        + "  curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L);\n"
        + "  curl_easy_setopt(curl, CURLOPT_USERAGENT, \"curl/8.21.0\");\n"
        + "  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);\n"
        + TlsAndKeepAlive
        + Perform;

    /// <summary>Writes the arguments as an <c>ARRANGE</c> line, then parses them and returns the options.</summary>
    private CommandLineOptions Parse(params string[] arguments)
    {
        Diagnostics.ArrangeArguments(arguments);
        return CommandLineParser.Parse(arguments).Options!;
    }

    /// <summary>Generates the source for <paramref name="transfers"/> and writes it as an <c>ACT</c> line.</summary>
    private string GenerateSource(IReadOnlyList<(CommandLineOptions, string)> transfers)
    {
        string source = LibcurlSourceCode.Generate(transfers);
        Diagnostics.Act("source", source);
        return source;
    }
}
