using Curl.Protocol.Abstractions;
using Curl.Testing;

namespace Curl.Cookies;

/// <summary>
/// Pins <see cref="NetscapeCookieFile"/> and <see cref="CookieStore"/>'s cookie-file members to curl 8.21.0
/// (<c>x86_64-w64-mingw32</c>, Schannel, libpsl), measured on 2026-09-26: curl loaded the file written here
/// with <c>-b</c> (or received the headers written here from <c>Record-CurlExchange.ps1</c>) and the
/// expected text is the <c>-c</c> jar it wrote, byte for byte; the Windows build ends jar lines with CR LF.
/// BL-221's Notes record each command.
/// </summary>
[TestClass]
public sealed class NetscapeCookieFileTests
{
    /// <summary>Gets or sets the context MSTest gives the running test; its diagnostics are written through it.</summary>
    public TestContext TestContext { get; set; } = null!;

    private const string Header =
        "# Netscape HTTP Cookie File\r\n# https://curl.se/docs/http-cookies.html\r\n# This file was generated by libcurl! Edit at your own risk.\r\n\r\n";

    private static readonly DateTimeOffset Now = DateTimeOffset.FromUnixTimeSeconds(1_790_460_351);

    /// <summary>
    /// Measured: <c>curl -c jar.txt http://localhost:18221/p/x</c>, the response setting <c>a=1; Path=/</c>,
    /// <c>h=2; HttpOnly; Path=/p</c>, <c>d=3; Domain=localhost; Max-Age=3600</c>, <c>s=4; Secure; HttpOnly</c>
    /// and <c>q="x y"</c>. Newest first, <c>#HttpOnly_</c> before the domain, a dot before a domain cookie's.
    /// </summary>
    [TestMethod]
    public void WriteCookieJar_ReceivedCookies_MatchesCurlsJarByteForByte()
    {
        DateTimeOffset received = DateTimeOffset.FromUnixTimeSeconds(1_790_463_538);
        CurlUrl url = CurlUrl.Parse("http://localhost:18221/p/x");
        string[] headers = ["a=1; Path=/", "h=2; HttpOnly; Path=/p", "d=3; Domain=localhost; Max-Age=3600", "s=4; Secure; HttpOnly", "q=\"x y\""];
        CookieStore store = new();
        Diagnostics.ArrangeSetCookies(url, headers, received);

        store.StoreFromResponse(url, headers, received, NoTransferEvents.Instance);
        string actual = WriteJar(store, received);

        string expected =
            Header
            + "localhost\tFALSE\t/p\tFALSE\t0\tq\t\"x y\"\r\n"
            + "#HttpOnly_localhost\tFALSE\t/p\tTRUE\t0\ts\t4\r\n"
            + ".localhost\tTRUE\t/p\tFALSE\t1790467138\td\t3\r\n"
            + "#HttpOnly_localhost\tFALSE\t/p\tFALSE\t0\th\t2\r\n"
            + "localhost\tFALSE\t/\tFALSE\t0\ta\t1\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>Measured: <c>curl -c empty.txt</c> against a response with no cookie writes the 135-byte header alone.</summary>
    [TestMethod]
    public void WriteCookieJar_NoCookies_WritesTheHeaderAlone()
    {
        Diagnostics.Arrange("cookies in the store", 0);

        string jar = WriteJar(new CookieStore(), Now);

        Diagnostics.AssertText("cookie jar", Header, jar);
        Assert.AreEqual(Header, jar);
        Diagnostics.Assert("cookie jar length", 135, jar.Length);
        Assert.AreEqual(135, jar.Length);
    }

    /// <summary>
    /// Measured: <c>curl -b in.txt -c out.txt http://127.0.0.1:18221/</c>. Comments and blank, malformed,
    /// eight-field and bad-expiry lines are skipped; six fields mean an empty value; <c>true</c> counts as
    /// <c>TRUE</c>; the file's last line is the jar's first.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_MixedLines_KeepsWhatCurlKeeps()
    {
        CookieStore store = Load(InTxt, discardSessionCookies: false);

        string expected =
            Header
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tlower\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tempty\t\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tnoval\t\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsp ace\tv v\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tdom\t2\r\n"
            + "#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t0\tho\t1\r\n";
        string actual = WriteJar(store, Now);

        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>Measured: the same file with <c>-j</c> keeps only the cookie with an expiry.</summary>
    [TestMethod]
    public void LoadCookieFile_DiscardSessionCookies_KeepsOnlyCookiesWithAnExpiry()
    {
        CookieStore store = Load(InTxt, discardSessionCookies: true);

        string expected = Header + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\r\n";
        string actual = WriteJar(store, Now);

        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Measured: <c>curl -b in2.txt -c out2.txt http://127.0.0.1:18221/p/x</c>. Domain dots and flags are
    /// normalised; a path field that starts <c>TRUE</c> is the secure field; expired, signed, too-large and
    /// bad-prefix lines are dropped; an empty name or domain, and a domain with spaces, are kept.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_FieldEdgeCases_NormalisesAsCurlDoes()
    {
        const string File =
            "127.0.0.1\tTRUE\t/\tFALSE\t0\tA1\t1\n"
            + ".127.0.0.1\tFALSE\t/\tFALSE\t0\tA2\t2\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t5\tA3\t3\n"
            + "127.0.0.1\tFALSE\t/\tT\t0\tA4\t4\n"
            + "127.0.0.1\tFALSE\t/\tyes\t0\tA5\t5\n"
            + "127.0.0.1\tFALSE\tTRUE\t0\tA6\t6\n"
            + "127.0.0.1\tFALSE\tnoslash\tFALSE\t0\tA7\t7\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t__Secure-A8\t8\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\t__Host-A9\t9\n"
            + "127.0.0.1\tFALSE\t/p\tTRUE\t0\t__Host-A10\t10\n"
            + "127.0.0.1\tTRUE\t/\tTRUE\t0\t__Host-A11\t11\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t-5\tA12\t12\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t+7\tA13\t13\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t\t14\n"
            + "\tFALSE\t/\tFALSE\t0\tA15\t15\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA16\t1\t6\n"
            + "127.0.0.1\tTRU\t/\tFALSE\t0\tA17\t17\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA18\t1 8 \n"
            + "  127.0.0.1\tFALSE\t/\tFALSE\t0\tA19\t19\n"
            + "127.0.0.1\tFALSE\t/p/\tFALSE\t0\tA20\t20\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t99999999999999999999\tA21\t21\n";

        CookieStore store = Load(File, discardSessionCookies: false);

        string expectedJar =
            Header
            + "127.0.0.1\tFALSE\t/p\tFALSE\t0\tA20\t20\r\n"
            + "  127.0.0.1\tFALSE\t/\tFALSE\t0\tA19\t19\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA18\t1 8 \r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tA17\t17\r\n"
            + "\tFALSE\t/\tFALSE\t0\tA15\t15\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t\t14\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\t__Host-A9\t9\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA7\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tA6\t6\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA5\t5\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tA4\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA2\t2\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tA1\t1\r\n";
        string actualJar = WriteJar(store, Now);
        const string ExpectedHeader = "A20=20; __Host-A9=9; A18=1 8 ; A17=17; A7=7; A6=6; A5=5; A4=4; A2=2; A1=1; =14";
        CurlUrl requestUrl = CurlUrl.Parse("http://127.0.0.1:18221/p/x");
        Diagnostics.Arrange("request URL", requestUrl.OriginalString);
        string? actualHeader = store.GetCookieHeader(requestUrl, secure: false, Now);
        Diagnostics.ActText("Cookie header", actualHeader);

        Diagnostics.AssertText("cookie jar", expectedJar, actualJar);
        Assert.AreEqual(expectedJar, actualJar);
        Diagnostics.AssertText("Cookie header", ExpectedHeader, actualHeader);
        Assert.AreEqual(ExpectedHeader, actualHeader);
    }

    /// <summary>
    /// Measured: <c>curl -b td.txt -c -</c>. A path field that is the start of <c>TRUE</c> or <c>FALSE</c>
    /// (empty included), in that case, becomes the secure field; the start of <c>TRUE</c> in any case, an
    /// empty field included, is true.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_BooleanWords_ReadAsCurlReadsThem()
    {
        const string File =
            "h\tFALSE\tT\t0\tD1\t1\n"
            + "h\tFALSE\t\t0\tD2\t2\n"
            + "h\tFALSE\tFALS\t0\tD3\t3\n"
            + "h\tFALSE\ttrue\t0\tD4\t4\n"
            + "h\tFALSE\tTRUEX\tTRUE\t0\tD5\t5\n"
            + "h\tFALSE\tTRUE\t0\tD6\n"
            + "h\tFALSE\t/\t\t0\tD7\t7\n"
            + "h\t\t/\tFALSE\t0\tD8\t8\n"
            + "h\tFALSE\t/\tFALSE\t0\tD9\t9\t\n"
            + "h\tFALSE\t/\tFALSE\t0\tD10\n"
            + "h\tFALSE\t/\tFALSE\t0\n";

        string actual = WriteJar(Load(File, discardSessionCookies: false), Now);

        string expected =
            Header
            + "h\tFALSE\t/\tFALSE\t0\tD10\t\r\n"
            + ".h\tTRUE\t/\tFALSE\t0\tD8\t8\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD7\t7\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD6\t\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD5\t5\r\n"
            + "h\tFALSE\t/\tFALSE\t0\tD3\t3\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD2\t2\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD1\t1\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Measured: <c>curl -b in4.txt -c out4.txt</c> and <c>curl -b tcc.txt -c -</c>. Quotes stay on a value
    /// and come off a path; a carriage return ends the line; a control character refuses the name or value
    /// but not the domain or path; <c>#httponly_</c> is a comment; bytes above 127 pass through.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_CharacterEdgeCases_ReadAsCurlReadsThem()
    {
        const string File =
            "127.0.0.1\tFALSE\t/\tFALSE\t0\tB5\t\"q\"\n"
            + "127.0.0.1\tFALSE\t\"/p\"\tFALSE\t0\tB6\t6\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB7\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB9\ta\u0001b\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t00\tB10\t10\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800abc\tB1\t1\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t\tB3\t3\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t9223372036854775807\tB4\t4\n"
            + "#httponly_127.0.0.1\tFALSE\t/\tFALSE\t0\tC1\t1\n"
            + "127.0.0.1\u0001\tFALSE\t/\tFALSE\t0\tC2\t2\n"
            + "127.0.0.1\tFALSE\t/\u0001\tFALSE\t0\tC3\t3\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC4\ta\u007Fb\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC\u00025\t5\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC6\ta\rb\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC8\taÃ©b\n"
            + "#HttpOnly_\tFALSE\t/\tFALSE\t0\tC9\t9\n"
            + "..h\tTRUE\t/\tFALSE\t0\tE1\t1\n"
            + "..g\tFALSE\t/\tFALSE\t0\tE2\t2\n";

        string actual = WriteJar(Load(File, discardSessionCookies: false), Now);

        string expected =
            Header
            + ".g\tFALSE\t/\tFALSE\t0\tE2\t2\r\n"
            + ".h\tTRUE\t/\tFALSE\t0\tE1\t1\r\n"
            + "#HttpOnly_\tFALSE\t/\tFALSE\t0\tC9\t9\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC8\taÃ©b\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC6\ta\r\n"
            + "127.0.0.1\tFALSE\t/\u0001\tFALSE\t0\tC3\t3\r\n"
            + "127.0.0.1\u0001\tFALSE\t/\tFALSE\t0\tC2\t2\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t9223372036854775807\tB4\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tB1\t1\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB10\t10\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB7\t7\r\n"
            + "127.0.0.1\tFALSE\t/p\tFALSE\t0\tB6\t6\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB5\t\"q\"\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>Measured: <c>curl -b te.txt -c -</c>. A later namesake (domain in any case) replaces an earlier one in its place.</summary>
    [TestMethod]
    public void LoadCookieFile_Namesakes_ReplaceInPlace()
    {
        const string File =
            "h\tFALSE\t/\tFALSE\t0\tX\t1\n"
            + "h\tFALSE\t/\tFALSE\t0\tY\t1\n"
            + "H\tFALSE\t/\tFALSE\t0\tX\t2\n"
            + "h\tTRUE\t/\tFALSE\t0\tX\t3\n";

        string actual = WriteJar(Load(File, discardSessionCookies: false), Now);

        string expected = Header + ".h\tTRUE\t/\tFALSE\t0\tX\t3\r\nh\tFALSE\t/\tFALSE\t0\tY\t1\r\nH\tFALSE\t/\tFALSE\t0\tX\t2\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Measured: a cookie line followed by <c>after</c>, loaded with <c>-b</c>. A line of up to 4998
    /// characters before its line feed, a carriage return counted, is read; a longer one ends the reading,
    /// so neither it nor anything after it is loaded. A last line without a line feed has the same limit.
    /// </summary>
    [TestMethod]
    [DataRow(4998, "\n", "after len")]
    [DataRow(4999, "\n", "")]
    [DataRow(4998, "\r\n", "after len")]
    [DataRow(4999, "\r\n", "")]
    public void Read_LongLine_StopsReadingPastTheLimit(int lengthBeforeLineFeed, string lineEnd, string expectedNames)
    {
        string line = CookieLineOfLength("len", lengthBeforeLineFeed - (lineEnd.Length - 1)) + lineEnd;
        string file = line + "127.0.0.1\tFALSE\t/\tFALSE\t0\tafter\t1" + lineEnd;

        Diagnostics.Arrange("line length before the line feed", lengthBeforeLineFeed);
        Diagnostics.ArrangeText("line ending", lineEnd);
        Diagnostics.ArrangeText("cookie file read in", file);
        Diagnostics.Arrange("clock Unix seconds", Now.ToUnixTimeSeconds());

        IReadOnlyList<Cookie> cookies = NetscapeCookieFile.Read(new StringReader(file), Now);
        string actualNames = string.Join(' ', cookies.Reverse().Select(cookie => cookie.Name));

        Diagnostics.ActCookies("cookies read", cookies);
        Diagnostics.AssertText("names of the cookies read, oldest first", expectedNames, actualNames);
        Assert.AreEqual(expectedNames, actualNames);
    }

    /// <summary>Measured: a last line with no line feed, after <c>before</c>, loads at 4998 characters and not at 4999.</summary>
    [TestMethod]
    [DataRow(4998, "len before")]
    [DataRow(4999, "before")]
    public void Read_LastLineWithoutLineFeed_HasTheSameLimit(int length, string expectedNames)
    {
        string file = "127.0.0.1\tFALSE\t/\tFALSE\t0\tbefore\t1\n" + CookieLineOfLength("len", length);

        Diagnostics.Arrange("last line length", length);
        Diagnostics.ArrangeText("cookie file read in", file);
        Diagnostics.Arrange("clock Unix seconds", Now.ToUnixTimeSeconds());

        IReadOnlyList<Cookie> cookies = NetscapeCookieFile.Read(new StringReader(file), Now);
        string actualNames = string.Join(' ', cookies.Reverse().Select(cookie => cookie.Name));

        Diagnostics.ActCookies("cookies read", cookies);
        Diagnostics.AssertText("names of the cookies read, oldest first", expectedNames, actualNames);
        Assert.AreEqual(expectedNames, actualNames);
    }

    [TestMethod]
    public void Read_EmptyText_ReadsNothing()
    {
        Diagnostics.ArrangeText("cookie file read in", string.Empty);

        IReadOnlyList<Cookie> cookies = NetscapeCookieFile.Read(new StringReader(string.Empty), Now);

        Diagnostics.ActCookies("cookies read", cookies);
        Diagnostics.Assert("cookies read", 0, cookies.Count);
        Assert.IsEmpty(cookies);
    }

    [TestMethod]
    public void ParseLine_HttpOnlyLine_ReadsEveryField()
    {
        const string Line = "#HttpOnly_.example.test\tTRUE\t/p\tTRUE\t1234\tn\tv";
        Cookie expected = new("n", "v", "example.test", true, "/p", true, true, 1234);
        Diagnostics.ArrangeText("cookie file line", Line);

        Cookie? actual = NetscapeCookieFile.ParseLine(Line, Now);

        Diagnostics.Act("parsed cookie", actual is null ? "(null)" : CookieTestDiagnostics.ShownCookies([actual]));
        Diagnostics.Assert(
            "parsed cookie",
            CookieTestDiagnostics.ShownCookies([expected]),
            actual is null ? "(null)" : CookieTestDiagnostics.ShownCookies([actual]));
        Assert.AreEqual(expected, actual);
    }

    [TestMethod]
    public void ParseLine_TooFewFieldsForAMadeUpPath_IsRefused()
    {
        Diagnostics.ArrangeText("cookie file line", "h\tFALSE");

        Cookie? parsed = NetscapeCookieFile.ParseLine("h\tFALSE", Now);

        Diagnostics.Act("parsed cookie", parsed is null ? "(null)" : CookieTestDiagnostics.ShownCookies([parsed]));
        Diagnostics.Assert("parsed cookie", "(null)", parsed is null ? "(null)" : CookieTestDiagnostics.ShownCookies([parsed]));
        Assert.IsNull(parsed);
    }

    [TestMethod]
    public void Write_CookiesInTheGivenOrder_UsesTheWritersLineEnding()
    {
        StringWriter writer = new() { NewLine = "\n" };
        Cookie[] cookies = [new Cookie("a", "1", "h", false, "/", false, false, 0)];
        Diagnostics.Arrange("cookies to write", CookieTestDiagnostics.ShownCookies(cookies));
        Diagnostics.ArrangeText("writer line ending", writer.NewLine);

        NetscapeCookieFile.Write(writer, cookies);
        string actual = writer.ToString();

        string expected = Header.Replace("\r\n", "\n", StringComparison.Ordinal) + "h\tFALSE\t/\tFALSE\t0\ta\t1\n";
        Diagnostics.ActText("text written", actual);
        Diagnostics.AssertText("text written", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    [TestMethod]
    public void NullArguments_Throw()
    {
        Diagnostics.Arrange("clock Unix seconds", Now.ToUnixTimeSeconds());

        ArgumentNullException readNullReader = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Read(null!, Now));
        LogThrown("Read(null reader)", readNullReader);
        ArgumentNullException readNullOptions = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Read(new StringReader(string.Empty), Now, null!));
        LogThrown("Read(reader, now, null third argument)", readNullOptions);
        ArgumentNullException parseNullLine = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.ParseLine(null!, Now));
        LogThrown("ParseLine(null line)", parseNullLine);
        ArgumentNullException writeNullWriter = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Write(null!, []));
        LogThrown("Write(null writer, no cookies)", writeNullWriter);
        ArgumentNullException writeNullCookies = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Write(new StringWriter(), null!));
        LogThrown("Write(writer, null cookies)", writeNullCookies);
        ArgumentNullException formatNullCookie = Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.FormatLine(null!));
        LogThrown("FormatLine(null cookie)", formatNullCookie);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in2.txt -c jar2.txt http://127.0.0.1:18273/x/y</c> at 1790486502. A
    /// <c>Set-Cookie:</c> line, in any case and followed by any blanks, is a header with no request: <c>Domain</c>,
    /// even an IP address, includes subdomains; <c>Expires</c> is capped at 400 days and <c>Max-Age</c> counts
    /// from the load; expired ones are gone; a line without <c>Domain</c> is left out of the jar; a line
    /// starting with a space is a malformed Netscape line.
    /// </summary>
    [TestMethod]
    public void WriteCookieJar_SetCookieLines_MatchesCurlsJarByteForByte()
    {
        DateTimeOffset loaded = DateTimeOffset.FromUnixTimeSeconds(1_790_486_502);
        CookieStore store = new();
        Diagnostics.ArrangeText("cookie file read in", In2Txt);
        Diagnostics.Arrange("clock Unix seconds", loaded.ToUnixTimeSeconds());
        store.LoadCookieFile(new StringReader(In2Txt), discardSessionCookies: false, loaded);
        string actual = WriteJar(store, loaded);

        string expected =
            Header
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tii\tnet\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\thh\tnet\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tgg\tnet\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tgg\t7\r\n"
            + ".127.0.0.1\tTRUE\t/x\tFALSE\t0\tff\t6\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t1790486602\tcc\t3\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t1825046520\tbb\t2\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t1825046520\ta\t1\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>
    /// Measured (BL-273): the same run sent this <c>Cookie</c> header. A cookie without <c>Domain</c> goes to
    /// every host and one without <c>Path</c> to every path, sorting after the cookies that have them.
    /// </summary>
    [TestMethod]
    public void GetCookieHeader_SetCookieLines_SendsWhatCurlSent()
    {
        DateTimeOffset loaded = DateTimeOffset.FromUnixTimeSeconds(1_790_486_502);
        CookieStore store = new();
        CurlUrl url = CurlUrl.Parse("http://127.0.0.1:18273/x/y");
        Diagnostics.ArrangeText("cookie file read in", In2Txt);
        Diagnostics.Arrange("clock Unix seconds", loaded.ToUnixTimeSeconds());
        Diagnostics.Arrange("request URL", url.OriginalString);
        store.LoadCookieFile(new StringReader(In2Txt), discardSessionCookies: false, loaded);

        string? actual = store.GetCookieHeader(url, secure: false, loaded);

        const string Expected = "ff=6; lower=l1; ii=net; hh=net; gg=net; gg=7; cc=3; bb=2; a=1; __Secure-s=10; hh=8; q=13";
        Diagnostics.ActText("Cookie header", actual);
        Diagnostics.AssertText("Cookie header", Expected, actual);
        Assert.AreEqual(Expected, actual);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in.txt -c jar.txt http://127.0.0.1:18273/</c>, the file mixing a
    /// Netscape line with <c>Set-Cookie:</c> lines. Only the cookies with a <c>Domain</c> reach the jar;
    /// <c>Set-Cookie2:</c> and a line with no <c>=</c> are skipped; <c>Secure</c> is kept.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_NetscapeAndSetCookieLines_KeepsWhatCurlKeeps()
    {
        DateTimeOffset loaded = DateTimeOffset.FromUnixTimeSeconds(1_790_486_461);
        CookieStore store = new();
        const string File =
            "example.com\tFALSE\t/\tFALSE\t0\tnet1\tv1\n"
            + "Set-Cookie: plain=p1\n"
            + "set-cookie:   lower=l1; Path=/x\n"
            + "SET-COOKIE: dom=d1; Domain=.example.com; Path=/\n"
            + "Set-Cookie: exp=e1; Expires=Wed, 01 Jan 2031 00:00:00 GMT\n"
            + "Set-Cookie: old=o1; Expires=Wed, 01 Jan 2001 00:00:00 GMT\n"
            + "Set-Cookie: sec=s1; Secure; HttpOnly; domain=127.0.0.1\n"
            + "Set-Cookie: ma=m1; Max-Age=100\n"
            + "Set-Cookie: far=f1; Expires=Wed, 01 Jan 2099 00:00:00 GMT\n"
            + "Set-Cookie:nospace=n1; domain=127.0.0.1; path=/\n"
            + "Set-Cookie2: two=t2\n"
            + "Set-Cookie: bad\n";
        CurlUrl url = CurlUrl.Parse("http://127.0.0.1:18273/");
        Diagnostics.ArrangeText("cookie file read in", File);
        Diagnostics.Arrange("clock Unix seconds", loaded.ToUnixTimeSeconds());
        Diagnostics.Arrange("request URL", url.OriginalString);

        store.LoadCookieFile(new StringReader(File), discardSessionCookies: false, loaded);
        string? actualHeader = store.GetCookieHeader(url, secure: false, loaded);
        Diagnostics.ActText("Cookie header", actualHeader);
        string actualJar = WriteJar(store, loaded);

        const string ExpectedHeader = "nospace=n1; sec=s1; plain=p1; far=f1; exp=e1; ma=m1";
        Diagnostics.AssertText("Cookie header", ExpectedHeader, actualHeader);
        Assert.AreEqual(ExpectedHeader, actualHeader);
        string expectedJar =
            Header
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tnospace\tn1\r\n"
            + "#HttpOnly_.127.0.0.1\tTRUE\t/\tTRUE\t0\tsec\ts1\r\n"
            + ".example.com\tTRUE\t/\tFALSE\t0\tdom\td1\r\n"
            + "example.com\tFALSE\t/\tFALSE\t0\tnet1\tv1\r\n";
        Diagnostics.AssertText("cookie jar", expectedJar, actualJar);
        Assert.AreEqual(expectedJar, actualJar);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in3.txt -c jar3.txt http://127.0.0.1:18273/</c>. A <c>Set-Cookie:</c>
    /// line without <c>Path</c> is not the namesake of one with the path <c>/</c>, sorts after it, and is
    /// written with <c>/</c>; two lines with neither <c>Domain</c> nor <c>Path</c> are namesakes.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_SetCookieLinesWithoutPath_KeepAnEmptyPath()
    {
        CookieStore store = Load(
            "Set-Cookie: yy=1; domain=127.0.0.1; path=/\n"
            + "Set-Cookie: zz=2; domain=127.0.0.1\n"
            + "Set-Cookie: nn=3; domain=127.0.0.1\n"
            + "127.0.0.1\tTRUE\t/\tFALSE\t0\tnn\tnet\n"
            + "127.0.0.1\tTRUE\t/\tFALSE\t0\tmm\tnet\n"
            + "Set-Cookie: mm=4; domain=127.0.0.1\n"
            + "Set-Cookie: kk=5\n"
            + "Set-Cookie: kk=6\n"
            + "Set-Cookie: jj=5; path=/\n"
            + "Set-Cookie: jj=6\n",
            discardSessionCookies: false);

        CurlUrl url = CurlUrl.Parse("http://127.0.0.1:18273/");
        Diagnostics.Arrange("request URL", url.OriginalString);
        string? actualHeader = store.GetCookieHeader(url, secure: false, Now);
        Diagnostics.ActText("Cookie header", actualHeader);
        string actualJar = WriteJar(store, Now);

        const string ExpectedHeader = "mm=net; nn=net; yy=1; jj=5; mm=4; nn=3; zz=2; jj=6; kk=6";
        Diagnostics.AssertText("Cookie header", ExpectedHeader, actualHeader);
        Assert.AreEqual(ExpectedHeader, actualHeader);
        string expectedJar =
            Header
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tmm\t4\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tmm\tnet\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tnn\tnet\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tnn\t3\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tzz\t2\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tyy\t1\r\n";
        Diagnostics.AssertText("cookie jar", expectedJar, actualJar);
        Assert.AreEqual(expectedJar, actualJar);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in4.txt</c> sends only <c>__Host-b=1</c>: a <c>__Host-</c> cookie from a
    /// <c>Set-Cookie:</c> line needs <c>Path=/</c> and no <c>Domain</c>.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_HostPrefixedSetCookieLines_KeepsOnlyTheOneWithPathSlash()
    {
        CookieStore store = Load(
            "Set-Cookie: __Host-a=1; Secure\n"
            + "Set-Cookie: __Host-b=1; Secure; Path=/\n"
            + "Set-Cookie: __Host-c=1; Secure; Path=/; domain=127.0.0.1\n",
            discardSessionCookies: false);

        CurlUrl url = CurlUrl.Parse("http://127.0.0.1:18273/");
        Diagnostics.Arrange("request URL", url.OriginalString);
        string? actual = store.GetCookieHeader(url, secure: false, Now);

        Diagnostics.ActText("Cookie header", actual);
        Diagnostics.AssertText("Cookie header", "__Host-b=1", actual);
        Assert.AreEqual("__Host-b=1", actual);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in5.txt -c jar5.txt --resolve foo.test:18273:127.0.0.1</c>, twice to
    /// <c>http://foo.test:18273/</c>, the response setting <c>s=2</c> and <c>t=2</c>. <c>Secure</c> cookies from
    /// <c>Set-Cookie:</c> lines without <c>Path</c> do not stop an insecure origin setting their names.
    /// </summary>
    [TestMethod]
    public void StoreFromResponse_SecureSetCookieLinesWithoutPath_DoNotBlockInsecureNamesakes()
    {
        CookieStore store = Load("Set-Cookie: s=1; Secure\nSet-Cookie: t=1; Secure; domain=foo.test\n", discardSessionCookies: false);
        CurlUrl foo = CurlUrl.Parse("http://foo.test:18273/");

        string[] headers = ["s=2", "t=2"];
        Diagnostics.ArrangeSetCookies(foo, headers, Now);

        store.StoreFromResponse(foo, headers, Now, NoTransferEvents.Instance);
        string? actualHeader = store.GetCookieHeader(foo, secure: false, Now);
        Diagnostics.ActText("Cookie header", actualHeader);
        string actualJar = WriteJar(store, Now);

        Diagnostics.AssertText("Cookie header", "t=2; s=2", actualHeader);
        Assert.AreEqual("t=2; s=2", actualHeader);
        string expectedJar =
            Header
            + "foo.test\tFALSE\t/\tFALSE\t0\tt\t2\r\n"
            + "foo.test\tFALSE\t/\tFALSE\t0\ts\t2\r\n"
            + ".foo.test\tTRUE\t/\tTRUE\t0\tt\t1\r\n";
        Diagnostics.AssertText("cookie jar", expectedJar, actualJar);
        Assert.AreEqual(expectedJar, actualJar);
    }

    /// <summary>
    /// Measured (BL-273): the same run with <c>in6.txt</c>, both lines given <c>Path=/</c>. The one with a
    /// <c>Domain</c> now blocks <c>t=2</c>; the one without still does not block <c>s=2</c>.
    /// </summary>
    [TestMethod]
    public void StoreFromResponse_SecureSetCookieLineWithoutDomain_DoesNotBlockAnInsecureNamesake()
    {
        CookieStore store = Load("Set-Cookie: s=1; Secure; Path=/\nSet-Cookie: t=1; Secure; domain=foo.test; Path=/\n", discardSessionCookies: false);
        CurlUrl foo = CurlUrl.Parse("http://foo.test:18273/");

        string[] headers = ["s=2", "t=2"];
        Diagnostics.ArrangeSetCookies(foo, headers, Now);

        store.StoreFromResponse(foo, headers, Now, NoTransferEvents.Instance);
        string? actualHeader = store.GetCookieHeader(foo, secure: false, Now);
        Diagnostics.ActText("Cookie header", actualHeader);
        string actualJar = WriteJar(store, Now);

        Diagnostics.AssertText("Cookie header", "s=2", actualHeader);
        Assert.AreEqual("s=2", actualHeader);
        string expectedJar =
            Header
            + "foo.test\tFALSE\t/\tFALSE\t0\ts\t2\r\n"
            + ".foo.test\tTRUE\t/\tTRUE\t0\tt\t1\r\n";
        Diagnostics.AssertText("cookie jar", expectedJar, actualJar);
        Assert.AreEqual(expectedJar, actualJar);
    }

    /// <summary>
    /// Measured (BL-273): <c>curl -b in7.txt -c jar7.txt --resolve bar.test:18273:127.0.0.1 http://bar.test:18273/</c>,
    /// the response setting <c>t=2</c>: a <c>Secure</c> namesake on an unrelated domain does not block it.
    /// </summary>
    [TestMethod]
    public void StoreFromResponse_SecureNamesakeOnAnotherDomain_DoesNotBlockIt()
    {
        CookieStore store = Load("Set-Cookie: t=1; Secure; domain=foo.test; Path=/\n", discardSessionCookies: false);

        CurlUrl bar = CurlUrl.Parse("http://bar.test:18273/");
        string[] headers = ["t=2"];
        Diagnostics.ArrangeSetCookies(bar, headers, Now);

        store.StoreFromResponse(bar, headers, Now, NoTransferEvents.Instance);
        string actual = WriteJar(store, Now);

        string expected =
            Header
            + "bar.test\tFALSE\t/\tFALSE\t0\tt\t2\r\n"
            + ".foo.test\tTRUE\t/\tTRUE\t0\tt\t1\r\n";
        Diagnostics.AssertText("cookie jar", expected, actual);
        Assert.AreEqual(expected, actual);
    }

    /// <summary>The measured <c>in2.txt</c> (BL-273).</summary>
    private const string In2Txt =
        "Set-Cookie: a=1; domain=127.0.0.1; Expires=Wed, 01 Jan 2031 00:00:00 GMT\n"
        + "Set-Cookie: bb=2; domain=127.0.0.1; Expires=Wed, 01 Jan 2099 00:00:00 GMT\n"
        + "Set-Cookie: cc=3; domain=127.0.0.1; Max-Age=100\n"
        + "Set-Cookie: dd=4; domain=127.0.0.1; Max-Age=0\n"
        + "Set-Cookie: ee=5; domain=127.0.0.1; Expires=Wed, 01 Jan 2001 00:00:00 GMT\n"
        + "Set-Cookie: ff=6; domain=127.0.0.1; path=/x/\n"
        + "sEt-CoOkIe:\t lower=l1; Path=/x\n"
        + "Set-Cookie: gg=7; domain=127.0.0.1\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tgg\tnet\n"
        + "Set-Cookie: hh=8\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\thh\tnet\n"
        + "Set-Cookie: __Host-h=9\n"
        + "Set-Cookie: __Secure-s=10; Secure\n"
        + "Set-Cookie: ii=11; domain=127.0.0.1; path=/\n"
        + "127.0.0.1\tTRUE\t/\tFALSE\t0\tii\tnet\n"
        + " Set-Cookie: sp=12\n"
        + "Set-Cookie:  \n"
        + "Set-Cookie: q=13\r\n";

    /// <summary>The measured <c>in.txt</c>.</summary>
    private const string InTxt =
        "# comment\n\n"
        + "#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t0\tho\t1\n"
        + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tdom\t2\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\t4\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsp ace\tv v\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tnoval\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tempty\t\n"
        + "bad line\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\tabc\tnum\t5\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tseven\t6\textra\n"
        + "127.0.0.1\tfalse\t/\ttrue\t0\tlower\t7\n";

    private TestDiagnostics Diagnostics => TestDiagnostics.For(TestContext);

    private CookieStore Load(string file, bool discardSessionCookies)
    {
        Diagnostics.ArrangeText("cookie file read in", file);
        Diagnostics.Arrange("discard session cookies", discardSessionCookies);
        Diagnostics.Arrange("clock Unix seconds", Now.ToUnixTimeSeconds());
        CookieStore store = new();
        store.LoadCookieFile(new StringReader(file), discardSessionCookies, Now);
        return store;
    }

    private string WriteJar(CookieStore store, DateTimeOffset now)
    {
        StringWriter writer = new() { NewLine = "\r\n" };
        store.WriteCookieJar(writer, now);
        string jar = writer.ToString();
        Diagnostics.ActText($"cookie jar written at Unix {now.ToUnixTimeSeconds()}", jar);
        return jar;
    }

    private void LogThrown(string call, Exception thrown)
    {
        Diagnostics.ActText($"{call} throws", thrown.GetType().Name + ": " + thrown.Message);
        Diagnostics.AssertText($"{call} exception type", nameof(ArgumentNullException), thrown.GetType().Name);
    }

    /// <summary>A cookie line of exactly <paramref name="length"/> characters named <paramref name="name"/>.</summary>
    private static string CookieLineOfLength(string name, int length)
    {
        string prefix = $"127.0.0.1\tFALSE\t/\tFALSE\t0\t{name}\t";
        return prefix + new string('u', length - prefix.Length);
    }
}
