namespace Curl.Cookies;

/// <summary>
/// Pins <see cref="NetscapeCookieFile"/> and <see cref="CookieStore"/>'s cookie-file members to curl 8.21.0
/// (<c>x86_64-w64-mingw32</c>, Schannel, libpsl), measured on 2026-09-26: curl loaded the file written here
/// with <c>-b</c> (or received the headers written here from <c>Record-CurlExchange.ps1</c>) and the
/// expected text is the <c>-c</c> jar it wrote, byte for byte; the Windows build ends jar lines with CR LF.
/// BL-221's Notes record each command.
/// </summary>
[TestClass]
public sealed class NetscapeCookieFileTests
{
    private const string Header =
        "# Netscape HTTP Cookie File\r\n# https://curl.se/docs/http-cookies.html\r\n# This file was generated by libcurl! Edit at your own risk.\r\n\r\n";

    private static readonly DateTimeOffset Now = DateTimeOffset.FromUnixTimeSeconds(1_790_460_351);

    /// <summary>
    /// Measured: <c>curl -c jar.txt http://localhost:18221/p/x</c>, the response setting <c>a=1; Path=/</c>,
    /// <c>h=2; HttpOnly; Path=/p</c>, <c>d=3; Domain=localhost; Max-Age=3600</c>, <c>s=4; Secure; HttpOnly</c>
    /// and <c>q="x y"</c>. Newest first, <c>#HttpOnly_</c> before the domain, a dot before a domain cookie's.
    /// </summary>
    [TestMethod]
    public void WriteCookieJar_ReceivedCookies_MatchesCurlsJarByteForByte()
    {
        DateTimeOffset received = DateTimeOffset.FromUnixTimeSeconds(1_790_463_538);
        CookieStore store = new();
        store.StoreFromResponse(
            new Uri("http://localhost:18221/p/x"),
            ["a=1; Path=/", "h=2; HttpOnly; Path=/p", "d=3; Domain=localhost; Max-Age=3600", "s=4; Secure; HttpOnly", "q=\"x y\""],
            received);

        Assert.AreEqual(
            Header
            + "localhost\tFALSE\t/p\tFALSE\t0\tq\t\"x y\"\r\n"
            + "#HttpOnly_localhost\tFALSE\t/p\tTRUE\t0\ts\t4\r\n"
            + ".localhost\tTRUE\t/p\tFALSE\t1790467138\td\t3\r\n"
            + "#HttpOnly_localhost\tFALSE\t/p\tFALSE\t0\th\t2\r\n"
            + "localhost\tFALSE\t/\tFALSE\t0\ta\t1\r\n",
            WriteJar(store, received));
    }

    /// <summary>Measured: <c>curl -c empty.txt</c> against a response with no cookie writes the 135-byte header alone.</summary>
    [TestMethod]
    public void WriteCookieJar_NoCookies_WritesTheHeaderAlone()
    {
        string jar = WriteJar(new CookieStore(), Now);

        Assert.AreEqual(Header, jar);
        Assert.AreEqual(135, jar.Length);
    }

    /// <summary>
    /// Measured: <c>curl -b in.txt -c out.txt http://127.0.0.1:18221/</c>. Comments and blank, malformed,
    /// eight-field and bad-expiry lines are skipped; six fields mean an empty value; <c>true</c> counts as
    /// <c>TRUE</c>; the file's last line is the jar's first.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_MixedLines_KeepsWhatCurlKeeps()
    {
        CookieStore store = Load(InTxt, discardSessionCookies: false);

        Assert.AreEqual(
            Header
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tlower\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tempty\t\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tnoval\t\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsp ace\tv v\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tdom\t2\r\n"
            + "#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t0\tho\t1\r\n",
            WriteJar(store, Now));
    }

    /// <summary>Measured: the same file with <c>-j</c> keeps only the cookie with an expiry.</summary>
    [TestMethod]
    public void LoadCookieFile_DiscardSessionCookies_KeepsOnlyCookiesWithAnExpiry()
    {
        CookieStore store = Load(InTxt, discardSessionCookies: true);

        Assert.AreEqual(Header + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\r\n", WriteJar(store, Now));
    }

    /// <summary>
    /// Measured: <c>curl -b in2.txt -c out2.txt http://127.0.0.1:18221/p/x</c>. Domain dots and flags are
    /// normalised; a path field that starts <c>TRUE</c> is the secure field; expired, signed, too-large and
    /// bad-prefix lines are dropped; an empty name or domain, and a domain with spaces, are kept.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_FieldEdgeCases_NormalisesAsCurlDoes()
    {
        const string File =
            "127.0.0.1\tTRUE\t/\tFALSE\t0\tA1\t1\n"
            + ".127.0.0.1\tFALSE\t/\tFALSE\t0\tA2\t2\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t5\tA3\t3\n"
            + "127.0.0.1\tFALSE\t/\tT\t0\tA4\t4\n"
            + "127.0.0.1\tFALSE\t/\tyes\t0\tA5\t5\n"
            + "127.0.0.1\tFALSE\tTRUE\t0\tA6\t6\n"
            + "127.0.0.1\tFALSE\tnoslash\tFALSE\t0\tA7\t7\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t__Secure-A8\t8\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\t__Host-A9\t9\n"
            + "127.0.0.1\tFALSE\t/p\tTRUE\t0\t__Host-A10\t10\n"
            + "127.0.0.1\tTRUE\t/\tTRUE\t0\t__Host-A11\t11\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t-5\tA12\t12\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t+7\tA13\t13\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t\t14\n"
            + "\tFALSE\t/\tFALSE\t0\tA15\t15\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA16\t1\t6\n"
            + "127.0.0.1\tTRU\t/\tFALSE\t0\tA17\t17\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA18\t1 8 \n"
            + "  127.0.0.1\tFALSE\t/\tFALSE\t0\tA19\t19\n"
            + "127.0.0.1\tFALSE\t/p/\tFALSE\t0\tA20\t20\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t99999999999999999999\tA21\t21\n";

        CookieStore store = Load(File, discardSessionCookies: false);

        Assert.AreEqual(
            Header
            + "127.0.0.1\tFALSE\t/p\tFALSE\t0\tA20\t20\r\n"
            + "  127.0.0.1\tFALSE\t/\tFALSE\t0\tA19\t19\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA18\t1 8 \r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tA17\t17\r\n"
            + "\tFALSE\t/\tFALSE\t0\tA15\t15\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\t\t14\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\t__Host-A9\t9\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA7\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tA6\t6\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA5\t5\r\n"
            + "127.0.0.1\tFALSE\t/\tTRUE\t0\tA4\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tA2\t2\r\n"
            + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tA1\t1\r\n",
            WriteJar(store, Now));
        Assert.AreEqual(
            "A20=20; __Host-A9=9; A18=1 8 ; A17=17; A7=7; A6=6; A5=5; A4=4; A2=2; A1=1; =14",
            store.GetCookieHeader(new Uri("http://127.0.0.1:18221/p/x"), secure: false, Now));
    }

    /// <summary>
    /// Measured: <c>curl -b td.txt -c -</c>. A path field that is the start of <c>TRUE</c> or <c>FALSE</c>
    /// (empty included), in that case, becomes the secure field; the start of <c>TRUE</c> in any case, an
    /// empty field included, is true.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_BooleanWords_ReadAsCurlReadsThem()
    {
        const string File =
            "h\tFALSE\tT\t0\tD1\t1\n"
            + "h\tFALSE\t\t0\tD2\t2\n"
            + "h\tFALSE\tFALS\t0\tD3\t3\n"
            + "h\tFALSE\ttrue\t0\tD4\t4\n"
            + "h\tFALSE\tTRUEX\tTRUE\t0\tD5\t5\n"
            + "h\tFALSE\tTRUE\t0\tD6\n"
            + "h\tFALSE\t/\t\t0\tD7\t7\n"
            + "h\t\t/\tFALSE\t0\tD8\t8\n"
            + "h\tFALSE\t/\tFALSE\t0\tD9\t9\t\n"
            + "h\tFALSE\t/\tFALSE\t0\tD10\n"
            + "h\tFALSE\t/\tFALSE\t0\n";

        Assert.AreEqual(
            Header
            + "h\tFALSE\t/\tFALSE\t0\tD10\t\r\n"
            + ".h\tTRUE\t/\tFALSE\t0\tD8\t8\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD7\t7\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD6\t\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD5\t5\r\n"
            + "h\tFALSE\t/\tFALSE\t0\tD3\t3\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD2\t2\r\n"
            + "h\tFALSE\t/\tTRUE\t0\tD1\t1\r\n",
            WriteJar(Load(File, discardSessionCookies: false), Now));
    }

    /// <summary>
    /// Measured: <c>curl -b in4.txt -c out4.txt</c> and <c>curl -b tcc.txt -c -</c>. Quotes stay on a value
    /// and come off a path; a carriage return ends the line; a control character refuses the name or value
    /// but not the domain or path; <c>#httponly_</c> is a comment; bytes above 127 pass through.
    /// </summary>
    [TestMethod]
    public void LoadCookieFile_CharacterEdgeCases_ReadAsCurlReadsThem()
    {
        const string File =
            "127.0.0.1\tFALSE\t/\tFALSE\t0\tB5\t\"q\"\n"
            + "127.0.0.1\tFALSE\t\"/p\"\tFALSE\t0\tB6\t6\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB7\t7\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB9\ta\u0001b\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t00\tB10\t10\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800abc\tB1\t1\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t\tB3\t3\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t9223372036854775807\tB4\t4\n"
            + "#httponly_127.0.0.1\tFALSE\t/\tFALSE\t0\tC1\t1\n"
            + "127.0.0.1\u0001\tFALSE\t/\tFALSE\t0\tC2\t2\n"
            + "127.0.0.1\tFALSE\t/\u0001\tFALSE\t0\tC3\t3\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC4\ta\u007Fb\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC\u00025\t5\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC6\ta\rb\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC8\taÃ©b\n"
            + "#HttpOnly_\tFALSE\t/\tFALSE\t0\tC9\t9\n"
            + "..h\tTRUE\t/\tFALSE\t0\tE1\t1\n"
            + "..g\tFALSE\t/\tFALSE\t0\tE2\t2\n";

        Assert.AreEqual(
            Header
            + ".g\tFALSE\t/\tFALSE\t0\tE2\t2\r\n"
            + ".h\tTRUE\t/\tFALSE\t0\tE1\t1\r\n"
            + "#HttpOnly_\tFALSE\t/\tFALSE\t0\tC9\t9\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC8\taÃ©b\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tC6\ta\r\n"
            + "127.0.0.1\tFALSE\t/\u0001\tFALSE\t0\tC3\t3\r\n"
            + "127.0.0.1\u0001\tFALSE\t/\tFALSE\t0\tC2\t2\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t9223372036854775807\tB4\t4\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tB1\t1\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB10\t10\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB7\t7\r\n"
            + "127.0.0.1\tFALSE\t/p\tFALSE\t0\tB6\t6\r\n"
            + "127.0.0.1\tFALSE\t/\tFALSE\t0\tB5\t\"q\"\r\n",
            WriteJar(Load(File, discardSessionCookies: false), Now));
    }

    /// <summary>Measured: <c>curl -b te.txt -c -</c>. A later namesake (domain in any case) replaces an earlier one in its place.</summary>
    [TestMethod]
    public void LoadCookieFile_Namesakes_ReplaceInPlace()
    {
        const string File =
            "h\tFALSE\t/\tFALSE\t0\tX\t1\n"
            + "h\tFALSE\t/\tFALSE\t0\tY\t1\n"
            + "H\tFALSE\t/\tFALSE\t0\tX\t2\n"
            + "h\tTRUE\t/\tFALSE\t0\tX\t3\n";

        Assert.AreEqual(
            Header + ".h\tTRUE\t/\tFALSE\t0\tX\t3\r\nh\tFALSE\t/\tFALSE\t0\tY\t1\r\nH\tFALSE\t/\tFALSE\t0\tX\t2\r\n",
            WriteJar(Load(File, discardSessionCookies: false), Now));
    }

    /// <summary>
    /// Measured: a cookie line followed by <c>after</c>, loaded with <c>-b</c>. A line of up to 4998
    /// characters before its line feed, a carriage return counted, is read; a longer one ends the reading,
    /// so neither it nor anything after it is loaded. A last line without a line feed has the same limit.
    /// </summary>
    [TestMethod]
    [DataRow(4998, "\n", "after len")]
    [DataRow(4999, "\n", "")]
    [DataRow(4998, "\r\n", "after len")]
    [DataRow(4999, "\r\n", "")]
    public void Read_LongLine_StopsReadingPastTheLimit(int lengthBeforeLineFeed, string lineEnd, string expectedNames)
    {
        string line = CookieLineOfLength("len", lengthBeforeLineFeed - (lineEnd.Length - 1)) + lineEnd;
        string file = line + "127.0.0.1\tFALSE\t/\tFALSE\t0\tafter\t1" + lineEnd;

        IReadOnlyList<Cookie> cookies = NetscapeCookieFile.Read(new StringReader(file));

        Assert.AreEqual(expectedNames, string.Join(' ', cookies.Reverse().Select(cookie => cookie.Name)));
    }

    /// <summary>Measured: a last line with no line feed, after <c>before</c>, loads at 4998 characters and not at 4999.</summary>
    [TestMethod]
    [DataRow(4998, "len before")]
    [DataRow(4999, "before")]
    public void Read_LastLineWithoutLineFeed_HasTheSameLimit(int length, string expectedNames)
    {
        string file = "127.0.0.1\tFALSE\t/\tFALSE\t0\tbefore\t1\n" + CookieLineOfLength("len", length);

        IReadOnlyList<Cookie> cookies = NetscapeCookieFile.Read(new StringReader(file));

        Assert.AreEqual(expectedNames, string.Join(' ', cookies.Reverse().Select(cookie => cookie.Name)));
    }

    [TestMethod]
    public void Read_EmptyText_ReadsNothing()
    {
        Assert.IsEmpty(NetscapeCookieFile.Read(new StringReader(string.Empty)));
    }

    [TestMethod]
    public void ParseLine_HttpOnlyLine_ReadsEveryField()
    {
        Assert.AreEqual(
            new Cookie("n", "v", "example.test", true, "/p", true, true, 1234),
            NetscapeCookieFile.ParseLine("#HttpOnly_.example.test\tTRUE\t/p\tTRUE\t1234\tn\tv"));
    }

    [TestMethod]
    public void ParseLine_TooFewFieldsForAMadeUpPath_IsRefused()
    {
        Assert.IsNull(NetscapeCookieFile.ParseLine("h\tFALSE"));
    }

    [TestMethod]
    public void Write_CookiesInTheGivenOrder_UsesTheWritersLineEnding()
    {
        StringWriter writer = new() { NewLine = "\n" };

        NetscapeCookieFile.Write(writer, [new Cookie("a", "1", "h", false, "/", false, false, 0)]);

        Assert.AreEqual(Header.Replace("\r\n", "\n", StringComparison.Ordinal) + "h\tFALSE\t/\tFALSE\t0\ta\t1\n", writer.ToString());
    }

    [TestMethod]
    public void NullArguments_Throw()
    {
        Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Read(null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.ParseLine(null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Write(null!, []));
        Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.Write(new StringWriter(), null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => NetscapeCookieFile.FormatLine(null!));
    }

    /// <summary>The measured <c>in.txt</c>.</summary>
    private const string InTxt =
        "# comment\n\n"
        + "#HttpOnly_127.0.0.1\tFALSE\t/\tFALSE\t0\tho\t1\n"
        + ".127.0.0.1\tTRUE\t/\tFALSE\t0\tdom\t2\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tpersist\t3\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\t4\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tsp ace\tv v\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tnoval\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tempty\t\n"
        + "bad line\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\tabc\tnum\t5\n"
        + "127.0.0.1\tFALSE\t/\tFALSE\t0\tseven\t6\textra\n"
        + "127.0.0.1\tfalse\t/\ttrue\t0\tlower\t7\n";

    private static CookieStore Load(string file, bool discardSessionCookies)
    {
        CookieStore store = new();
        store.LoadCookieFile(new StringReader(file), discardSessionCookies, Now);
        return store;
    }

    private static string WriteJar(CookieStore store, DateTimeOffset now)
    {
        StringWriter writer = new() { NewLine = "\r\n" };
        store.WriteCookieJar(writer, now);
        return writer.ToString();
    }

    /// <summary>A cookie line of exactly <paramref name="length"/> characters named <paramref name="name"/>.</summary>
    private static string CookieLineOfLength(string name, int length)
    {
        string prefix = $"127.0.0.1\tFALSE\t/\tFALSE\t0\t{name}\t";
        return prefix + new string('u', length - prefix.Length);
    }
}
