using Curl.Core.Fakes;
using Curl.Protocol.Abstractions;

namespace Curl.Core.Hsts;

/// <summary>
/// Pins <see cref="HstsTransferPolicy" />: which URLs it switches to <c>https</c> and how, and which
/// responses it learns from, as curl 8.21.0 does (measured 2026-09-29, BL-621 Notes).
/// </summary>
[TestClass]
public sealed class HstsTransferPolicyTests
{
    private static readonly DateTimeOffset Now = new(2026, 9, 29, 14, 22, 10, TimeSpan.Zero);

    private readonly HstsTransferPolicy policy = new(new FakeTimeProvider(Now));

    [TestMethod]
    [DataRow("http://localhost:18443/p?q", "https://localhost:18443/p?q")]
    [DataRow("HTTP://LocalHost.:80/a", "https://LocalHost.:80/a")]
    [DataRow("http://www.localhost/", "https://www.localhost/")]
    public void TrySwitchToHttps_KnownHost_ReplacesTheSchemeOnly(string url, string expected)
    {
        policy.ReadFile(".localhost \"unlimited\"\n");

        Assert.IsTrue(policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl));
        Assert.AreEqual(expected, httpsUrl);
    }

    [TestMethod]
    [DataRow("http://example.com/")]
    [DataRow("https://localhost/")]
    [DataRow("ftp://localhost/")]
    public void TrySwitchToHttps_UnknownHostOrNotHttp_LeavesTheUrl(string url)
    {
        policy.ReadFile(".localhost \"unlimited\"\n");

        Assert.IsFalse(policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl));
        Assert.IsNull(httpsUrl);
    }

    [TestMethod]
    public void LearnFrom_HttpsResponse_LearnsEveryStrictTransportSecurityHeaderInOrder()
    {
        policy.LearnFrom(CurlUrl.Parse("https://localhost:18443/"), Report(
            new("strict-transport-security", "max-age=60"),
            new("Content-Length", "0"),
            new("Strict-Transport-Security", "max-age=120; includeSubDomains")));

        Assert.AreEqual(
            "# Your HSTS cache. https://curl.se/docs/hsts.html\n# This file was generated by libcurl! Edit at your own risk.\n"
            + ".localhost \"20260929 14:24:10\"\n",
            policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    public void LearnFrom_HttpResponseOrNoReport_LearnsNothing()
    {
        policy.LearnFrom(CurlUrl.Parse("http://localhost/"), Report(StrictTransportSecurity("max-age=60")));
        policy.LearnFrom(CurlUrl.Parse("https://localhost/"), null);

        Assert.IsFalse(policy.TrySwitchToHttps("http://localhost/", CurlUrl.Parse("http://localhost/"), out _));
    }

    [TestMethod]
    public void LearnFrom_Ipv6Host_IsRefusedAsAnIpAddress()
    {
        policy.LearnFrom(CurlUrl.Parse("https://[::1]/"), Report(StrictTransportSecurity("max-age=60")));

        Assert.IsFalse(policy.TrySwitchToHttps("http://[::1]/", CurlUrl.Parse("http://[::1]/"), out _));
        Assert.AreEqual(
            "# Your HSTS cache. https://curl.se/docs/hsts.html\n# This file was generated by libcurl! Edit at your own risk.\n",
            policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    public void Members_NullArguments_Throw()
    {
        CurlUrl url = CurlUrl.Parse("http://localhost/");

        Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps(null!, url, out _));
        Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps("http://localhost/", null!, out _));
        Assert.ThrowsExactly<ArgumentNullException>(() => policy.LearnFrom(null!, null));
    }

    private static TransferReport Report(params KeyValuePair<string, string>[] headers) =>
        new() { ResponseHeaders = headers };

    private static KeyValuePair<string, string> StrictTransportSecurity(string value) =>
        new("Strict-Transport-Security", value);
}
