using Curl.Core.Fakes;

namespace Curl.Core.Hsts;

/// <summary>
/// Pins <see cref="HstsCache" /> against the HSTS files curl 8.21.0 (mingw, Schannel) wrote on
/// 2026-09-29 UTC with <c>-k --hsts cache.txt https://localhost:18443/</c> against
/// <c>Record-CurlExchange.ps1 -Tls</c>, byte for byte; each test's clock is the second curl ran
/// at, read back from the expiries it wrote. The commands and files are in BL-620's notes.
/// </summary>
[TestClass]
public sealed class HstsCacheTests
{
    private const string Header =
        "# Your HSTS cache. https://curl.se/docs/hsts.html\r\n"
        + "# This file was generated by libcurl! Edit at your own risk.\r\n";

    private const long Windows = HstsCache.LatestWritableExpiryOnWindows;

    [TestMethod]
    public void FormatFile_AfterAYearWithSubdomains_WritesCurlsFile()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 5, 59, 2);

        cache.ApplyHeader("max-age=31536000; includeSubDomains", "localhost");

        Assert.AreEqual(Header + ".localhost \"20270929 05:59:02\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void FormatFile_WithLineFeed_EndsEveryLineInLineFeed()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 5, 59, 2);

        cache.ApplyHeader("max-age=31536000; includeSubDomains", "localhost");

        Assert.AreEqual(
            string.Join('\n', HstsCache.FileHeaderLines) + "\n.localhost \"20270929 05:59:02\"\n",
            cache.FormatFile("\n", HstsCache.LatestWritableExpiryOffWindows));
    }

    [TestMethod]
    public void ApplyHeader_MaxAgeZeroAfterReadingCurlsFile_LeavesOnlyTheComments()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(Header + ".localhost \"20270929 05:59:02\"\r\n");

        cache.ApplyHeader("max-age=0", "localhost");

        Assert.AreEqual(Header, cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void ReadFile_CurlsSeededFile_KeepsWhatCurlKept()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 1);
        cache.ReadFile(
            "# c\n   # indented\n\nplain.test \"unlimited\"\n.sub.test \"20300101 00:00:00\"\nold.test \"20200101 00:00:00\"\n"
            + "bad.test 20300101\ndup.test \"20300101 00:00:00\"\ndup.test \"20310101 00:00:00\"\nDUP.test \"20290101 00:00:00\"\n"
            + "trail.test. \"20300101 00:00:00\"\ngarbage.test \"not a date\"\n  lead.test \"20300101 00:00:00\"\n"
            + "two.test  \"20300101 00:00:00\"\ntab.test\t\"20300101 00:00:00\"\nx.test \"20300101 00:00:00\" y\n"
            + "cr.test \"20300101 00:00:00\"\r\nlocalhost \"20300101 00:00:00\"\nlast.test \"20300101 00:00:00\"");

        cache.ApplyHeader("max-age=60", "localhost");

        Assert.AreEqual(
            Header
            + "plain.test \"unlimited\"\r\n.sub.test \"20300101 00:00:00\"\r\ndup.test \"20310101 00:00:00\"\r\n"
            + "trail.test \"20300101 00:00:00\"\r\nlead.test \"20300101 00:00:00\"\r\ncr.test \"20300101 00:00:00\"\r\n"
            + "localhost \"20260929 06:01:01\"\r\nlast.test \"20300101 00:00:00\"\r\n",
            cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    [DataRow("max-age=99999999999999999999999; includeSubDomains", ".localhost")]
    [DataRow("max-age=9223372036854775807", "localhost")]
    public void ApplyHeader_MaxAgePastSixtyFourBits_WritesUnlimited(string headerValue, string written)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 2);
        cache.ReadFile("a.test \"20300101 00:00:00\"\n");

        cache.ApplyHeader(headerValue, "localhost");

        Assert.AreEqual(Header + "a.test \"20300101 00:00:00\"\r\n" + written + " \"unlimited\"\r\n", cache.FormatFile("\r\n", Windows));
        Assert.IsTrue(cache.Entries[1].IsUnlimited);
    }

    [TestMethod]
    public void FormatFile_ExpiryAtTheWindowsLimit_WritesIt()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("e \"30010101 20:59:59\"\n");

        Assert.AreEqual(Header + "e \"30010101 20:59:59\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void FormatFile_ExpiryPastTheWindowsLimit_WritesNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("e \"30010101 20:59:59\"\nf \"30010101 21:00:00\"\n");

        Assert.IsNull(cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void FormatFile_MaxAgePastTheWindowsLimit_WritesNothingOnWindowsAndTheYearElsewhere()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 25);

        cache.ApplyHeader("max-age=251611639175", "localhost");

        Assert.IsNull(cache.FormatFile("\r\n", Windows));
        Assert.AreEqual(
            string.Join('\n', HstsCache.FileHeaderLines) + "\nlocalhost \"100000101 00:00:00\"\n",
            cache.FormatFile("\n", HstsCache.LatestWritableExpiryOffWindows));
    }

    [TestMethod]
    public void FormatFile_ExpiryPastTheLastYearAnIntHolds_WritesNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        cache.ApplyHeader("max-age=" + (HstsCache.LatestWritableExpiryOffWindows + 1 - new DateTimeOffset(2026, 9, 29, 6, 0, 0, TimeSpan.Zero).ToUnixTimeSeconds()), "localhost");

        Assert.IsNull(cache.FormatFile("\n", HstsCache.LatestWritableExpiryOffWindows));
    }

    [TestMethod]
    public void Find_SubdomainOfAnIncludeSubDomainsEntry_FindsIt()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 27);
        cache.ReadFile(".localhost \"unlimited\"\n");

        Assert.AreEqual(new HstsEntry("localhost", true, HstsEntry.UnlimitedExpiry), cache.Find("www.localhost"));
    }

    [TestMethod]
    public void ApplyHeader_SubdomainOfAnIncludeSubDomainsEntry_AddsItsOwnEntry()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 27);
        cache.ReadFile(".localhost \"unlimited\"\n");

        cache.ApplyHeader("max-age=60", "www.localhost");

        Assert.AreEqual(Header + ".localhost \"unlimited\"\r\nwww.localhost \"20260929 06:01:27\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void Find_SubdomainOfAnEntryWithoutIncludeSubDomains_FindsNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 28);
        cache.ReadFile("localhost \"unlimited\"\n");

        Assert.IsNull(cache.Find("www.localhost"));
    }

    [TestMethod]
    public void Find_HostInAnotherCaseWithTrailingDot_FindsItsEntry()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 29);
        cache.ReadFile(".localhost \"unlimited\"\n");

        Assert.AreEqual("localhost", cache.Find("LOCALHOST.")?.Host);
    }

    [TestMethod]
    public void ApplyHeader_HostInAnotherCaseWithTrailingDot_UpdatesTheEntryInPlace()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 29);
        cache.ReadFile(".localhost \"unlimited\"\n");

        cache.ApplyHeader("max-age=60", "LOCALHOST.");

        Assert.AreEqual(Header + "localhost \"20260929 06:01:29\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void Find_ExpiredEntry_FindsNothingAndDropsIt()
    {
        FakeTimeProvider clock = new(new DateTimeOffset(2020, 1, 1, 0, 0, 0, TimeSpan.Zero));
        HstsCache cache = new(clock);
        cache.ReadFile("localhost \"20200101 00:00:01\"\nother \"unlimited\"\n");
        clock.Advance(TimeSpan.FromSeconds(1));

        Assert.IsNull(cache.Find("localhost"));
        Assert.AreEqual(Header + "other \"unlimited\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void FormatFile_ExpiredEntryNoLookupPassed_StillWritesIt()
    {
        FakeTimeProvider clock = new(new DateTimeOffset(2020, 1, 1, 0, 0, 0, TimeSpan.Zero));
        HstsCache cache = new(clock);
        cache.ReadFile("localhost \"20200101 00:00:01\"\n");
        clock.Advance(TimeSpan.FromSeconds(1));

        Assert.AreEqual(Header + "localhost \"20200101 00:00:01\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void ReadFile_ExpiredEntry_SkipsIt()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 30);
        cache.ReadFile("localhost \"20200101 00:00:00\"\n");

        Assert.IsNull(cache.Find("localhost"));
        Assert.AreEqual(Header, cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void ReadFile_SubdomainLineUnderAHeldParent_SkipsOnlyTheDottedOne()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 1, 6);
        cache.ReadFile(".sub.test \"20300101 00:00:00\"\n.a.sub.test \"20300101 00:00:00\"\nb.sub.test \"20300101 00:00:00\"\n");

        cache.ApplyHeader("max-age=0", "localhost");

        Assert.AreEqual(Header + ".sub.test \"20300101 00:00:00\"\r\nb.sub.test \"20300101 00:00:00\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    public void ReadFile_SameHostTwice_KeepsTheLaterExpiryAndAnyIncludeSubDomains()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("dup.test \"20310101 00:00:00\"\n.DUP.test \"20300101 00:00:00\"\n");

        Assert.AreEqual(new HstsEntry("dup.test", true, new DateTimeOffset(2031, 1, 1, 0, 0, 0, TimeSpan.Zero).ToUnixTimeSeconds()), cache.Entries.Single());
    }

    [TestMethod]
    [DataRow("20300230", "20300302 00:00:00")]
    [DataRow("20300101 23:59:60", "20300102 00:00:00")]
    [DataRow("20300101 00:00", "20300101 00:00:00")]
    [DataRow("20300101 0:0:0", "20300101 00:00:00")]
    [DataRow("20300101", "20300101 00:00:00")]
    public void ReadFile_DateCurlReads_WritesItAsCurlDid(string written, string rewritten)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("e \"" + written + "\"\n");

        Assert.AreEqual(Header + "e \"" + rewritten + "\"\r\n", cache.FormatFile("\r\n", Windows));
    }

    [TestMethod]
    [DataRow("UNLIMITED")]
    [DataRow("20301301")]
    [DataRow("20300101 24:00:00")]
    [DataRow("2030-01-01")]
    [DataRow("Tue, 01 Jan 2030 00:00:00 GMT")]
    [DataRow("20300101 00:00:00Z")]
    [DataRow("20300101 T00:00:00")]
    [DataRow("20300101  00:00:00")]
    [DataRow("2030010 00:00:00")]
    [DataRow("not a date")]
    public void ReadFile_DateCurlRefuses_DropsTheLine(string written)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("e \"" + written + "\"\n");

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    [DataRow(".\"unlimited\"")]
    [DataRow(". \"unlimited\"")]
    [DataRow(".. \"unlimited\"")]
    public void ReadFile_HostOfOnlyDots_AddsNothing(string line)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(line);

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    public void ReadFile_LineLongerThanCurlReads_EndsTheReading()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(
            "a \"unlimited\"\r\n# " + new string('x', HstsCache.MaxFileLineLength - 2) + "\r\nb \"unlimited\"\n#"
            + new string('x', HstsCache.MaxFileLineLength) + "\nc \"unlimited\"\n");

        CollectionAssert.AreEqual(new[] { "a", "b" }, cache.Entries.Select(entry => entry.Host).ToArray());
    }

    [TestMethod]
    [DataRow("127.0.0.1")]
    [DataRow("::1")]
    [DataRow("2001:db8::1")]
    [DataRow("0.0.0.0")]
    [DataRow("255.255.255.255")]
    public void ApplyHeader_FromAnIpAddress_LearnsNothing(string host)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        cache.ApplyHeader("max-age=60", host);

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    [DataRow("1.2.3")]
    [DataRow("1.2.3.4.5")]
    [DataRow("256.1.1.1")]
    [DataRow("01.1.1.1")]
    [DataRow("1..1.1")]
    [DataRow("1.2.3.4444")]
    [DataRow("a.b.c.d")]
    [DataRow("fe80::1%eth0")]
    [DataRow("[::1]")]
    [DataRow("a:b")]
    public void ApplyHeader_FromANameThatIsNoAddress_LearnsIt(string host)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        cache.ApplyHeader("max-age=60", host);

        Assert.AreEqual(host, cache.Entries.Single().Host);
    }

    [TestMethod]
    [DataRow("")]
    [DataRow(".")]
    public void ApplyHeader_EmptyHost_LearnsNothing(string host)
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        cache.ApplyHeader("max-age=60", host);

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    public void ApplyHeader_RefusedValue_LearnsNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        cache.ApplyHeader("includeSubDomains", "localhost");

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    public void ApplyHeader_MaxAgeZeroForAnUnknownHost_ChangesNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(".localhost \"unlimited\"\n");

        cache.ApplyHeader("max-age=0", "www.localhost");

        Assert.AreEqual(1, cache.Entries.Count);
    }

    [TestMethod]
    public void ApplyHeader_HostLongerThanCurlLooksUp_AddsItAgainEachTime()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        string host = new('a', HstsFileLineParser.MaxHostLength + 1);

        cache.ApplyHeader("max-age=60", host);
        cache.ApplyHeader("max-age=60", host);

        Assert.AreEqual(2, cache.Entries.Count);
        Assert.IsNull(cache.Find(host));
    }

    [TestMethod]
    public void Find_SeveralParents_TakesTheLongestAndAnExactMatchOverAll()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(".b.test \"20300101 00:00:00\"\n.c.test \"unlimited\"\nx.b.test \"20310101 00:00:00\"\n.test \"unlimited\"\n");

        Assert.AreEqual("b.test", cache.Find("y.x.b.test")?.Host);
        Assert.AreEqual("x.b.test", cache.Find("X.B.TEST")?.Host);
        Assert.AreEqual("test", cache.Find("q.test")?.Host);
        Assert.IsNull(cache.Find("xb.test.org"));
        Assert.IsNull(cache.Find("atest"));
    }

    [TestMethod]
    public void Find_EmptyHost_FindsNothing()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile("a \"unlimited\"\n");

        Assert.IsNull(cache.Find(string.Empty));
    }

    [TestMethod]
    public void ApplyHeader_PastMaxEntries_DropsTheFirst()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);
        cache.ReadFile(string.Concat(Enumerable.Range(0, HstsCache.MaxEntries).Select(number => $"h{number} \"unlimited\"\n")));

        cache.ApplyHeader("max-age=60", "new");

        Assert.AreEqual(HstsCache.MaxEntries, cache.Entries.Count);
        Assert.AreEqual("h1", cache.Entries[0].Host);
        Assert.AreEqual("new", cache.Entries[^1].Host);
    }

    [TestMethod]
    public void Members_NullArguments_Throw()
    {
        HstsCache cache = CacheAt(2026, 9, 29, 6, 0, 0);

        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ReadFile(null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ApplyHeader(null!, "a"));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ApplyHeader("max-age=1", null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.Find(null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.FormatFile(null!, Windows));
    }

    private static HstsCache CacheAt(int year, int month, int day, int hour, int minute, int second) =>
        new(new FakeTimeProvider(new DateTimeOffset(year, month, day, hour, minute, second, TimeSpan.Zero)));
}
