using Curl.Core.Fakes;
using Curl.Protocol.Abstractions;
using Curl.Testing;

namespace Curl.Core.Hsts;

/// <summary>
/// Pins <see cref="HstsTransferPolicy" />: which URLs it switches to <c>https</c> and how, and which
/// headers it learns, as curl 8.21.0 does (measured 2026-09-29, BL-621 Notes).
/// </summary>
[TestClass]
public sealed class HstsTransferPolicyTests
{
    private static readonly DateTimeOffset Now = new(2026, 9, 29, 14, 22, 10, TimeSpan.Zero);

    private const string EmptyFile =
        "# Your HSTS cache. https://curl.se/docs/hsts.html\n# This file was generated by libcurl! Edit at your own risk.\n";

    private readonly HstsTransferPolicy policy = new(new FakeTimeProvider(Now));

    public TestContext TestContext { get; set; } = null!;

    [TestMethod]
    [DataRow("http://localhost:18443/p?q", "https://localhost:18443/p?q")]
    [DataRow("HTTP://LocalHost.:80/a", "https://LocalHost.:80/a")]
    [DataRow("http://www.localhost/", "https://www.localhost/")]
    public void TrySwitchToHttps_KnownHost_ReplacesTheSchemeOnly(string url, string expected)
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        policy.ReadFile(".localhost \"unlimited\"\n");
        diagnostics.Arrange("url", url);

        bool switched = policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl);

        diagnostics.Act("switched", switched);
        diagnostics.Act("https url", httpsUrl);
        diagnostics.Assert("switched", true, switched);
        Assert.IsTrue(switched);
        diagnostics.Assert("https url", expected, httpsUrl);
        Assert.AreEqual(expected, httpsUrl);
    }

    [TestMethod]
    [DataRow("http://example.com/")]
    [DataRow("https://localhost/")]
    [DataRow("ftp://localhost/")]
    public void TrySwitchToHttps_UnknownHostOrNotHttp_LeavesTheUrl(string url)
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        policy.ReadFile(".localhost \"unlimited\"\n");
        diagnostics.Arrange("url", url);

        bool switched = policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl);

        diagnostics.Act("switched", switched);
        diagnostics.Act("https url", httpsUrl);
        diagnostics.Assert("switched", false, switched);
        Assert.IsFalse(switched);
        diagnostics.Assert("https url", "null", httpsUrl ?? "null");
        Assert.IsNull(httpsUrl);
    }

    [TestMethod]
    public void StoreFromResponse_IllegalHeaderOnANameHost_ReturnsFalseAndStoresNothing()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("header", "max-age=abc from https://localhost/");

        bool stored = policy.StoreFromResponse(CurlUrl.Parse("https://localhost/"), "max-age=abc", Now);

        diagnostics.Act("stored", stored);
        diagnostics.Assert("stored", false, stored);
        Assert.IsFalse(stored);

        string? file = policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows);
        diagnostics.Act("file", file);
        diagnostics.Assert("file", EmptyFile, file);
        Assert.AreEqual(EmptyFile, file);
    }

    [TestMethod]
    [DataRow("https://127.0.0.1/")]
    [DataRow("https://[::1]/")]
    public void StoreFromResponse_IllegalHeaderOnAnIpAddressHost_ReturnsTrueAndStoresNothing(string url)
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("header", "max-age=abc from " + url);

        bool stored = policy.StoreFromResponse(CurlUrl.Parse(url), "max-age=abc", Now);

        diagnostics.Act("stored", stored);
        diagnostics.Assert("stored", true, stored);
        Assert.IsTrue(stored);

        string? file = policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows);
        diagnostics.Act("file", file);
        diagnostics.Assert("file", EmptyFile, file);
        Assert.AreEqual(EmptyFile, file);
    }

    [TestMethod]
    public void StoreFromResponse_HttpOrigin_ReturnsTrueAndStoresNothing()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("header", "max-age=60 from http://localhost/");

        bool stored = policy.StoreFromResponse(CurlUrl.Parse("http://localhost/"), "max-age=60", Now);

        diagnostics.Act("stored", stored);
        diagnostics.Assert("stored", true, stored);
        Assert.IsTrue(stored);

        string? file = policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows);
        diagnostics.Act("file", file);
        diagnostics.Assert("file", EmptyFile, file);
        Assert.AreEqual(EmptyFile, file);
    }

    [TestMethod]
    public void StoreFromResponse_LegalHeader_ReturnsTrueAndStoresTheHostFromTheGivenTime()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        IHstsStore store = policy;
        DateTimeOffset received = Now.AddHours(1);
        diagnostics.Arrange("header", "max-age=60 from https://localhost/");
        diagnostics.Arrange("received at", received);

        bool stored = store.StoreFromResponse(CurlUrl.Parse("https://localhost/"), "max-age=60", received);

        diagnostics.Act("stored", stored);
        diagnostics.Assert("stored", true, stored);
        Assert.IsTrue(stored);

        string? file = policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows);
        diagnostics.Act("file", file);
        diagnostics.Assert("file", EmptyFile + "localhost \"20260929 15:23:10\"\n", file);
        Assert.AreEqual(EmptyFile + "localhost \"20260929 15:23:10\"\n", file);
    }

    [TestMethod]
    public void StoreFromResponse_NullArguments_Throw()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("arguments", "null url, then null header");

        var urlException = Assert.ThrowsExactly<ArgumentNullException>(() => policy.StoreFromResponse(null!, "max-age=60", Now));
        var headerException = Assert.ThrowsExactly<ArgumentNullException>(() => policy.StoreFromResponse(CurlUrl.Parse("https://localhost/"), null!, Now));

        diagnostics.Act("url exception", urlException.GetType().Name);
        diagnostics.Act("header exception", headerException.GetType().Name);
        diagnostics.Assert("url exception type", nameof(ArgumentNullException), urlException.GetType().Name);
        diagnostics.Assert("header exception type", nameof(ArgumentNullException), headerException.GetType().Name);
    }

    [TestMethod]
    public void Members_NullArguments_Throw()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        CurlUrl url = CurlUrl.Parse("http://localhost/");
        diagnostics.Arrange("arguments", "null url text, then null parsed url");

        var textException = Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps(null!, url, out _));
        var urlException = Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps("http://localhost/", null!, out _));

        diagnostics.Act("text exception", textException.GetType().Name);
        diagnostics.Act("url exception", urlException.GetType().Name);
        diagnostics.Assert("text exception type", nameof(ArgumentNullException), textException.GetType().Name);
        diagnostics.Assert("url exception type", nameof(ArgumentNullException), urlException.GetType().Name);
    }
}
