using Curl.Core.Fakes;
using Curl.Protocol.Abstractions;

namespace Curl.Core.Hsts;

/// <summary>
/// Pins <see cref="HstsTransferPolicy" />: which URLs it switches to <c>https</c> and how, and which
/// headers it learns, as curl 8.21.0 does (measured 2026-09-29, BL-621 Notes).
/// </summary>
[TestClass]
public sealed class HstsTransferPolicyTests
{
    private static readonly DateTimeOffset Now = new(2026, 9, 29, 14, 22, 10, TimeSpan.Zero);

    private const string EmptyFile =
        "# Your HSTS cache. https://curl.se/docs/hsts.html\n# This file was generated by libcurl! Edit at your own risk.\n";

    private readonly HstsTransferPolicy policy = new(new FakeTimeProvider(Now));

    [TestMethod]
    [DataRow("http://localhost:18443/p?q", "https://localhost:18443/p?q")]
    [DataRow("HTTP://LocalHost.:80/a", "https://LocalHost.:80/a")]
    [DataRow("http://www.localhost/", "https://www.localhost/")]
    public void TrySwitchToHttps_KnownHost_ReplacesTheSchemeOnly(string url, string expected)
    {
        policy.ReadFile(".localhost \"unlimited\"\n");

        Assert.IsTrue(policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl));
        Assert.AreEqual(expected, httpsUrl);
    }

    [TestMethod]
    [DataRow("http://example.com/")]
    [DataRow("https://localhost/")]
    [DataRow("ftp://localhost/")]
    public void TrySwitchToHttps_UnknownHostOrNotHttp_LeavesTheUrl(string url)
    {
        policy.ReadFile(".localhost \"unlimited\"\n");

        Assert.IsFalse(policy.TrySwitchToHttps(url, CurlUrl.Parse(url), out string? httpsUrl));
        Assert.IsNull(httpsUrl);
    }

    [TestMethod]
    public void StoreFromResponse_IllegalHeaderOnANameHost_ReturnsFalseAndStoresNothing()
    {
        Assert.IsFalse(policy.StoreFromResponse(CurlUrl.Parse("https://localhost/"), "max-age=abc", Now));

        Assert.AreEqual(EmptyFile, policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    [DataRow("https://127.0.0.1/")]
    [DataRow("https://[::1]/")]
    public void StoreFromResponse_IllegalHeaderOnAnIpAddressHost_ReturnsTrueAndStoresNothing(string url)
    {
        Assert.IsTrue(policy.StoreFromResponse(CurlUrl.Parse(url), "max-age=abc", Now));

        Assert.AreEqual(EmptyFile, policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    public void StoreFromResponse_HttpOrigin_ReturnsTrueAndStoresNothing()
    {
        Assert.IsTrue(policy.StoreFromResponse(CurlUrl.Parse("http://localhost/"), "max-age=60", Now));

        Assert.AreEqual(EmptyFile, policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    public void StoreFromResponse_LegalHeader_ReturnsTrueAndStoresTheHostFromTheGivenTime()
    {
        IHstsStore store = policy;

        Assert.IsTrue(store.StoreFromResponse(CurlUrl.Parse("https://localhost/"), "max-age=60", Now.AddHours(1)));

        Assert.AreEqual(
            EmptyFile + "localhost \"20260929 15:23:10\"\n",
            policy.FormatFile("\n", HstsCache.LatestWritableExpiryOnWindows));
    }

    [TestMethod]
    public void StoreFromResponse_NullArguments_Throw()
    {
        Assert.ThrowsExactly<ArgumentNullException>(() => policy.StoreFromResponse(null!, "max-age=60", Now));
        Assert.ThrowsExactly<ArgumentNullException>(() => policy.StoreFromResponse(CurlUrl.Parse("https://localhost/"), null!, Now));
    }

    [TestMethod]
    public void Members_NullArguments_Throw()
    {
        CurlUrl url = CurlUrl.Parse("http://localhost/");

        Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps(null!, url, out _));
        Assert.ThrowsExactly<ArgumentNullException>(() => policy.TrySwitchToHttps("http://localhost/", null!, out _));
    }
}
