using System.Globalization;
using System.Net;
using System.Net.Sockets;
using System.Text;
using Curl.Protocol.Abstractions;

namespace Curl.Core.Hsts;

/// <summary>
/// The HSTS cache behind <c>--hsts</c>: reads curl 8.21.0's HSTS file, learns from
/// <c>Strict-Transport-Security</c> headers, answers whether a host is known, and writes the
/// file back byte for byte as curl does, measured on 2026-09-29 UTC (BL-620's notes, ADR-0179).
/// </summary>
/// <remarks>
/// Entries keep the order they were read or learned in. An entry expires once the current
/// second of the injected <see cref="TimeProvider" /> reaches its expiry: it is skipped when
/// read, and removed by every lookup that passes it - <see cref="Find" />, and the lookups
/// <see cref="ReadFile" /> and <see cref="ApplyHeader" /> make - but an entry still held is
/// written back whether or not it has expired, as curl does. Host names compare ignoring ASCII
/// case and one trailing dot.
/// </remarks>
/// <param name="timeProvider">The clock expiries are counted on.</param>
/// <param name="diagnosticLog">
/// Where the cache writes its entries' lives, component <see cref="DiagnosticLogComponents.Hsts" />
/// (BL-1072): each entry stored from a header and each expired entry a lookup removes, as
/// <c>verbose</c>, by host name only; <see langword="null" /> for none.
/// </param>
public sealed class HstsCache(TimeProvider timeProvider, IDiagnosticLog? diagnosticLog = null)
{
    private readonly IDiagnosticLog log = diagnosticLog ?? NoDiagnosticLog.Instance;

    /// <summary>The two comment lines curl writes at the top of the file, without line endings.</summary>
    public static readonly IReadOnlyList<string> FileHeaderLines =
    [
        "# Your HSTS cache. https://curl.se/docs/hsts.html",
        "# This file was generated by libcurl! Edit at your own risk.",
    ];

    /// <summary>
    /// The longest file line curl reads, without its line ending: 4093 characters (libcurl's
    /// <c>MAX_HSTS_LINE</c> of 4095 bytes holds the LF and a terminator too).
    /// </summary>
    public const int MaxFileLineLength = 4093;

    /// <summary>
    /// The most entries curl holds: libcurl's <c>MAX_HSTS_ENTRIES</c>. Adding one more drops the
    /// first.
    /// </summary>
    public const int MaxEntries = 10_000;

    /// <summary>
    /// The latest expiry curl's Windows build writes, 3001-01-01 20:59:59 UTC, measured: its
    /// <c>gmtime</c> refuses a later one, and curl then leaves the file as it was.
    /// </summary>
    public const long LatestWritableExpiryOnWindows = 32_535_291_599;

    /// <summary>
    /// The latest expiry curl's Linux and macOS builds write, 31 December of year 2147485547
    /// 23:59:59 UTC: the last second whose year fits <c>struct tm</c>'s <c>int</c>, past which
    /// their <c>gmtime</c> fails.
    /// </summary>
    public const long LatestWritableExpiryOffWindows = 67_768_036_191_676_799;

    private const string UnlimitedText = "unlimited";

    private readonly List<HstsEntry> entries = [];

    /// <summary>Gets the entries held, in order.</summary>
    public IReadOnlyList<HstsEntry> Entries => entries;

    /// <summary>
    /// Adds the entries of an HSTS file's text, as libcurl 8.21.0's <c>hsts_load</c> does. Each
    /// line <see cref="HstsFileLineParser" /> reads is an entry expiring at its date, read by
    /// <see cref="CurlDateParser" />, or never for <c>unlimited</c>; an expired or unreadable
    /// date skips the line. A host already held (ignoring case) keeps its place and takes the
    /// later expiry, and a leading dot on either sets <c>includeSubDomains</c>; a subdomain of a
    /// host held with <c>includeSubDomains</c> is skipped when its own line has a leading dot.
    /// A line longer than <see cref="MaxFileLineLength" />, comment or not, ends the reading.
    /// </summary>
    /// <param name="fileText">The whole file, lines ending in LF or CR LF.</param>
    public void ReadFile(string fileText)
    {
        ArgumentNullException.ThrowIfNull(fileText);

        foreach (string line in fileText.Split('\n'))
        {
            string content = line.EndsWith('\r') ? line[..^1] : line;
            if (content.Length > MaxFileLineLength)
            {
                break;
            }

            HstsFileLine? fileLine = HstsFileLineParser.Parse(content);
            if (fileLine is not null)
            {
                AddFileEntry(fileLine);
            }
        }
    }

    /// <summary>
    /// Learns from one <c>Strict-Transport-Security</c> header received from a host, as libcurl
    /// 8.21.0's <c>Curl_hsts_parse</c> does: nothing from an IP address or from a value
    /// <see cref="HstsHeaderParser" /> refuses; <c>max-age=0</c> removes the host's own entry
    /// (never a parent's); otherwise the host's entry, if held, takes the new expiry and
    /// <c>includeSubDomains</c> in its place, and a new one is added last. The expiry is
    /// <c>max-age</c> seconds from now, or never when that is past 64 bits.
    /// </summary>
    /// <param name="headerValue">The header value, as received.</param>
    /// <param name="host">The host the response came from, an IPv6 address without brackets.</param>
    public void ApplyHeader(string headerValue, string host)
    {
        ArgumentNullException.ThrowIfNull(headerValue);
        ArgumentNullException.ThrowIfNull(host);

        HstsHeader? header = IsIpAddress(host) ? null : HstsHeaderParser.Parse(headerValue);
        if (header is null)
        {
            return;
        }

        int index = IndexOf(host, includingParents: false);
        if (header.MaxAgeSeconds == 0)
        {
            RemoveAt(index);
            return;
        }

        long now = NowSeconds();
        long expires = long.MaxValue - now < header.MaxAgeSeconds ? HstsEntry.UnlimitedExpiry : now + header.MaxAgeSeconds;
        if (index < 0)
        {
            Add(host, header.IncludeSubDomains, expires);
        }
        else
        {
            entries[index] = entries[index] with { IncludeSubDomains = header.IncludeSubDomains, ExpiresUnixSeconds = expires };
        }

        LogVerbose("stored entry for ", host, string.Empty);
    }

    /// <summary>
    /// Finds the policy for a host as libcurl 8.21.0's <c>Curl_hsts</c> does before a transfer:
    /// the host's own entry, else the entry with the longest name among those held with
    /// <c>includeSubDomains</c> that the host is a subdomain of, removing each expired entry
    /// passed on the way.
    /// </summary>
    /// <param name="host">The host to be reached; one trailing dot is ignored.</param>
    /// <returns>The entry, or <see langword="null" /> when the host is not known.</returns>
    public HstsEntry? Find(string host)
    {
        ArgumentNullException.ThrowIfNull(host);

        int index = IndexOf(host, includingParents: true);
        return index < 0 ? null : entries[index];
    }

    /// <summary>
    /// Writes the file as libcurl 8.21.0's <c>Curl_hsts_save</c> does: the two header comments,
    /// then one line per entry held, <c>[.]host "yyyyMMdd HH:mm:ss"</c> in UTC or
    /// <c>"unlimited"</c>, a leading dot for <c>includeSubDomains</c>.
    /// </summary>
    /// <param name="lineEnding">
    /// What ends each line: curl writes the file in text mode, so its Windows build ends lines
    /// in CR LF and its Linux and macOS builds in LF. Pass <see cref="Environment.NewLine" />.
    /// </param>
    /// <param name="latestWritableExpiry">
    /// The latest expiry the platform's curl can write: <see cref="LatestWritableExpiryOnWindows" />
    /// or <see cref="LatestWritableExpiryOffWindows" />.
    /// </param>
    /// <returns>
    /// The file's text, or <see langword="null" /> when an entry expires later than
    /// <paramref name="latestWritableExpiry" /> without being unlimited: curl then fails to write
    /// and leaves the file as it was.
    /// </returns>
    public string? FormatFile(string lineEnding, long latestWritableExpiry)
    {
        ArgumentNullException.ThrowIfNull(lineEnding);

        StringBuilder text = new();
        foreach (string line in FileHeaderLines)
        {
            text.Append(line).Append(lineEnding);
        }

        foreach (HstsEntry entry in entries)
        {
            if (!entry.IsUnlimited && entry.ExpiresUnixSeconds > latestWritableExpiry)
            {
                return null;
            }

            AppendLine(text, entry, lineEnding);
        }

        return text.ToString();
    }

    private static void AppendLine(StringBuilder text, HstsEntry entry, string lineEnding)
    {
        string expiry = entry.IsUnlimited ? UnlimitedText : HstsExpiryText.Format(entry.ExpiresUnixSeconds);
        text.Append(entry.IncludeSubDomains ? "." : string.Empty).Append(entry.Host).Append(" \"").Append(expiry).Append('"').Append(lineEnding);
    }

    /// <summary>
    /// Whether libcurl's <c>Curl_host_is_ipnum</c> calls <paramref name="host" /> an IP address:
    /// a dotted quad (curl's URL parser has already written every IPv4 form as one) or an IPv6
    /// address without brackets or zone.
    /// </summary>
    private static bool IsIpAddress(string host) => IsDottedQuad(host) || IsIpv6Address(host);

    private static bool IsDottedQuad(string host)
    {
        string[] octets = host.Split('.');
        return octets.Length == 4 && Array.TrueForAll(octets, IsOctet);
    }

    /// <summary>A decimal number from 0 to 255 written without a leading zero, as <c>inet_pton</c> takes it.</summary>
    private static bool IsOctet(string text) =>
        byte.TryParse(text, NumberStyles.None, CultureInfo.InvariantCulture, out byte value) && value.ToString(CultureInfo.InvariantCulture) == text;

    private static bool IsIpv6Address(string host) =>
        host.Contains(':')
        && host.AsSpan().IndexOfAny('%', '[') < 0
        && IPAddress.TryParse(host, out IPAddress? address)
        && address.AddressFamily == AddressFamily.InterNetworkV6;

    private static long ReadExpiry(string expiryText) =>
        expiryText == UnlimitedText ? HstsEntry.UnlimitedExpiry : CurlDateParser.TryParse(expiryText, out long seconds) ? seconds : 0;

    private static string WithoutTrailingDot(string host) => host.EndsWith('.') ? host[..^1] : host;

    /// <summary>libcurl's <c>hsts_add_host_expire</c> for one line of the file.</summary>
    private void AddFileEntry(HstsFileLine fileLine)
    {
        long expires = ReadExpiry(fileLine.ExpiryText);
        bool includeSubDomains = fileLine.Host.StartsWith('.');
        string host = WithoutTrailingDot(includeSubDomains ? fileLine.Host[1..] : fileLine.Host);
        if (expires <= NowSeconds() || host.Length == 0)
        {
            return;
        }

        int index = IndexOf(host, includingParents: includeSubDomains);
        if (index < 0)
        {
            Add(host, includeSubDomains, expires);
        }
        else if (AsciiText.EqualsIgnoringCase(entries[index].Host, host))
        {
            HstsEntry held = entries[index];
            entries[index] = held with
            {
                IncludeSubDomains = held.IncludeSubDomains || includeSubDomains,
                ExpiresUnixSeconds = Math.Max(held.ExpiresUnixSeconds, expires),
            };
        }
    }

    /// <summary>
    /// libcurl's <c>hsts_check</c>: the index of the host's own entry, else, when
    /// <paramref name="includingParents" />, of the longest-named <c>includeSubDomains</c> entry
    /// the host is a subdomain of, removing expired entries passed; -1 when none, and for an
    /// empty host or one longer than 2048 characters.
    /// </summary>
    private int IndexOf(string host, bool includingParents) =>
        host.Length is 0 or > HstsFileLineParser.MaxHostLength ? -1 : IndexOfName(WithoutTrailingDot(host), includingParents);

    private int IndexOfName(string name, bool includingParents)
    {
        long now = NowSeconds();
        int parent = -1;
        int index = 0;
        while (index < entries.Count)
        {
            HstsEntry entry = entries[index];
            if (entry.ExpiresUnixSeconds <= now)
            {
                entries.RemoveAt(index);
                LogVerbose("entry for ", entry.Host, " expired");
                continue;
            }

            if (AsciiText.EqualsIgnoringCase(entry.Host, name))
            {
                return index;
            }

            parent = includingParents && IsLongerParent(entry, name, parent) ? index : parent;
            index++;
        }

        return parent;
    }

    /// <summary>
    /// Whether <paramref name="entry" /> covers <paramref name="name" /> as a subdomain and has a
    /// longer name than the entry at <paramref name="parent" />.
    /// </summary>
    private bool IsLongerParent(HstsEntry entry, string name, int parent)
    {
        int offset = name.Length - entry.Host.Length;
        return entry.IncludeSubDomains
            && offset > 0
            && name[offset - 1] == '.'
            && AsciiText.EqualsIgnoringCase(name.AsSpan(offset), entry.Host)
            && (parent < 0 || entry.Host.Length > entries[parent].Host.Length);
    }

    /// <summary>libcurl's <c>hsts_create</c>: adds the host without a trailing dot, dropping the first entry when full.</summary>
    private void Add(string host, bool includeSubDomains, long expires)
    {
        string name = WithoutTrailingDot(host);
        if (name.Length == 0)
        {
            return;
        }

        if (entries.Count == MaxEntries)
        {
            entries.RemoveAt(0);
        }

        entries.Add(new HstsEntry(name, includeSubDomains, expires));
    }

    private void RemoveAt(int index)
    {
        if (index >= 0)
        {
            entries.RemoveAt(index);
        }
    }

    private long NowSeconds() => timeProvider.GetUtcNow().ToUnixTimeSeconds();

    /// <summary>
    /// Writes the <c>verbose</c> line <paramref name="before" />, <paramref name="host" /> without its
    /// trailing dot, then <paramref name="after" />, joining them only when the level is enabled.
    /// </summary>
    private void LogVerbose(string before, string host, string after)
    {
        if (log.IsEnabled(DiagnosticLogLevel.Verbose))
        {
            log.Write(DiagnosticLogLevel.Verbose, DiagnosticLogComponents.Hsts, before + WithoutTrailingDot(host) + after);
        }
    }
}
