using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Text;
using Curl.Testing;

namespace Curl.Cryptography;

/// <summary>
/// Pins <see cref="BcryptPbkdf" /> to the vectors "generated by the reference
/// implementation from OpenBSD" in Go's
/// https://github.com/golang/crypto/blob/master/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go
/// (<c>golden</c> and <c>TestBcryptHash</c>), and checks the inputs OpenBSD's
/// <c>bcrypt_pbkdf</c> refuses are an <see cref="ArgumentException" /> (ADR-0118).
/// </summary>
[TestClass]
public sealed class BcryptPbkdfTests
{
    /// <summary>Gets or sets the MSTest context the diagnostics write to.</summary>
    public TestContext TestContext { get; set; } = null!;

    // Go bcrypt_pbkdf_test.go, golden[0]: 12 rounds, a 32-byte key.
    [TestMethod]
    public void DeriveKey_GoGoldenVector0_GivesThePublishedKey()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("vector source", "Go bcrypt_pbkdf_test.go golden[0]");

        AssertDerives(
            diagnostics,
            "password"u8.ToArray(),
            "salt"u8.ToArray(),
            12,
            "1ae42c05d487bc02f64921a4ebe4ea93bcacfe135fda99974c06b7b01fae149a");
    }

    // Go bcrypt_pbkdf_test.go, golden[1]: 3 rounds, embedded NULs, a 32-byte key.
    [TestMethod]
    public void DeriveKey_GoGoldenVector1_GivesThePublishedKey()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("vector source", "Go bcrypt_pbkdf_test.go golden[1]");

        AssertDerives(
            diagnostics,
            "passwordy\0PASSWORD\0"u8.ToArray(),
            "salty\0SALT\0"u8.ToArray(),
            3,
            "7f310bd3e78c3280c59ce4595211a2928e8d4ec744c1ed2efc9f764e3388e0ad");
    }

    // Go bcrypt_pbkdf_test.go, golden[2] (from http://thread.gmane.org/gmane.os.openbsd.bugs/20542):
    // 8 rounds, UTF-8 password and salt, an 88-byte key interleaved over three blocks.
    [TestMethod]
    public void DeriveKey_GoGoldenVector2_GivesThePublishedKey()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("vector source", "Go bcrypt_pbkdf_test.go golden[2]");

        AssertDerives(
            diagnostics,
            Encoding.UTF8.GetBytes("секретное слово"),
            Encoding.UTF8.GetBytes("посолить немножко"),
            8,
            "8df43fc6fe131fc47f0c9e39224bd94c70b6fcc8ee8135faddf61156e6cb2733ea765f315a3e1e4afc35bf8687d189254c1e05a6fe80c0617f9183d67260d6a115c6c94e3603e2303fbb43a76a64523ffda686b1d4518543");
    }

    // Go bcrypt_pbkdf_test.go, TestBcryptHash: password bytes 0 to 63, salt bytes 64 to 127.
    [TestMethod]
    public void ComputeHash_GoBcryptHashVector_GivesThePublishedHash()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        byte[] passwordHash = new byte[64];
        byte[] saltHash = new byte[64];
        for (int index = 0; index < 64; index++)
        {
            passwordHash[index] = (byte)index;
            saltHash[index] = (byte)(index + 64);
        }

        byte[] hash = new byte[BcryptPbkdf.HashSize];
        diagnostics.Arrange("vector source", "Go bcrypt_pbkdf_test.go TestBcryptHash");
        diagnostics.Bytes("password", passwordHash);
        diagnostics.Bytes("salt", saltHash);

        using (diagnostics.Phase("hash"))
        {
            BcryptPbkdf.ComputeHash(new BlowfishState(), passwordHash, saltHash, hash);
        }

        const string expectedHash = "87904870eef9deddf8e7611a140106e6aaf1a363d9a2c504db356443721eb555";
        diagnostics.Act("hash", Convert.ToHexStringLower(hash));
        diagnostics.Diff("hash", expectedHash, Convert.ToHexStringLower(hash));
        Assert.AreEqual(expectedHash, Convert.ToHexStringLower(hash));
    }

    // OpenBSD bcrypt_pbkdf with one round: block k (from 1) is bcrypt_hash(SHA-512(password),
    // SHA-512(salt || BE32(k))), and a 1024-byte key has stride 32, so key[i * 32 + k - 1] is
    // byte i of block k. The reference is built here from ComputeHash, which the Go
    // TestBcryptHash vector pins, so every byte of the key is checked, not a sample.
    [TestMethod]
    public void DeriveKey_OneRoundMaximumLengthKey_EqualsTheInterleavedBlockHashes()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        byte[] password = "password"u8.ToArray();
        byte[] salt = "salt"u8.ToArray();
        byte[] key = new byte[BcryptPbkdf.MaximumKeySize];
        diagnostics.Arrange("rounds", 1);
        diagnostics.Arrange("key size", key.Length);

        using (diagnostics.Phase("derive"))
        {
            BcryptPbkdf.DeriveKey(password, salt, 1, key);
        }

        byte[] expectedKey = InterleavedOneRoundBlockHashes(password, salt, key.Length);
        diagnostics.Bytes("derived key", key);
        diagnostics.Diff("key", Convert.ToHexStringLower(expectedKey), Convert.ToHexStringLower(key));
        Assert.AreEqual(Convert.ToHexStringLower(expectedKey), Convert.ToHexStringLower(key));
    }

    private static byte[] InterleavedOneRoundBlockHashes(byte[] password, byte[] salt, int keyLength)
    {
        int stride = (keyLength + BcryptPbkdf.HashSize - 1) / BcryptPbkdf.HashSize;
        byte[] passwordHash = SHA512.HashData(password);
        byte[] countedSalt = new byte[salt.Length + 4];
        salt.CopyTo(countedSalt, 0);
        byte[] block = new byte[BcryptPbkdf.HashSize];
        byte[] key = new byte[keyLength];
        for (int blockNumber = 1; blockNumber <= stride; blockNumber++)
        {
            BinaryPrimitives.WriteUInt32BigEndian(countedSalt.AsSpan(salt.Length), (uint)blockNumber);
            BcryptPbkdf.ComputeHash(new BlowfishState(), passwordHash, SHA512.HashData(countedSalt), block);
            for (int index = 0; (index * stride) + blockNumber - 1 < keyLength; index++)
            {
                key[(index * stride) + blockNumber - 1] = block[index];
            }
        }

        return key;
    }

    [TestMethod]
    [DataRow(0, 4, 32, "password")]
    [DataRow(8, 0, 32, "salt")]
    [DataRow(8, BcryptPbkdf.MaximumSaltSize + 1, 32, "salt")]
    [DataRow(8, 4, 0, "destination")]
    [DataRow(8, 4, BcryptPbkdf.MaximumKeySize + 1, "destination")]
    public void DeriveKey_LengthOpenBsdRefuses_ThrowsArgumentException(int passwordLength, int saltLength, int keyLength, string parameterName)
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("password length", passwordLength);
        diagnostics.Arrange("salt length", saltLength);
        diagnostics.Arrange("key length", keyLength);

        ArgumentException exception = Assert.ThrowsExactly<ArgumentException>(
            () => BcryptPbkdf.DeriveKey(new byte[passwordLength], new byte[saltLength], 1, new byte[keyLength]));
        diagnostics.Act("exception ParamName", exception.ParamName);

        diagnostics.Assert("ParamName", parameterName, exception.ParamName);
        Assert.AreEqual(parameterName, exception.ParamName);
    }

    [TestMethod]
    public void DeriveKey_ZeroRounds_ThrowsArgumentOutOfRangeException()
    {
        var diagnostics = TestDiagnostics.For(TestContext);
        diagnostics.Arrange("rounds", 0);

        ArgumentOutOfRangeException exception = Assert.ThrowsExactly<ArgumentOutOfRangeException>(
            () => BcryptPbkdf.DeriveKey("password"u8, "salt"u8, 0, new byte[32]));
        diagnostics.Act("exception ParamName", exception.ParamName);

        diagnostics.Assert("ParamName", "rounds", exception.ParamName);
        Assert.AreEqual("rounds", exception.ParamName);
    }

    private static void AssertDerives(TestDiagnostics diagnostics, byte[] password, byte[] salt, int rounds, string expectedKey)
    {
        byte[] key = new byte[expectedKey.Length / 2];
        diagnostics.Bytes("password", password);
        diagnostics.Bytes("salt", salt);
        diagnostics.Arrange("rounds", rounds);
        diagnostics.Arrange("key length", key.Length);

        using (diagnostics.Phase("derive"))
        {
            BcryptPbkdf.DeriveKey(password, salt, rounds, key);
        }

        diagnostics.Act("derived key", Convert.ToHexStringLower(key));
        diagnostics.Diff("derived key", expectedKey, Convert.ToHexStringLower(key));
        Assert.AreEqual(expectedKey, Convert.ToHexStringLower(key));
    }
}
