<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Curl.Conformance.UnitLibrary\Curl.Conformance.UnitLibrary.csproj" />
    <ProjectReference Include="..\Curl.Console\Curl.Console.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="UpstreamTestData\test*.rawhttp;UpstreamTestData\COPYING;UpstreamTestData\certs\*;PassingUpstreamCases.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
