// Ported from OpenSSL 3.5 crypto/asn1/a_strex.c, Copyright The OpenSSL Project Authors,
// under the Apache License 2.0.

using System.Formats.Asn1;
using System.Security.Cryptography.X509Certificates;
using System.Text;

namespace Curl.Output;

/// <summary>
/// Prints a distinguished name as curl 8.21.0's OpenSSL build prints a certificate's subject
/// and issuer for <c>-v</c>: <c>X509_NAME_print_ex</c> with the flags of curl's
/// <c>x509_name_oneline</c> (ADR-0085).
/// </summary>
/// <remarks>
/// Those flags are <c>XN_FLAG_SEP_SPLUS_SPC | (XN_FLAG_ONELINE &amp; ~ASN1_STRFLGS_ESC_MSB
/// &amp; ~XN_FLAG_SPC_EQ)</c>: attributes in the order encoded, <c>; </c> between relative
/// names and <c> + </c> within one, OpenSSL's short name then <c>=</c>, strings converted to
/// UTF-8 with bytes above 0x7F left as they are, a value holding <c>,+;&lt;&gt;</c> or a
/// leading <c>#</c> or space or a trailing space put in double quotes, <c>"</c> and
/// <c>\</c> escaped with a backslash, control characters as <c>\XX</c>, and a value that is
/// not a string printed as <c>#</c> and its DER encoding in hex.
/// </remarks>
internal static class OpenSslDistinguishedNameText
{
    private const int EscapeRfc2253 = 0x01;
    private const int EscapeControl = 0x02;
    private const int EscapeWithQuotes = 0x08;
    private const int FirstCharacter = 0x20;
    private const int LastCharacter = 0x40;
    private const int BackslashEscapes = EscapeRfc2253 | FirstCharacter | LastCharacter;
    private const int EscapeFlags = EscapeRfc2253 | EscapeControl | EscapeWithQuotes;
    private const int Utf8StringTag = 12;

    // OpenSSL's char_type, generated by crypto/asn1/charmap.pl, for 0 to 127.
    private static readonly ushort[] CharacterTypes =
    [
        1026, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 120, 0, 1, 40,
        0, 0, 0, 16, 1040, 1040, 33792, 25, 25, 16400, 8208, 16,
        4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 16, 9,
        9, 16, 9, 16, 0, 4112, 4112, 4112, 4112, 4112, 4112, 4112,
        4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112,
        4112, 4112, 4112, 4112, 4112, 4112, 4112, 0, 1025, 0, 0, 0,
        0, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112,
        4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112, 4112,
        4112, 4112, 4112, 0, 0, 0, 0, 2,
    ];

    // OpenSSL's tag2nbyte for the string types: bytes per character, 0 for UTF-8.
    private static readonly Dictionary<int, int> CharacterWidths = new()
    {
        [Utf8StringTag] = 0,
        [18] = 1,
        [19] = 1,
        [20] = 1,
        [22] = 1,
        [23] = 1,
        [24] = 1,
        [26] = 1,
        [28] = 4,
        [30] = 2,
    };

    // OpenSSL's short names for the attribute types a certificate name carries.
    private static readonly Dictionary<string, string> ShortNames = new(StringComparer.Ordinal)
    {
        ["2.5.4.3"] = "CN",
        ["2.5.4.4"] = "SN",
        ["2.5.4.5"] = "serialNumber",
        ["2.5.4.6"] = "C",
        ["2.5.4.7"] = "L",
        ["2.5.4.8"] = "ST",
        ["2.5.4.9"] = "street",
        ["2.5.4.10"] = "O",
        ["2.5.4.11"] = "OU",
        ["2.5.4.12"] = "title",
        ["2.5.4.13"] = "description",
        ["2.5.4.15"] = "businessCategory",
        ["2.5.4.17"] = "postalCode",
        ["2.5.4.41"] = "name",
        ["2.5.4.42"] = "GN",
        ["2.5.4.43"] = "initials",
        ["2.5.4.44"] = "generationQualifier",
        ["2.5.4.45"] = "x500UniqueIdentifier",
        ["2.5.4.46"] = "dnQualifier",
        ["2.5.4.65"] = "pseudonym",
        ["2.5.4.72"] = "role",
        ["2.5.4.97"] = "organizationIdentifier",
        ["1.2.840.113549.1.9.1"] = "emailAddress",
        ["1.2.840.113549.1.9.2"] = "unstructuredName",
        ["0.9.2342.19200300.100.1.1"] = "UID",
        ["0.9.2342.19200300.100.1.25"] = "DC",
        ["1.3.6.1.4.1.311.60.2.1.1"] = "jurisdictionL",
        ["1.3.6.1.4.1.311.60.2.1.2"] = "jurisdictionST",
        ["1.3.6.1.4.1.311.60.2.1.3"] = "jurisdictionC",
    };

    /// <summary>Prints a name.</summary>
    /// <param name="name">The name.</param>
    /// <returns>The text, or <see langword="null"/> when OpenSSL could not print it.</returns>
    internal static string? Format(X500DistinguishedName name)
    {
        var output = new List<byte>();
        try
        {
            var names = new AsnReader(name.RawData, AsnEncodingRules.BER).ReadSequence();
            var separator = string.Empty;
            while (names.HasData)
            {
                AppendRelativeName(output, names.ReadSetOf(skipSortOrderValidation: true), separator);
                separator = "; ";
            }
        }
        catch (AsnContentException)
        {
            return null;
        }
        catch (FormatException)
        {
            return null;
        }

        return Encoding.UTF8.GetString(output.ToArray());
    }

    private static void AppendRelativeName(List<byte> output, AsnReader attributes, string separator)
    {
        while (attributes.HasData)
        {
            var attribute = attributes.ReadSequence();
            var type = attribute.ReadObjectIdentifier();
            Append(output, separator);
            Append(output, ShortNames.GetValueOrDefault(type, type));
            output.Add((byte)'=');
            AppendValue(output, attribute.ReadEncodedValue());
            separator = " + ";
        }
    }

    // do_print_ex: a string type is printed character by character, anything else dumped.
    private static void AppendValue(List<byte> output, ReadOnlyMemory<byte> encoded)
    {
        var tag = new AsnReader(encoded, AsnEncodingRules.BER).PeekTag();
        if (tag.TagClass != TagClass.Universal || tag.IsConstructed || !CharacterWidths.TryGetValue(tag.TagValue, out var width))
        {
            output.Add((byte)'#');
            Append(output, Convert.ToHexString(encoded.Span));
            return;
        }

        AppendString(output, new AsnReader(encoded, AsnEncodingRules.BER).PeekContentBytes().ToArray(), width);
    }

    // do_buf, run once to learn whether the value needs quotes and once to print it.
    private static void AppendString(List<byte> output, byte[] content, int width)
    {
        var characters = ReadCharacters(content, width);
        var value = new List<byte>();
        var quoted = false;
        for (var index = 0; index < characters.Length; index++)
        {
            var position = index == characters.Length - 1 ? LastCharacter : index == 0 ? FirstCharacter : 0;
            quoted |= AppendCharacter(value, characters[index], width == 0, position);
        }

        if (quoted)
        {
            output.Add((byte)'"');
            output.AddRange(value);
            output.Add((byte)'"');
            return;
        }

        output.AddRange(value);
    }

    // A UTF8String is taken a byte at a time, as ASN1_STRFLGS_UTF8_CONVERT makes do_print_ex
    // do to avoid converting it twice; the other types a character of their width at a time.
    private static int[] ReadCharacters(byte[] content, int width)
    {
        var size = Math.Max(width, 1);
        if (content.Length % size != 0)
        {
            throw new FormatException("The string's length is not a whole number of characters.");
        }

        var characters = new int[content.Length / size];
        for (var index = 0; index < characters.Length; index++)
        {
            var character = 0;
            for (var offset = 0; offset < size; offset++)
            {
                character = (character << 8) | content[(index * size) + offset];
            }

            characters[index] = character;
        }

        return characters;
    }

    // do_esc_char for one character; returns whether the value must be quoted.
    private static bool AppendCharacter(List<byte> value, int character, bool isUtf8Byte, int position)
    {
        if ((uint)character > 0x7F)
        {
            AppendAboveAscii(value, character, isUtf8Byte);
            return false;
        }

        var type = CharacterTypes[character] & (EscapeFlags | position);
        if ((type & BackslashEscapes) != 0)
        {
            if ((type & EscapeWithQuotes) != 0)
            {
                value.Add((byte)character);
                return true;
            }

            value.Add((byte)'\\');
            value.Add((byte)character);
            return false;
        }

        if ((type & EscapeControl) != 0)
        {
            Append(value, $"\\{character:X2}");
            return false;
        }

        value.Add((byte)character);
        return false;
    }

    // A UTF-8 byte goes out as it is; any other character as its UTF-8 bytes, which are all
    // above 0x7F and so never escaped. A surrogate or a value past U+10FFFF, which UTF8_putc
    // refuses, prints nothing.
    private static void AppendAboveAscii(List<byte> value, int character, bool isUtf8Byte)
    {
        if (isUtf8Byte)
        {
            value.Add((byte)character);
            return;
        }

        if (Rune.TryCreate(character, out var rune))
        {
            Span<byte> bytes = stackalloc byte[4];
            value.AddRange(bytes[..rune.EncodeToUtf8(bytes)]);
        }
    }

    private static void Append(List<byte> output, string text)
    {
        output.AddRange(Encoding.ASCII.GetBytes(text));
    }
}
