namespace Curl.Cli;

/// <summary>
/// Every row curl 8.21.0 prints in its option help, in its order: the option as shown, its one-line
/// description and its categories, copied from curl's generated <c>src/tool_listhelp.c</c> at tag
/// <c>curl-8_21_0</c>. It lists all of curl's options, not only those <see cref="CommandLineOptionTable"/>
/// parses, because curl's help lists them all (ADR-0066).
/// </summary>
internal static class CurlHelpTable
{
    /// <summary>The rows, in curl's order.</summary>
    internal static readonly IReadOnlyList<CurlHelpEntry> Entries =
    [
        new("    --abstract-unix-socket <path>", "Connect via abstract Unix domain socket", CurlHelpCategories.Connection),
        new("    --alt-svc <filename>", "Enable alt-svc with this cache file", CurlHelpCategories.Http),
        new("    --anyauth", "Pick any authentication method", CurlHelpCategories.Http | CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("-a, --append", "Append to target file when uploading", CurlHelpCategories.Ftp | CurlHelpCategories.Sftp),
        new("    --aws-sigv4 <provider1[:prvdr2[:reg[:srv]]]>", "AWS V4 signature auth", CurlHelpCategories.Auth | CurlHelpCategories.Http),
        new("    --basic", "HTTP Basic Authentication", CurlHelpCategories.Auth),
        new("    --ca-native", "Load CA certs from the OS", CurlHelpCategories.Tls),
        new("    --cacert <file>", "CA certificate to verify peer against", CurlHelpCategories.Tls),
        new("    --capath <dir>", "CA directory to verify peer against", CurlHelpCategories.Tls),
        new("-E, --cert <certificate[:password]>", "Client certificate file and password", CurlHelpCategories.Tls),
        new("    --cert-status", "Verify server cert status OCSP-staple", CurlHelpCategories.Tls),
        new("    --cert-type <type>", "Certificate type (DER/PEM/ENG/PROV/P12)", CurlHelpCategories.Tls),
        new("    --ciphers <list>", "TLS 1.2 (1.1, 1.0) ciphers to use", CurlHelpCategories.Tls),
        new("    --compressed", "Request compressed response", CurlHelpCategories.Http),
        new("    --compressed-ssh", "Enable SSH compression", CurlHelpCategories.Scp | CurlHelpCategories.Ssh),
        new("-K, --config <file>", "Read config from a file", CurlHelpCategories.Curl),
        new("    --connect-timeout <seconds>", "Maximum time allowed to connect", CurlHelpCategories.Connection | CurlHelpCategories.Timeout),
        new("    --connect-to <HOST1:PORT1:HOST2:PORT2>", "Connect to host2 instead of host1", CurlHelpCategories.Connection | CurlHelpCategories.Dns),
        new("-C, --continue-at <offset>", "Resumed transfer offset", CurlHelpCategories.Connection),
        new("-b, --cookie <data|filename>", "Send cookies from string/load from file", CurlHelpCategories.Http),
        new("-c, --cookie-jar <filename>", "Save cookies to <filename> after operation", CurlHelpCategories.Http),
        new("    --create-dirs", "Create necessary local directory hierarchy", CurlHelpCategories.Output),
        new("    --create-file-mode <mode>", "File mode for created files", CurlHelpCategories.Sftp | CurlHelpCategories.Scp | CurlHelpCategories.File | CurlHelpCategories.Upload),
        new("    --crlf", "Convert LF to CRLF in upload", CurlHelpCategories.Ftp | CurlHelpCategories.Smtp),
        new("    --crlfile <file>", "Certificate Revocation list", CurlHelpCategories.Tls),
        new("    --curves <list>", "(EC) TLS key exchange algorithms to request", CurlHelpCategories.Tls),
        new("-d, --data <data>", "HTTP POST data", CurlHelpCategories.Important | CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("    --data-ascii <data>", "HTTP POST ASCII data", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("    --data-binary <data>", "HTTP POST binary data", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("    --data-raw <data>", "HTTP POST data, '@' allowed", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("    --data-urlencode <data>", "HTTP POST data URL encoded", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("    --delegation <LEVEL>", "GSS-API delegation permission", CurlHelpCategories.Auth),
        new("    --digest", "HTTP Digest Authentication", CurlHelpCategories.Proxy | CurlHelpCategories.Auth | CurlHelpCategories.Http),
        new("-q, --disable", "Disable .curlrc", CurlHelpCategories.Curl),
        new("    --disable-eprt", "Inhibit using EPRT or LPRT", CurlHelpCategories.Ftp),
        new("    --disable-epsv", "Inhibit using EPSV", CurlHelpCategories.Ftp),
        new("    --disallow-username-in-url", "Disallow username in URL", CurlHelpCategories.Curl),
        new("    --dns-interface <interface>", "Interface to use for DNS requests", CurlHelpCategories.Dns),
        new("    --dns-ipv4-addr <address>", "IPv4 address to use for DNS requests", CurlHelpCategories.Dns),
        new("    --dns-ipv6-addr <address>", "IPv6 address to use for DNS requests", CurlHelpCategories.Dns),
        new("    --dns-servers <addresses>", "DNS server addrs to use", CurlHelpCategories.Dns),
        new("    --doh-cert-status", "Verify DoH server cert status OCSP-staple", CurlHelpCategories.Dns | CurlHelpCategories.Tls),
        new("    --doh-insecure", "Allow insecure DoH server connections", CurlHelpCategories.Dns | CurlHelpCategories.Tls),
        new("    --doh-url <URL>", "Resolve hostnames over DoH", CurlHelpCategories.Dns),
        new("    --dump-ca-embed", "Write the embedded CA bundle to standard output", CurlHelpCategories.Http | CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("-D, --dump-header <filename>", "Write the received headers to <filename>", CurlHelpCategories.Http | CurlHelpCategories.Ftp),
        new("    --ech <config>", "Configure ECH", CurlHelpCategories.Tls),
        new("    --egd-file <file>", "EGD socket path for random data", CurlHelpCategories.Deprecated),
        new("    --engine <name>", "Crypto engine to use", CurlHelpCategories.Tls),
        new("    --etag-compare <file>", "Load ETag from file", CurlHelpCategories.Http),
        new("    --etag-save <file>", "Parse incoming ETag and save to a file", CurlHelpCategories.Http),
        new("    --expect100-timeout <seconds>", "How long to wait for 100-continue", CurlHelpCategories.Http | CurlHelpCategories.Timeout),
        new("-f, --fail", "Fail fast with no output on HTTP errors", CurlHelpCategories.Important | CurlHelpCategories.Http),
        new("    --fail-early", "Fail on first transfer error", CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --fail-with-body", "Fail on HTTP errors but save the body", CurlHelpCategories.Http | CurlHelpCategories.Output),
        new("    --false-start", "Enable TLS False Start", CurlHelpCategories.Deprecated),
        new("    --follow", "Follow redirects per spec", CurlHelpCategories.Http),
        new("-F, --form <name=content>", "Specify multipart MIME data", CurlHelpCategories.Http | CurlHelpCategories.Upload | CurlHelpCategories.Post | CurlHelpCategories.Imap | CurlHelpCategories.Smtp),
        new("    --form-escape", "Escape form fields using backslash", CurlHelpCategories.Http | CurlHelpCategories.Upload | CurlHelpCategories.Post),
        new("    --form-string <name=string>", "Specify multipart MIME data", CurlHelpCategories.Http | CurlHelpCategories.Upload | CurlHelpCategories.Post | CurlHelpCategories.Smtp | CurlHelpCategories.Imap),
        new("    --ftp-account <data>", "Account data string", CurlHelpCategories.Ftp | CurlHelpCategories.Auth),
        new("    --ftp-alternative-to-user <command>", "String to replace USER [name]", CurlHelpCategories.Ftp),
        new("    --ftp-create-dirs", "Create the remote dirs if not present", CurlHelpCategories.Ftp | CurlHelpCategories.Sftp),
        new("    --ftp-method <method>", "Control CWD usage", CurlHelpCategories.Ftp),
        new("    --ftp-pasv", "Send PASV/EPSV instead of PORT", CurlHelpCategories.Ftp),
        new("-P, --ftp-port <address>", "Send PORT instead of PASV", CurlHelpCategories.Ftp),
        new("    --ftp-pret", "Send PRET before PASV", CurlHelpCategories.Ftp),
        new("    --ftp-skip-pasv-ip", "Skip the IP address for PASV", CurlHelpCategories.Ftp),
        new("    --ftp-ssl-ccc", "Send CCC after authenticating", CurlHelpCategories.Ftp | CurlHelpCategories.Tls),
        new("    --ftp-ssl-ccc-mode <active/passive>", "Set CCC mode", CurlHelpCategories.Ftp | CurlHelpCategories.Tls),
        new("    --ftp-ssl-control", "Require TLS for login, clear for transfer", CurlHelpCategories.Ftp | CurlHelpCategories.Tls),
        new("-G, --get", "Put the post data in the URL and use GET", CurlHelpCategories.Http),
        new("-g, --globoff", "Disable URL globbing with {} and []", CurlHelpCategories.Curl),
        new("    --happy-eyeballs-timeout-ms <ms>", "Time for IPv6 before IPv4", CurlHelpCategories.Connection | CurlHelpCategories.Timeout),
        new("    --haproxy-clientip <ip>", "Set address in HAProxy PROXY", CurlHelpCategories.Http | CurlHelpCategories.Proxy),
        new("    --haproxy-protocol", "Send HAProxy PROXY protocol v1 header", CurlHelpCategories.Http | CurlHelpCategories.Proxy),
        new("-I, --head", "Show document info only", CurlHelpCategories.Important | CurlHelpCategories.Http | CurlHelpCategories.Ftp | CurlHelpCategories.File),
        new("-H, --header <header/@file>", "Pass custom header(s) to server", CurlHelpCategories.Important | CurlHelpCategories.Http | CurlHelpCategories.Imap | CurlHelpCategories.Smtp),
        new("-h, --help <subject>", "Get help for commands", CurlHelpCategories.Important | CurlHelpCategories.Curl),
        new("    --hostpubmd5 <md5>", "Acceptable MD5 hash of host public key", CurlHelpCategories.Sftp | CurlHelpCategories.Scp | CurlHelpCategories.Ssh),
        new("    --hostpubsha256 <sha256>", "Acceptable SHA256 hash of host public key", CurlHelpCategories.Sftp | CurlHelpCategories.Scp | CurlHelpCategories.Ssh),
        new("    --hsts <filename>", "Enable HSTS with this cache file", CurlHelpCategories.Http),
        new("    --http0.9", "Allow HTTP/0.9 responses", CurlHelpCategories.Http),
        new("-0, --http1.0", "Use HTTP/1.0", CurlHelpCategories.Http),
        new("    --http1.1", "Use HTTP/1.1", CurlHelpCategories.Http),
        new("    --http2", "Use HTTP/2", CurlHelpCategories.Http),
        new("    --http2-prior-knowledge", "Use HTTP/2 without HTTP/1.1 Upgrade", CurlHelpCategories.Http),
        new("    --http3", "Use HTTP/3", CurlHelpCategories.Http),
        new("    --http3-only", "Use HTTP/3 only", CurlHelpCategories.Http),
        new("    --ignore-content-length", "Ignore the size of the remote resource", CurlHelpCategories.Http | CurlHelpCategories.Ftp),
        new("-k, --insecure", "Allow insecure server connections", CurlHelpCategories.Tls | CurlHelpCategories.Sftp | CurlHelpCategories.Scp | CurlHelpCategories.Ssh),
        new("    --interface <name>", "Use network interface", CurlHelpCategories.Connection),
        new("    --ip-tos <string>", "Set IP Type of Service or Traffic Class", CurlHelpCategories.Connection),
        new("    --ipfs-gateway <URL>", "Gateway for IPFS", CurlHelpCategories.Curl),
        new("-4, --ipv4", "Resolve names to IPv4 addresses", CurlHelpCategories.Connection | CurlHelpCategories.Dns),
        new("-6, --ipv6", "Resolve names to IPv6 addresses", CurlHelpCategories.Connection | CurlHelpCategories.Dns),
        new("    --json <data>", "HTTP POST JSON", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("-j, --junk-session-cookies", "Ignore session cookies read from file", CurlHelpCategories.Http),
        new("    --keepalive-cnt <integer>", "Maximum number of keepalive probes", CurlHelpCategories.Connection),
        new("    --keepalive-time <seconds>", "Interval time for keepalive probes", CurlHelpCategories.Connection | CurlHelpCategories.Timeout),
        new("    --key <key>", "Private key filename", CurlHelpCategories.Tls | CurlHelpCategories.Ssh),
        new("    --key-type <type>", "Private key file type (DER/PEM/ENG)", CurlHelpCategories.Tls),
        new("    --knownhosts <file>", "Specify knownhosts path", CurlHelpCategories.Ssh),
        new("    --krb <level>", "Enable Kerberos with security <level>", CurlHelpCategories.Deprecated),
        new("    --libcurl <file>", "Generate libcurl code for this command line", CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --limit-rate <speed>", "Limit transfer speed to RATE", CurlHelpCategories.Connection),
        new("-l, --list-only", "List only mode", CurlHelpCategories.Ftp | CurlHelpCategories.Pop3 | CurlHelpCategories.Sftp | CurlHelpCategories.File),
        new("    --local-port <range>", "Use a local port number within RANGE", CurlHelpCategories.Connection),
        new("-L, --location", "Follow redirects", CurlHelpCategories.Http),
        new("    --location-trusted", "As --location, but send secrets to other hosts", CurlHelpCategories.Http | CurlHelpCategories.Auth),
        new("    --login-options <options>", "Server login options", CurlHelpCategories.Imap | CurlHelpCategories.Pop3 | CurlHelpCategories.Smtp | CurlHelpCategories.Auth | CurlHelpCategories.Ldap),
        new("    --mail-auth <address>", "Originator address of the original email", CurlHelpCategories.Smtp),
        new("    --mail-from <address>", "Mail from this address", CurlHelpCategories.Smtp),
        new("    --mail-rcpt <address>", "Mail to this address", CurlHelpCategories.Smtp),
        new("    --mail-rcpt-allowfails", "Allow RCPT TO command to fail", CurlHelpCategories.Smtp),
        new("-M, --manual", "Display the full manual", CurlHelpCategories.Curl),
        new("    --max-filesize <bytes>", "Maximum file size to download", CurlHelpCategories.Connection),
        new("    --max-redirs <num>", "Maximum number of redirects allowed", CurlHelpCategories.Http),
        new("-m, --max-time <seconds>", "Maximum time allowed for transfer", CurlHelpCategories.Connection | CurlHelpCategories.Timeout),
        new("    --metalink", "Process given URLs as metalink XML file", CurlHelpCategories.Deprecated),
        new("    --mptcp", "Enable Multipath TCP", CurlHelpCategories.Connection),
        new("    --negotiate", "Use HTTP Negotiate (SPNEGO) authentication", CurlHelpCategories.Auth | CurlHelpCategories.Http),
        new("-n, --netrc", "Must read .netrc for username and password", CurlHelpCategories.Auth),
        new("    --netrc-file <filename>", "Specify FILE for netrc", CurlHelpCategories.Auth),
        new("    --netrc-optional", "Use either .netrc or URL", CurlHelpCategories.Auth),
        new("-:, --next", "Make next URL use separate options", CurlHelpCategories.Curl),
        new("    --no-alpn", "Disable the ALPN TLS extension", CurlHelpCategories.Tls | CurlHelpCategories.Http),
        new("-N, --no-buffer", "Disable buffering of the output stream", CurlHelpCategories.Output),
        new("    --no-clobber", "Do not overwrite files that already exist", CurlHelpCategories.Output),
        new("    --no-keepalive", "Disable TCP keepalive on the connection", CurlHelpCategories.Connection),
        new("    --no-npn", "Disable the NPN TLS extension", CurlHelpCategories.Deprecated),
        new("    --no-progress-meter", "Do not show the progress meter", CurlHelpCategories.Verbose),
        new("    --no-sessionid", "Disable SSL session-ID reusing", CurlHelpCategories.Tls),
        new("    --noproxy <no-proxy-list>", "List of hosts which do not use proxy", CurlHelpCategories.Proxy),
        new("    --ntlm", "HTTP NTLM authentication", CurlHelpCategories.Auth | CurlHelpCategories.Http),
        new("    --ntlm-wb", "HTTP NTLM authentication with winbind", CurlHelpCategories.Deprecated),
        new("    --oauth2-bearer <token>", "OAuth 2 Bearer Token", CurlHelpCategories.Auth | CurlHelpCategories.Imap | CurlHelpCategories.Pop3 | CurlHelpCategories.Smtp | CurlHelpCategories.Ldap),
        new("    --out-null", "Discard response data into the void", CurlHelpCategories.Output),
        new("-o, --output <file>", "Write to file instead of stdout", CurlHelpCategories.Important | CurlHelpCategories.Output),
        new("    --output-dir <dir>", "Directory to save files in", CurlHelpCategories.Output),
        new("-Z, --parallel", "Perform transfers in parallel", CurlHelpCategories.Connection | CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --parallel-immediate", "Do not wait for multiplexing", CurlHelpCategories.Connection | CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --parallel-max <num>", "Maximum concurrency for parallel transfers", CurlHelpCategories.Connection | CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --parallel-max-host <num>", "Maximum connections to a single host", CurlHelpCategories.Connection | CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("    --pass <phrase>", "Passphrase for the private key", CurlHelpCategories.Ssh | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --path-as-is", "Do not squash .. sequences in URL path", CurlHelpCategories.Curl),
        new("    --pinnedpubkey <hashes>", "Public key to verify peer against", CurlHelpCategories.Tls),
        new("    --post301", "Do not switch to GET after a 301 redirect", CurlHelpCategories.Http | CurlHelpCategories.Post),
        new("    --post302", "Do not switch to GET after a 302 redirect", CurlHelpCategories.Http | CurlHelpCategories.Post),
        new("    --post303", "Do not switch to GET after a 303 redirect", CurlHelpCategories.Http | CurlHelpCategories.Post),
        new("    --preproxy <[protocol://]host[:port]>", "Use this proxy first", CurlHelpCategories.Proxy),
        new("-#, --progress-bar", "Display transfer progress as a bar", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --proto <protocols>", "Enable/disable PROTOCOLS", CurlHelpCategories.Connection | CurlHelpCategories.Curl),
        new("    --proto-default <protocol>", "Use PROTOCOL for any URL missing a scheme", CurlHelpCategories.Connection | CurlHelpCategories.Curl),
        new("    --proto-redir <protocols>", "Enable/disable PROTOCOLS on redirect", CurlHelpCategories.Connection | CurlHelpCategories.Curl),
        new("-x, --proxy <[protocol://]host[:port]>", "Use this proxy", CurlHelpCategories.Proxy),
        new("    --proxy-anyauth", "Pick any proxy authentication method", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --proxy-basic", "Use Basic authentication on the proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --proxy-ca-native", "Load CA certs from the OS to verify proxy", CurlHelpCategories.Tls),
        new("    --proxy-cacert <file>", "CA certificates to verify proxy against", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-capath <dir>", "CA directory to verify proxy against", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-cert <cert[:passwd]>", "Set client certificate for proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-cert-type <type>", "Client certificate type for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-ciphers <list>", "TLS 1.2 (1.1, 1.0) ciphers to use for proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-crlfile <file>", "Set a CRL list for proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-digest", "Digest auth with the proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-header <header/@file>", "Pass custom header(s) to proxy", CurlHelpCategories.Proxy),
        new("    --proxy-http2", "Use HTTP/2 with HTTPS proxy", CurlHelpCategories.Http | CurlHelpCategories.Proxy),
        new("    --proxy-http3", "Use HTTP/3 with HTTPS proxy", CurlHelpCategories.Http | CurlHelpCategories.Proxy),
        new("    --proxy-insecure", "Skip HTTPS proxy cert verification", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-key <key>", "Private key for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-key-type <type>", "Private key file type for proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-negotiate", "HTTP Negotiate (SPNEGO) auth with the proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --proxy-ntlm", "NTLM authentication with the proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --proxy-pass <phrase>", "Passphrase for private key for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --proxy-pinnedpubkey <hashes>", "FILE/HASHES public key to verify proxy with", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-service-name <name>", "SPNEGO proxy service name", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-ssl-allow-beast", "Allow this security flaw for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-ssl-auto-client-cert", "Auto client certificate for proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-tls13-ciphers <list>", "TLS 1.3 proxy cipher suites", CurlHelpCategories.Proxy | CurlHelpCategories.Tls),
        new("    --proxy-tlsauthtype <type>", "TLS authentication type for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --proxy-tlspassword <string>", "TLS password for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --proxy-tlsuser <name>", "TLS username for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --proxy-tlsv1", "TLSv1 for HTTPS proxy", CurlHelpCategories.Proxy | CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("-U, --proxy-user <user:password>", "Proxy user and password", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --proxy1.0 <host[:port]>", "Use HTTP/1.0 proxy on given port", CurlHelpCategories.Proxy),
        new("-p, --proxytunnel", "HTTP proxy tunnel (using CONNECT)", CurlHelpCategories.Proxy),
        new("    --pubkey <key>", "SSH Public key filename", CurlHelpCategories.Sftp | CurlHelpCategories.Scp | CurlHelpCategories.Ssh | CurlHelpCategories.Auth),
        new("-Q, --quote <command>", "Send command(s) to server before transfer", CurlHelpCategories.Ftp | CurlHelpCategories.Sftp),
        new("    --random-file <file>", "File for reading random data from", CurlHelpCategories.Deprecated),
        new("-r, --range <range>", "Retrieve only the bytes within RANGE", CurlHelpCategories.Http | CurlHelpCategories.Ftp | CurlHelpCategories.Sftp | CurlHelpCategories.File),
        new("    --rate <max request rate>", "Request rate for serial transfers", CurlHelpCategories.Connection | CurlHelpCategories.Global),
        new("    --raw", "Do HTTP raw; no transfer decoding", CurlHelpCategories.Http),
        new("-e, --referer <URL>", "Referrer URL", CurlHelpCategories.Http),
        new("-J, --remote-header-name", "Use the header-provided filename", CurlHelpCategories.Output),
        new("-O, --remote-name", "Write output to file named as remote file", CurlHelpCategories.Important | CurlHelpCategories.Output),
        new("    --remote-name-all", "Use the remote filename for all URLs", CurlHelpCategories.Output),
        new("-R, --remote-time", "Set remote file's time on local output", CurlHelpCategories.Output),
        new("    --remove-on-error", "Remove output file on errors", CurlHelpCategories.Output),
        new("-X, --request <method>", "Specify request method to use", CurlHelpCategories.Connection | CurlHelpCategories.Pop3 | CurlHelpCategories.Ftp | CurlHelpCategories.Imap | CurlHelpCategories.Smtp),
        new("    --request-target <path>", "Specify the target for this request", CurlHelpCategories.Http),
        new("    --resolve <[+]host:port:addr[,addr]...>", "Resolve host+port to address", CurlHelpCategories.Connection | CurlHelpCategories.Dns),
        new("    --retry <num>", "Retry request if transient problems occur", CurlHelpCategories.Curl),
        new("    --retry-all-errors", "Retry all errors (with --retry)", CurlHelpCategories.Curl),
        new("    --retry-connrefused", "Retry on connection refused (with --retry)", CurlHelpCategories.Curl),
        new("    --retry-delay <seconds>", "Wait time between retries", CurlHelpCategories.Curl | CurlHelpCategories.Timeout),
        new("    --retry-max-time <seconds>", "Retry only within this period", CurlHelpCategories.Curl | CurlHelpCategories.Timeout),
        new("    --sasl-authzid <identity>", "Identity for SASL PLAIN authentication", CurlHelpCategories.Auth),
        new("    --sasl-ir", "Initial response in SASL authentication", CurlHelpCategories.Auth),
        new("    --service-name <name>", "SPNEGO service name", CurlHelpCategories.Auth),
        new("-S, --show-error", "Show error even when -s is used", CurlHelpCategories.Curl | CurlHelpCategories.Global),
        new("-i, --show-headers", "Show response headers in output", CurlHelpCategories.Important | CurlHelpCategories.Verbose | CurlHelpCategories.Output),
        new("    --sigalgs <list>", "TLS signature algorithms to use", CurlHelpCategories.Tls),
        new("-s, --silent", "Silent mode", CurlHelpCategories.Important | CurlHelpCategories.Verbose),
        new("    --skip-existing", "Skip download if local file already exists", CurlHelpCategories.Curl | CurlHelpCategories.Output),
        new("    --socks4 <host[:port]>", "SOCKS4 proxy on given host + port", CurlHelpCategories.Proxy),
        new("    --socks4a <host[:port]>", "SOCKS4a proxy on given host + port", CurlHelpCategories.Proxy),
        new("    --socks5 <host[:port]>", "SOCKS5 proxy on given host + port", CurlHelpCategories.Proxy),
        new("    --socks5-basic", "Username/password auth for SOCKS5 proxies", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --socks5-gssapi", "Enable GSS-API auth for SOCKS5 proxies", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --socks5-gssapi-nec", "Compatibility with NEC SOCKS5 server", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --socks5-gssapi-service <name>", "SOCKS5 proxy service name for GSS-API", CurlHelpCategories.Proxy | CurlHelpCategories.Auth),
        new("    --socks5-hostname <host[:port]>", "SOCKS5 proxy, pass hostname to proxy", CurlHelpCategories.Proxy),
        new("-Y, --speed-limit <speed>", "Stop transfers slower than this", CurlHelpCategories.Connection),
        new("-y, --speed-time <seconds>", "Trigger 'speed-limit' abort after this time", CurlHelpCategories.Connection | CurlHelpCategories.Timeout),
        new("    --ssl", "Try enabling TLS", CurlHelpCategories.Tls | CurlHelpCategories.Imap | CurlHelpCategories.Pop3 | CurlHelpCategories.Smtp | CurlHelpCategories.Ldap),
        new("    --ssl-allow-beast", "Allow security flaw to improve interop", CurlHelpCategories.Tls),
        new("    --ssl-auto-client-cert", "Use auto client certificate (Schannel)", CurlHelpCategories.Tls),
        new("    --ssl-no-revoke", "Disable cert revocation checks (Schannel)", CurlHelpCategories.Tls),
        new("    --ssl-reqd", "Require SSL/TLS", CurlHelpCategories.Tls | CurlHelpCategories.Imap | CurlHelpCategories.Pop3 | CurlHelpCategories.Smtp | CurlHelpCategories.Ldap),
        new("    --ssl-revoke-best-effort", "Ignore missing cert CRL dist points", CurlHelpCategories.Tls),
        new("    --ssl-sessions <filename>", "Load/save SSL session tickets from/to this file", CurlHelpCategories.Tls),
        new("-2, --sslv2", "SSLv2", CurlHelpCategories.Deprecated),
        new("-3, --sslv3", "SSLv3", CurlHelpCategories.Deprecated),
        new("    --stderr <file>", "Where to redirect stderr", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --styled-output", "Enable styled output for HTTP headers", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --suppress-connect-headers", "Suppress proxy CONNECT response headers", CurlHelpCategories.Proxy),
        new("    --tcp-fastopen", "Use TCP Fast Open", CurlHelpCategories.Connection),
        new("    --tcp-nodelay", "Set TCP_NODELAY", CurlHelpCategories.Connection),
        new("-t, --telnet-option <opt=val>", "Set telnet option", CurlHelpCategories.Telnet),
        new("    --tftp-blksize <value>", "Set TFTP BLKSIZE option", CurlHelpCategories.Tftp),
        new("    --tftp-no-options", "Do not send any TFTP options", CurlHelpCategories.Tftp),
        new("-z, --time-cond <time>", "Transfer based on a time condition", CurlHelpCategories.Http | CurlHelpCategories.Ftp),
        new("    --tls-earlydata", "Allow use of TLSv1.3 early data (0RTT)", CurlHelpCategories.Tls),
        new("    --tls-max <VERSION>", "Maximum allowed TLS version", CurlHelpCategories.Tls),
        new("    --tls13-ciphers <list>", "TLS 1.3 cipher suites to use", CurlHelpCategories.Tls),
        new("    --tlsauthtype <type>", "TLS authentication type", CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --tlspassword <string>", "TLS password", CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("    --tlsuser <name>", "TLS username", CurlHelpCategories.Tls | CurlHelpCategories.Auth),
        new("-1, --tlsv1", "TLSv1.0 or greater", CurlHelpCategories.Tls),
        new("    --tlsv1.0", "TLSv1.0 or greater", CurlHelpCategories.Tls),
        new("    --tlsv1.1", "TLSv1.1 or greater", CurlHelpCategories.Tls),
        new("    --tlsv1.2", "TLSv1.2 or greater", CurlHelpCategories.Tls),
        new("    --tlsv1.3", "TLSv1.3 or greater", CurlHelpCategories.Tls),
        new("    --tr-encoding", "Request compressed transfer encoding", CurlHelpCategories.Http),
        new("    --trace <file>", "Write a debug trace to FILE", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --trace-ascii <file>", "Like --trace, but without hex output", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --trace-config <string>", "Details to log in trace/verbose output", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --trace-ids", "Transfer + connection ids in verbose output", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --trace-time", "Add time stamps to trace/verbose output", CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("    --unix-socket <path>", "Connect through this Unix domain socket", CurlHelpCategories.Connection),
        new("-T, --upload-file <file>", "Transfer local FILE to destination", CurlHelpCategories.Important | CurlHelpCategories.Upload),
        new("    --upload-flags <flags>", "IMAP upload behavior", CurlHelpCategories.Curl | CurlHelpCategories.Output),
        new("    --url <url/file>", "URL(s) to work with", CurlHelpCategories.Curl),
        new("    --url-query <data>", "Add a URL query part", CurlHelpCategories.Http | CurlHelpCategories.Post | CurlHelpCategories.Upload),
        new("-B, --use-ascii", "Use ASCII/text transfer", CurlHelpCategories.Ftp | CurlHelpCategories.Output | CurlHelpCategories.Ldap | CurlHelpCategories.Tftp),
        new("-u, --user <user:password>", "Server user and password", CurlHelpCategories.Important | CurlHelpCategories.Auth),
        new("-A, --user-agent <name>", "Send User-Agent <name> to server", CurlHelpCategories.Important | CurlHelpCategories.Http),
        new("    --variable <[%]name=text/@file>", "Set variable", CurlHelpCategories.Curl),
        new("-v, --verbose", "Make the operation more talkative", CurlHelpCategories.Important | CurlHelpCategories.Verbose | CurlHelpCategories.Global),
        new("-V, --version", "Show version number and quit", CurlHelpCategories.Important | CurlHelpCategories.Curl),
        new("    --vlan-priority <priority>", "Set VLAN priority", CurlHelpCategories.Connection),
        new("-w, --write-out <format>", "Output FORMAT after completion", CurlHelpCategories.Verbose),
        new("    --xattr", "Store metadata in extended file attributes", CurlHelpCategories.Output),
    ];
}

/// <summary>One row of curl's option help.</summary>
/// <param name="Option">The option as shown: <c>-d, --data &lt;data&gt;</c>, or four spaces before a long-only one.</param>
/// <param name="Description">The one-line description.</param>
/// <param name="Categories">The categories it is listed under.</param>
internal sealed record CurlHelpEntry(string Option, string Description, CurlHelpCategories Categories);
