using System.Collections.Frozen;
using System.Diagnostics.CodeAnalysis;

namespace Curl.Cli;

/// <summary>
/// Every long option name curl 8.21.0 accepts, in its order, with the letter that also names it and
/// whether it takes a <c>--no-</c> prefix: copied from the <c>aliases</c> array in curl's
/// <c>src/tool_getparam.c</c> at tag <c>curl-8_21_0</c>, as the release build compiles it: without the
/// <c>DEBUGBUILD</c> rows <c>test-duphandle</c> and <c>test-event</c> or the <c>USE_WATT32</c> row
/// <c>wdebug</c>, which the reference build refuses. It lists all of curl's other names, hidden ones
/// included, not only those <see cref="CommandLineOptionTable"/> parses, because <c>--help &lt;option&gt;</c>
/// looks names up in it (ADR-0069). The rows are sorted by name in ordinal order, as curl's binary search
/// needs.
/// </summary>
public static class CurlOptionAliasTable
{
    /// <summary>The letter curl stores for a name that has no single-letter form.</summary>
    public const char NoLetter = ' ';

    /// <summary>The rows, in curl's order.</summary>
    public static IReadOnlyList<CurlOptionAlias> Aliases { get; } =
    [
        new("abstract-unix-socket", ' ', CurlOptionNoPrefix.NotAccepted),
        new("alpn", ' ', CurlOptionNoPrefix.Documented),
        new("alt-svc", ' ', CurlOptionNoPrefix.NotAccepted),
        new("anyauth", ' ', CurlOptionNoPrefix.NotAccepted),
        new("append", 'a', CurlOptionNoPrefix.Accepted),
        new("aws-sigv4", ' ', CurlOptionNoPrefix.NotAccepted),
        new("basic", ' ', CurlOptionNoPrefix.Accepted),
        new("buffer", 'N', CurlOptionNoPrefix.Documented),
        new("ca-native", ' ', CurlOptionNoPrefix.Accepted),
        new("cacert", ' ', CurlOptionNoPrefix.NotAccepted),
        new("capath", ' ', CurlOptionNoPrefix.NotAccepted),
        new("cert", 'E', CurlOptionNoPrefix.NotAccepted),
        new("cert-status", ' ', CurlOptionNoPrefix.Accepted),
        new("cert-type", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ciphers", ' ', CurlOptionNoPrefix.NotAccepted),
        new("clobber", ' ', CurlOptionNoPrefix.Documented),
        new("compressed", ' ', CurlOptionNoPrefix.Accepted),
        new("compressed-ssh", ' ', CurlOptionNoPrefix.Accepted),
        new("config", 'K', CurlOptionNoPrefix.NotAccepted),
        new("connect-timeout", ' ', CurlOptionNoPrefix.NotAccepted),
        new("connect-to", ' ', CurlOptionNoPrefix.NotAccepted),
        new("continue-at", 'C', CurlOptionNoPrefix.NotAccepted),
        new("cookie", 'b', CurlOptionNoPrefix.NotAccepted),
        new("cookie-jar", 'c', CurlOptionNoPrefix.NotAccepted),
        new("create-dirs", ' ', CurlOptionNoPrefix.Accepted),
        new("create-file-mode", ' ', CurlOptionNoPrefix.NotAccepted),
        new("crlf", ' ', CurlOptionNoPrefix.Accepted),
        new("crlfile", ' ', CurlOptionNoPrefix.NotAccepted),
        new("curves", ' ', CurlOptionNoPrefix.NotAccepted),
        new("data", 'd', CurlOptionNoPrefix.NotAccepted),
        new("data-ascii", ' ', CurlOptionNoPrefix.NotAccepted),
        new("data-binary", ' ', CurlOptionNoPrefix.NotAccepted),
        new("data-raw", ' ', CurlOptionNoPrefix.NotAccepted),
        new("data-urlencode", ' ', CurlOptionNoPrefix.NotAccepted),
        new("delegation", ' ', CurlOptionNoPrefix.NotAccepted),
        new("digest", ' ', CurlOptionNoPrefix.Accepted),
        new("disable", 'q', CurlOptionNoPrefix.Accepted),
        new("disable-eprt", ' ', CurlOptionNoPrefix.Accepted),
        new("disable-epsv", ' ', CurlOptionNoPrefix.Accepted),
        new("disallow-username-in-url", ' ', CurlOptionNoPrefix.Accepted),
        new("dns-interface", ' ', CurlOptionNoPrefix.NotAccepted),
        new("dns-ipv4-addr", ' ', CurlOptionNoPrefix.NotAccepted),
        new("dns-ipv6-addr", ' ', CurlOptionNoPrefix.NotAccepted),
        new("dns-servers", ' ', CurlOptionNoPrefix.NotAccepted),
        new("doh-cert-status", ' ', CurlOptionNoPrefix.Accepted),
        new("doh-insecure", ' ', CurlOptionNoPrefix.Accepted),
        new("doh-url", ' ', CurlOptionNoPrefix.NotAccepted),
        new("dump-ca-embed", ' ', CurlOptionNoPrefix.NotAccepted),
        new("dump-header", 'D', CurlOptionNoPrefix.NotAccepted),
        new("ech", ' ', CurlOptionNoPrefix.NotAccepted),
        new("egd-file", ' ', CurlOptionNoPrefix.NotAccepted),
        new("engine", ' ', CurlOptionNoPrefix.NotAccepted),
        new("eprt", ' ', CurlOptionNoPrefix.Accepted),
        new("epsv", ' ', CurlOptionNoPrefix.Accepted),
        new("etag-compare", ' ', CurlOptionNoPrefix.NotAccepted),
        new("etag-save", ' ', CurlOptionNoPrefix.NotAccepted),
        new("expect100-timeout", ' ', CurlOptionNoPrefix.NotAccepted),
        new("fail", 'f', CurlOptionNoPrefix.Accepted),
        new("fail-early", ' ', CurlOptionNoPrefix.Accepted),
        new("fail-with-body", ' ', CurlOptionNoPrefix.Accepted),
        new("false-start", ' ', CurlOptionNoPrefix.Accepted),
        new("follow", ' ', CurlOptionNoPrefix.Accepted),
        new("form", 'F', CurlOptionNoPrefix.NotAccepted),
        new("form-escape", ' ', CurlOptionNoPrefix.Accepted),
        new("form-string", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-account", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-alternative-to-user", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-create-dirs", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-method", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-pasv", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-port", 'P', CurlOptionNoPrefix.NotAccepted),
        new("ftp-pret", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-skip-pasv-ip", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-ssl", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-ssl-ccc", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-ssl-ccc-mode", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ftp-ssl-control", ' ', CurlOptionNoPrefix.Accepted),
        new("ftp-ssl-reqd", ' ', CurlOptionNoPrefix.Accepted),
        new("get", 'G', CurlOptionNoPrefix.Accepted),
        new("globoff", 'g', CurlOptionNoPrefix.Accepted),
        new("happy-eyeballs-timeout-ms", ' ', CurlOptionNoPrefix.NotAccepted),
        new("haproxy-clientip", ' ', CurlOptionNoPrefix.NotAccepted),
        new("haproxy-protocol", ' ', CurlOptionNoPrefix.Accepted),
        new("head", 'I', CurlOptionNoPrefix.Accepted),
        new("header", 'H', CurlOptionNoPrefix.NotAccepted),
        new("help", 'h', CurlOptionNoPrefix.NotAccepted),
        new("hostpubmd5", ' ', CurlOptionNoPrefix.NotAccepted),
        new("hostpubsha256", ' ', CurlOptionNoPrefix.NotAccepted),
        new("hsts", ' ', CurlOptionNoPrefix.NotAccepted),
        new("http0.9", ' ', CurlOptionNoPrefix.Accepted),
        new("http1.0", '0', CurlOptionNoPrefix.NotAccepted),
        new("http1.1", ' ', CurlOptionNoPrefix.NotAccepted),
        new("http2", ' ', CurlOptionNoPrefix.NotAccepted),
        new("http2-prior-knowledge", ' ', CurlOptionNoPrefix.NotAccepted),
        new("http3", ' ', CurlOptionNoPrefix.NotAccepted),
        new("http3-only", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ignore-content-length", ' ', CurlOptionNoPrefix.Accepted),
        new("include", ' ', CurlOptionNoPrefix.Accepted),
        new("insecure", 'k', CurlOptionNoPrefix.Accepted),
        new("interface", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ip-tos", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ipfs-gateway", ' ', CurlOptionNoPrefix.NotAccepted),
        new("ipv4", '4', CurlOptionNoPrefix.NotAccepted),
        new("ipv6", '6', CurlOptionNoPrefix.NotAccepted),
        new("json", ' ', CurlOptionNoPrefix.NotAccepted),
        new("junk-session-cookies", 'j', CurlOptionNoPrefix.Accepted),
        new("keepalive", ' ', CurlOptionNoPrefix.Documented),
        new("keepalive-cnt", ' ', CurlOptionNoPrefix.NotAccepted),
        new("keepalive-time", ' ', CurlOptionNoPrefix.NotAccepted),
        new("key", ' ', CurlOptionNoPrefix.NotAccepted),
        new("key-type", ' ', CurlOptionNoPrefix.NotAccepted),
        new("knownhosts", ' ', CurlOptionNoPrefix.NotAccepted),
        new("krb", ' ', CurlOptionNoPrefix.NotAccepted),
        new("krb4", ' ', CurlOptionNoPrefix.NotAccepted),
        new("libcurl", ' ', CurlOptionNoPrefix.NotAccepted),
        new("limit-rate", ' ', CurlOptionNoPrefix.NotAccepted),
        new("list-only", 'l', CurlOptionNoPrefix.Accepted),
        new("local-port", ' ', CurlOptionNoPrefix.NotAccepted),
        new("location", 'L', CurlOptionNoPrefix.Accepted),
        new("location-trusted", ' ', CurlOptionNoPrefix.Accepted),
        new("login-options", ' ', CurlOptionNoPrefix.NotAccepted),
        new("mail-auth", ' ', CurlOptionNoPrefix.NotAccepted),
        new("mail-from", ' ', CurlOptionNoPrefix.NotAccepted),
        new("mail-rcpt", ' ', CurlOptionNoPrefix.NotAccepted),
        new("mail-rcpt-allowfails", ' ', CurlOptionNoPrefix.Accepted),
        new("manual", 'M', CurlOptionNoPrefix.Accepted),
        new("max-filesize", ' ', CurlOptionNoPrefix.NotAccepted),
        new("max-redirs", ' ', CurlOptionNoPrefix.NotAccepted),
        new("max-time", 'm', CurlOptionNoPrefix.NotAccepted),
        new("metalink", ' ', CurlOptionNoPrefix.Accepted),
        new("mptcp", ' ', CurlOptionNoPrefix.Accepted),
        new("negotiate", ' ', CurlOptionNoPrefix.Accepted),
        new("netrc", 'n', CurlOptionNoPrefix.Accepted),
        new("netrc-file", ' ', CurlOptionNoPrefix.NotAccepted),
        new("netrc-optional", ' ', CurlOptionNoPrefix.Accepted),
        new("next", ':', CurlOptionNoPrefix.NotAccepted),
        new("noproxy", ' ', CurlOptionNoPrefix.NotAccepted),
        new("npn", ' ', CurlOptionNoPrefix.Accepted),
        new("ntlm", ' ', CurlOptionNoPrefix.Accepted),
        new("ntlm-wb", ' ', CurlOptionNoPrefix.Accepted),
        new("oauth2-bearer", ' ', CurlOptionNoPrefix.NotAccepted),
        new("out-null", ' ', CurlOptionNoPrefix.Accepted),
        new("output", 'o', CurlOptionNoPrefix.NotAccepted),
        new("output-dir", ' ', CurlOptionNoPrefix.NotAccepted),
        new("parallel", 'Z', CurlOptionNoPrefix.Accepted),
        new("parallel-immediate", ' ', CurlOptionNoPrefix.Accepted),
        new("parallel-max", ' ', CurlOptionNoPrefix.NotAccepted),
        new("parallel-max-host", ' ', CurlOptionNoPrefix.NotAccepted),
        new("pass", ' ', CurlOptionNoPrefix.NotAccepted),
        new("path-as-is", ' ', CurlOptionNoPrefix.Accepted),
        new("pinnedpubkey", ' ', CurlOptionNoPrefix.NotAccepted),
        new("post301", ' ', CurlOptionNoPrefix.Accepted),
        new("post302", ' ', CurlOptionNoPrefix.Accepted),
        new("post303", ' ', CurlOptionNoPrefix.Accepted),
        new("preproxy", ' ', CurlOptionNoPrefix.NotAccepted),
        new("progress-bar", '#', CurlOptionNoPrefix.Accepted),
        new("progress-meter", ' ', CurlOptionNoPrefix.Documented),
        new("proto", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proto-default", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proto-redir", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy", 'x', CurlOptionNoPrefix.NotAccepted),
        new("proxy-anyauth", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-basic", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-ca-native", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-cacert", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-capath", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-cert", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-cert-type", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-ciphers", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-crlfile", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-digest", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-header", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-http2", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-http3", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-insecure", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-key", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-key-type", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-negotiate", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-ntlm", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-pass", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-pinnedpubkey", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-service-name", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-ssl-allow-beast", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-ssl-auto-client-cert", ' ', CurlOptionNoPrefix.Accepted),
        new("proxy-tls13-ciphers", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-tlsauthtype", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-tlspassword", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-tlsuser", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-tlsv1", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxy-user", 'U', CurlOptionNoPrefix.NotAccepted),
        new("proxy1.0", ' ', CurlOptionNoPrefix.NotAccepted),
        new("proxytunnel", 'p', CurlOptionNoPrefix.Accepted),
        new("pubkey", ' ', CurlOptionNoPrefix.NotAccepted),
        new("quote", 'Q', CurlOptionNoPrefix.NotAccepted),
        new("random-file", ' ', CurlOptionNoPrefix.NotAccepted),
        new("range", 'r', CurlOptionNoPrefix.NotAccepted),
        new("rate", ' ', CurlOptionNoPrefix.NotAccepted),
        new("raw", ' ', CurlOptionNoPrefix.Accepted),
        new("referer", 'e', CurlOptionNoPrefix.NotAccepted),
        new("remote-header-name", 'J', CurlOptionNoPrefix.Accepted),
        new("remote-name", 'O', CurlOptionNoPrefix.Accepted),
        new("remote-name-all", ' ', CurlOptionNoPrefix.Accepted),
        new("remote-time", 'R', CurlOptionNoPrefix.Accepted),
        new("remove-on-error", ' ', CurlOptionNoPrefix.Accepted),
        new("request", 'X', CurlOptionNoPrefix.NotAccepted),
        new("request-target", ' ', CurlOptionNoPrefix.NotAccepted),
        new("resolve", ' ', CurlOptionNoPrefix.NotAccepted),
        new("retry", ' ', CurlOptionNoPrefix.NotAccepted),
        new("retry-all-errors", ' ', CurlOptionNoPrefix.Accepted),
        new("retry-connrefused", ' ', CurlOptionNoPrefix.Accepted),
        new("retry-delay", ' ', CurlOptionNoPrefix.NotAccepted),
        new("retry-max-time", ' ', CurlOptionNoPrefix.NotAccepted),
        new("sasl-authzid", ' ', CurlOptionNoPrefix.NotAccepted),
        new("sasl-ir", ' ', CurlOptionNoPrefix.Accepted),
        new("service-name", ' ', CurlOptionNoPrefix.NotAccepted),
        new("sessionid", ' ', CurlOptionNoPrefix.Documented),
        new("show-error", 'S', CurlOptionNoPrefix.Accepted),
        new("show-headers", 'i', CurlOptionNoPrefix.Accepted),
        new("sigalgs", ' ', CurlOptionNoPrefix.NotAccepted),
        new("silent", 's', CurlOptionNoPrefix.Accepted),
        new("skip-existing", ' ', CurlOptionNoPrefix.Accepted),
        new("socks4", ' ', CurlOptionNoPrefix.NotAccepted),
        new("socks4a", ' ', CurlOptionNoPrefix.NotAccepted),
        new("socks5", ' ', CurlOptionNoPrefix.NotAccepted),
        new("socks5-basic", ' ', CurlOptionNoPrefix.Accepted),
        new("socks5-gssapi", ' ', CurlOptionNoPrefix.Accepted),
        new("socks5-gssapi-nec", ' ', CurlOptionNoPrefix.Accepted),
        new("socks5-gssapi-service", ' ', CurlOptionNoPrefix.NotAccepted),
        new("socks5-hostname", ' ', CurlOptionNoPrefix.NotAccepted),
        new("speed-limit", 'Y', CurlOptionNoPrefix.NotAccepted),
        new("speed-time", 'y', CurlOptionNoPrefix.NotAccepted),
        new("ssl", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-allow-beast", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-auto-client-cert", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-no-revoke", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-reqd", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-revoke-best-effort", ' ', CurlOptionNoPrefix.Accepted),
        new("ssl-sessions", ' ', CurlOptionNoPrefix.NotAccepted),
        new("sslv2", '2', CurlOptionNoPrefix.NotAccepted),
        new("sslv3", '3', CurlOptionNoPrefix.NotAccepted),
        new("stderr", ' ', CurlOptionNoPrefix.NotAccepted),
        new("styled-output", ' ', CurlOptionNoPrefix.Accepted),
        new("suppress-connect-headers", ' ', CurlOptionNoPrefix.Accepted),
        new("tcp-fastopen", ' ', CurlOptionNoPrefix.Accepted),
        new("tcp-nodelay", ' ', CurlOptionNoPrefix.Accepted),
        new("telnet-option", 't', CurlOptionNoPrefix.NotAccepted),
        new("tftp-blksize", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tftp-no-options", ' ', CurlOptionNoPrefix.Accepted),
        new("time-cond", 'z', CurlOptionNoPrefix.NotAccepted),
        new("tls-earlydata", ' ', CurlOptionNoPrefix.Accepted),
        new("tls-max", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tls13-ciphers", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsauthtype", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlspassword", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsuser", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsv1", '1', CurlOptionNoPrefix.NotAccepted),
        new("tlsv1.0", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsv1.1", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsv1.2", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tlsv1.3", ' ', CurlOptionNoPrefix.NotAccepted),
        new("tr-encoding", ' ', CurlOptionNoPrefix.Accepted),
        new("trace", ' ', CurlOptionNoPrefix.NotAccepted),
        new("trace-ascii", ' ', CurlOptionNoPrefix.NotAccepted),
        new("trace-config", ' ', CurlOptionNoPrefix.NotAccepted),
        new("trace-ids", ' ', CurlOptionNoPrefix.Accepted),
        new("trace-time", ' ', CurlOptionNoPrefix.Accepted),
        new("unix-socket", ' ', CurlOptionNoPrefix.NotAccepted),
        new("upload-file", 'T', CurlOptionNoPrefix.NotAccepted),
        new("upload-flags", ' ', CurlOptionNoPrefix.NotAccepted),
        new("url", ' ', CurlOptionNoPrefix.NotAccepted),
        new("url-query", ' ', CurlOptionNoPrefix.NotAccepted),
        new("use-ascii", 'B', CurlOptionNoPrefix.Accepted),
        new("user", 'u', CurlOptionNoPrefix.NotAccepted),
        new("user-agent", 'A', CurlOptionNoPrefix.NotAccepted),
        new("variable", ' ', CurlOptionNoPrefix.NotAccepted),
        new("verbose", 'v', CurlOptionNoPrefix.Accepted),
        new("version", 'V', CurlOptionNoPrefix.Accepted),
        new("vlan-priority", ' ', CurlOptionNoPrefix.NotAccepted),
        new("write-out", 'w', CurlOptionNoPrefix.NotAccepted),
        new("xattr", ' ', CurlOptionNoPrefix.Accepted),
    ];

    private static readonly FrozenDictionary<string, CurlOptionAlias> AliasesByName =
        Aliases.ToFrozenDictionary(alias => alias.Name, StringComparer.Ordinal);

    /// <summary>Finds the row named <paramref name="name"/>, case-sensitively.</summary>
    /// <param name="name">The long name without its leading <c>--</c>.</param>
    /// <param name="alias">The row found; <see langword="null"/> when there is none.</param>
    /// <returns><see langword="true"/> when curl 8.21.0 knows the name.</returns>
    public static bool TryFindName(string name, [NotNullWhen(true)] out CurlOptionAlias? alias) =>
        AliasesByName.TryGetValue(name, out alias);
}

/// <summary>Whether a long option takes a <c>--no-</c> prefix, and whether the manual names it that way.</summary>
public enum CurlOptionNoPrefix
{
    /// <summary>Not a boolean: <c>--no-&lt;name&gt;</c> is not an option (curl's <c>ARG_NONE</c>, <c>ARG_STRG</c> and the like).</summary>
    NotAccepted,

    /// <summary>A boolean the manual documents as <c>--&lt;name&gt;</c> (curl's <c>ARG_BOOL</c>).</summary>
    Accepted,

    /// <summary>A boolean the manual documents as <c>--no-&lt;name&gt;</c> (curl's <c>ARG_BOOL|ARG_NO</c>).</summary>
    Documented,
}

/// <summary>One of curl's long option names.</summary>
/// <param name="Name">The name without its leading <c>--</c>.</param>
/// <param name="Letter">The single letter that also names it, or <see cref="CurlOptionAliasTable.NoLetter"/>.</param>
/// <param name="NoPrefix">Whether it takes a <c>--no-</c> prefix, and whether the manual names it that way.</param>
public sealed record CurlOptionAlias(string Name, char Letter, CurlOptionNoPrefix NoPrefix);
