using System.Collections.Frozen;
using System.Text;
using Curl.Core;

namespace Curl.Cli;

/// <summary>
/// The C source file <c>--libcurl &lt;file&gt;</c> writes after the transfers, as curl 8.21.0 writes it: a
/// header comment, <c>#include &lt;curl/curl.h&gt;</c>, a <c>main</c> that calls <c>curl_easy_init</c>, then
/// for each transfer the <c>curl_easy_setopt</c> lines and the list of options that cannot be written as
/// source, and <c>curl_easy_perform</c>, then the cleanup and the end-of-sample comment (measured
/// 2026-10-01, BL-652 Notes). Every line ends in <c>\n</c>; the console layer writes the file in text mode
/// on Windows, as curl does, and standard output in binary.
/// </summary>
/// <remarks>
/// This is the skeleton: per transfer it writes the lines curl writes for a command line naming only URLs,
/// plus <c>CURLOPT_NOPROGRESS</c> for <c>-s</c> and <c>--no-progress-meter</c>. The lines other options add
/// are BL-653's and BL-654's.
/// </remarks>
public static class LibcurlSourceCode
{
    /// <summary>The longest string, in bytes, a <c>curl_easy_setopt</c> line quotes in full; a longer one is cut and ends in <c>...</c>.</summary>
    public const int LongestQuotedString = 2000;

    private static readonly FrozenDictionary<byte, string> NamedEscapes = new Dictionary<byte, string>
    {
        [(byte)'\n'] = "\\n",
        [(byte)'\r'] = "\\r",
        [(byte)'\t'] = "\\t",
        [(byte)'\\'] = "\\\\",
        [(byte)'"'] = "\\\"",
        [(byte)'?'] = "\\?",
    }.ToFrozenDictionary();

    private static readonly string[] HeaderLines =
    [
        "/********* Sample code generated by the curl command line tool **********",
        " * All curl_easy_setopt() options are documented at:",
        " * https://curl.se/libcurl/c/curl_easy_setopt.html",
        " ************************************************************************/",
        "#include <curl/curl.h>",
        "",
        "int main(int argc, char *argv[])",
        "{",
        "  CURLcode result;",
        "  CURL *curl;",
        "",
        "  curl = curl_easy_init();",
    ];

    private static readonly string[] UngeneratableOptionLines =
    [
        "",
        "  /* Here is a list of options the curl code used that cannot get generated",
        "     as source easily. You may choose to either not use them or implement",
        "     them yourself.",
        "",
        "  CURLOPT_WRITEDATA was set to an object pointer",
        "  CURLOPT_INTERLEAVEDATA was set to an object pointer",
        "  CURLOPT_WRITEFUNCTION was set to a function pointer",
        "  CURLOPT_READDATA was set to an object pointer",
        "  CURLOPT_READFUNCTION was set to a function pointer",
        "  CURLOPT_SEEKDATA was set to an object pointer",
        "  CURLOPT_SEEKFUNCTION was set to a function pointer",
        "  CURLOPT_HEADERFUNCTION was set to a function pointer",
        "  CURLOPT_HEADERDATA was set to an object pointer",
        "  CURLOPT_ERRORBUFFER was set to an object pointer",
        "  CURLOPT_STDERR was set to an object pointer",
        "",
        "  */",
        "",
        "  result = curl_easy_perform(curl);",
        "",
    ];

    private static readonly string[] FooterLines =
    [
        "  curl_easy_cleanup(curl);",
        "  curl = NULL;",
        "",
        "  return (int)result;",
        "}",
        "/**** End of sample code ****/",
    ];

    /// <summary>Builds the source file for the transfers performed, in the order they were performed.</summary>
    /// <param name="transfers">
    /// Each transfer's option group and its URL as the glob expanded it, before any scheme is guessed:
    /// <c>CURLOPT_URL</c> quotes it as given.
    /// </param>
    /// <returns>The source text, every line ending in <c>\n</c>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="transfers" /> is <see langword="null" />.</exception>
    public static string Generate(IReadOnlyList<(CommandLineOptions Options, string Url)> transfers)
    {
        ArgumentNullException.ThrowIfNull(transfers);

        List<string> lines = [.. HeaderLines];
        foreach ((CommandLineOptions options, string url) in transfers)
        {
            lines.AddRange(TransferLines(options, url));
            lines.AddRange(UngeneratableOptionLines);
        }

        lines.AddRange(FooterLines);
        return string.Concat(lines.Select(line => line + "\n"));
    }

    /// <summary>
    /// Quotes <paramref name="value" /> as a C string literal the way curl 8.21.0 does: its UTF-8 bytes,
    /// cut at <see cref="LongestQuotedString" /> with <c>...</c> added, <c>\n</c>, <c>\r</c>, <c>\t</c>,
    /// <c>\\</c>, <c>\"</c> and <c>\?</c> escaped, and any other byte outside printable ASCII as <c>\x</c>
    /// and two lowercase hex digits.
    /// </summary>
    /// <param name="value">The string.</param>
    /// <exception cref="ArgumentNullException"><paramref name="value" /> is <see langword="null" />.</exception>
    /// <returns>The literal, quotes included.</returns>
    public static string QuoteCString(string value)
    {
        ArgumentNullException.ThrowIfNull(value);

        byte[] bytes = Encoding.UTF8.GetBytes(value);
        StringBuilder literal = new("\"");
        foreach (byte character in bytes.AsSpan(0, Math.Min(bytes.Length, LongestQuotedString)))
        {
            literal.Append(EscapeByte(character));
        }

        return literal.Append(bytes.Length > LongestQuotedString ? "...\"" : "\"").ToString();
    }

    private static string EscapeByte(byte character) =>
        NamedEscapes.TryGetValue(character, out string? escape)
            ? escape
            : character is < 0x20 or > 0x7E ? $"\\x{character:x2}" : ((char)character).ToString();

    private static List<string> TransferLines(CommandLineOptions options, string url)
    {
        List<string> lines =
        [
            "  curl_easy_setopt(curl, CURLOPT_BUFFERSIZE, 102400L);",
            $"  curl_easy_setopt(curl, CURLOPT_URL, {QuoteCString(url)});",
        ];
        if (options.Silent || options.ProgressMeterOff)
        {
            lines.Add("  curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L);");
        }

        lines.Add("  curl_easy_setopt(curl, CURLOPT_USERAGENT, \"curl/8.21.0\");");
        lines.AddRange(SchemeLines(SchemeOf(options, url)));
        lines.Add("  curl_easy_setopt(curl, CURLOPT_SSLVERSION, (long)CURL_SSLVERSION_TLSv1_2);");
        lines.Add("  curl_easy_setopt(curl, CURLOPT_TCP_KEEPALIVE, 1L);");
        return lines;
    }

    /// <summary>The lines curl 8.21.0 writes for the scheme alone: the redirect limit for HTTP, the passive-IP skip for FTP.</summary>
    private static string[] SchemeLines(string scheme) => scheme switch
    {
        "http" or "https" => ["  curl_easy_setopt(curl, CURLOPT_MAXREDIRS, 50L);"],
        "ftp" or "ftps" => ["  curl_easy_setopt(curl, CURLOPT_FTP_SKIP_PASV_IP, 1L);"],
        _ => [],
    };

    /// <summary>
    /// The scheme curl 8.21.0's tool finds for <paramref name="url" />, lowercase: its own, the
    /// <c>--proto-default</c> one or the guessed one; empty for a URL holding a space or control
    /// character, which curl's URL parser refuses, so it sets none of the scheme's options.
    /// </summary>
    private static string SchemeOf(CommandLineOptions options, string url)
    {
        if (url.Any(character => character <= ' ' || character == '\x7F'))
        {
            return string.Empty;
        }

        string withScheme = UrlSchemeGuesser.AddScheme(url, options.DefaultProtocol);
        return withScheme[..withScheme.IndexOf(':', StringComparison.Ordinal)].ToLowerInvariant();
    }
}
