using System.Collections.Frozen;
using System.Text;
using Curl.Core;
using Curl.Protocol.Abstractions;

namespace Curl.Cli;

/// <summary>
/// The C source file <c>--libcurl &lt;file&gt;</c> writes after the transfers, as curl 8.21.0 writes it: a
/// header comment, <c>#include &lt;curl/curl.h&gt;</c>, a <c>main</c> that declares and fills the
/// <c>curl_slist</c> and <c>curl_mime</c> variables and calls <c>curl_easy_init</c>, then for each transfer
/// the <c>curl_easy_setopt</c> lines and the list of options that cannot be written as source, and
/// <c>curl_easy_perform</c>, then the cleanup, the variables freed, and the end-of-sample comment (measured
/// 2026-10-01, BL-652 and BL-653 Notes). Every line ends in <c>\n</c>; the console layer writes the file in
/// text mode on Windows, as curl does, and standard output in binary.
/// </summary>
/// <remarks>
/// Per transfer it writes curl's lines for the URL, <c>-s</c> and <c>--no-progress-meter</c>, the HTTP
/// options (<c>-X</c>, <c>-H</c>, the <c>-d</c> family and <c>--json</c>, <c>-F</c> and
/// <c>--form-string</c>, <c>-u</c>, <c>-L</c>, <c>-e</c>, <c>-A</c>, <c>-b</c>, <c>-c</c>,
/// <c>--compressed</c>, <c>-I</c>, <c>-R</c>, <c>-f</c>), the output options (<c>-o</c>, <c>-O</c> and
/// <c>-i</c> write nothing of their own) and the connection options (<c>--connect-timeout</c>, <c>-m</c>,
/// <c>--resolve</c>, <c>--connect-to</c>, <c>-4</c>, <c>-6</c>). A number curl's default already has, such
/// as a zero timeout, is not written, as curl does not write it. The proxy, TLS and authentication options'
/// lines (BL-654) are in <c>LibcurlSourceCode.ProxyTlsAndAuthentication.cs</c>, the transfer, redirect, speed and socket options' lines (BL-1106) in <c>LibcurlSourceCode.TransferOptions.cs</c>, the FTP, SSH, TFTP, telnet, mail, verbose, rate-limit and protocol options' lines (BL-1174) in <c>LibcurlSourceCode.ProtocolOptions.cs</c>, and
/// the lines that need the transfer's files - <c>-T</c>, <c>--etag-compare</c>, <c>-C -</c> and the SSH
/// known-hosts file (BL-1177) - in <c>LibcurlSourceCode.TransferFiles.cs</c>.
/// </remarks>
public static partial class LibcurlSourceCode
{
    /// <summary>The longest string, in bytes, a <c>curl_easy_setopt</c> line quotes in full; a longer one is cut and ends in <c>...</c>.</summary>
    public const int LongestQuotedString = 2000;

    private const string DefaultUserAgent = "curl/8.21.0";

    private static readonly FrozenDictionary<byte, string> NamedEscapes = new Dictionary<byte, string>
    {
        [(byte)'\n'] = "\\n",
        [(byte)'\r'] = "\\r",
        [(byte)'\t'] = "\\t",
        [(byte)'\\'] = "\\\\",
        [(byte)'"'] = "\\\"",
        [(byte)'?'] = "\\?",
    }.ToFrozenDictionary();

    private static readonly string[] HeaderLines =
    [
        "/********* Sample code generated by the curl command line tool **********",
        " * All curl_easy_setopt() options are documented at:",
        " * https://curl.se/libcurl/c/curl_easy_setopt.html",
        " ************************************************************************/",
        "#include <curl/curl.h>",
        "",
        "int main(int argc, char *argv[])",
        "{",
        "  CURLcode result;",
        "  CURL *curl;",
    ];

    private static readonly string[] UngeneratableOptionHeaderLines =
    [
        "",
        "  /* Here is a list of options the curl code used that cannot get generated",
        "     as source easily. You may choose to either not use them or implement",
        "     them yourself.",
        "",
    ];

    private static readonly string[] StandardUngeneratableOptionLines =
    [
        "  CURLOPT_WRITEDATA was set to an object pointer",
        "  CURLOPT_INTERLEAVEDATA was set to an object pointer",
        "  CURLOPT_WRITEFUNCTION was set to a function pointer",
        "  CURLOPT_READDATA was set to an object pointer",
        "  CURLOPT_READFUNCTION was set to a function pointer",
        "  CURLOPT_SEEKDATA was set to an object pointer",
        "  CURLOPT_SEEKFUNCTION was set to a function pointer",
        "  CURLOPT_HEADERFUNCTION was set to a function pointer",
        "  CURLOPT_HEADERDATA was set to an object pointer",
        "  CURLOPT_ERRORBUFFER was set to an object pointer",
        "  CURLOPT_STDERR was set to an object pointer",
    ];

    private static readonly string[] UngeneratableOptionFooterLines =
    [
        "",
        "  */",
        "",
        "  result = curl_easy_perform(curl);",
        "",
    ];

    private static readonly string[] FooterLines =
    [
        "",
        "  return (int)result;",
        "}",
        "/**** End of sample code ****/",
    ];

    /// <summary>Builds the source file for the transfers performed, in the order they were performed.</summary>
    /// <param name="transfers">
    /// Each transfer's option group and its URL as the glob expanded it, before any scheme is guessed:
    /// <c>CURLOPT_URL</c> quotes it as given.
    /// </param>
    /// <returns>The source text, every line ending in <c>\n</c>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="transfers" /> is <see langword="null" />.</exception>
    public static string Generate(IReadOnlyList<(CommandLineOptions Options, string Url)> transfers)
    {
        ArgumentNullException.ThrowIfNull(transfers);
        return Generate([.. transfers.Select(transfer => new LibcurlTransfer(transfer.Options, transfer.Url))]);
    }

    /// <summary>
    /// Builds the source file for the transfers performed, in the order they were performed, with what the
    /// console learnt about each transfer's files. A transfer whose <c>CURLOPT_SSH_KNOWNHOSTS</c> curl's tool
    /// fails to set (<see cref="LibcurlTransfer.SshKnownHostsFileMissing" />) ends the transfers there, without
    /// its list of options or <c>curl_easy_perform</c>, as curl 8.21.0 ends them with exit 2.
    /// </summary>
    /// <param name="transfers">Each transfer and its facts.</param>
    /// <returns>The source text, every line ending in <c>\n</c>.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="transfers" /> is <see langword="null" />.</exception>
    public static string Generate(IReadOnlyList<LibcurlTransfer> transfers)
    {
        ArgumentNullException.ThrowIfNull(transfers);

        LibcurlSourceVariables variables = new();
        List<string> body = [];
        foreach (LibcurlTransfer transfer in transfers)
        {
            List<string> transferLines = TransferLines(transfer, variables);
            int failed = transferLines.IndexOf(KnownHostsSetoptFailed);
            if (failed >= 0)
            {
                body.AddRange(transferLines.Take(failed));
                break;
            }

            body.AddRange(transferLines);
            body.AddRange(UngeneratableOptionLinesFor(transfer.Options));
        }

        List<string> lines = [.. HeaderLines, .. variables.Declarations];
        if (variables.Initialisations.Count > 0)
        {
            lines.Add(string.Empty);
            lines.AddRange(variables.Initialisations);
        }

        lines.AddRange(["", "  curl = curl_easy_init();", .. body, "  curl_easy_cleanup(curl);", "  curl = NULL;"]);
        lines.AddRange(variables.Cleanups);
        lines.AddRange(FooterLines);
        return string.Concat(lines.Select(line => line + "\n"));
    }

    /// <summary>
    /// Quotes <paramref name="value" /> as a C string literal the way curl 8.21.0 does: its UTF-8 bytes,
    /// quoted as <see cref="QuoteCBytes" /> quotes them.
    /// </summary>
    /// <param name="value">The string.</param>
    /// <exception cref="ArgumentNullException"><paramref name="value" /> is <see langword="null" />.</exception>
    /// <returns>The literal, quotes included.</returns>
    public static string QuoteCString(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return QuoteCBytes(Encoding.UTF8.GetBytes(value));
    }

    /// <summary>
    /// Quotes <paramref name="bytes" /> as a C string literal the way curl 8.21.0 does: cut at
    /// <see cref="LongestQuotedString" /> with <c>...</c> added, <c>\n</c>, <c>\r</c>, <c>\t</c>, <c>\\</c>,
    /// <c>\"</c> and <c>\?</c> escaped, and any other byte outside printable ASCII as <c>\x</c> and two
    /// lowercase hex digits, or as <c>\</c> and three octal digits when a hex digit follows it, so a C
    /// compiler does not read that digit as part of the escape.
    /// </summary>
    /// <param name="bytes">The bytes.</param>
    /// <returns>The literal, quotes included.</returns>
    public static string QuoteCBytes(ReadOnlySpan<byte> bytes)
    {
        int quoted = Math.Min(bytes.Length, LongestQuotedString);
        StringBuilder literal = new("\"");
        for (int index = 0; index < quoted; index++)
        {
            bool hexDigitFollows = index + 1 < bytes.Length && char.IsAsciiHexDigit((char)bytes[index + 1]);
            literal.Append(EscapeByte(bytes[index], hexDigitFollows));
        }

        return literal.Append(bytes.Length > LongestQuotedString ? "...\"" : "\"").ToString();
    }

    private static string EscapeByte(byte character, bool hexDigitFollows) =>
        NamedEscapes.TryGetValue(character, out string? escape)
            ? escape
            : character is >= 0x20 and <= 0x7E ? ((char)character).ToString()
            : hexDigitFollows ? "\\" + Convert.ToString(character, 8).PadLeft(3, '0')
            : $"\\x{character:x2}";

    private static string Setopt(string option, string value) => $"  curl_easy_setopt(curl, {option}, {value});";

    private static string SetoptOn(string option) => Setopt(option, "1L");

    private static string SetoptMilliseconds(string option, TimeSpan time) => Setopt(option, $"{(long)time.TotalMilliseconds}L");

    private static List<string> TransferLines(LibcurlTransfer transfer, LibcurlSourceVariables variables)
    {
        CommandLineOptions options = transfer.Options;
        string scheme = SchemeOf(options, transfer.Url);
        List<string> lines = [];
        AddIf(lines, options.Trace != TraceKind.None, SetoptOn("CURLOPT_VERBOSE"));
        lines.AddRange([BufferSizeLine(options), Setopt("CURLOPT_URL", QuoteCString(QueryUrl.Append(UploadUrlOf(transfer), options)))]);
        AddIf(lines, options.Silent || options.ProgressMeterOff, SetoptOn("CURLOPT_NOPROGRESS"));
        AddIf(lines, options.NoBody, SetoptOn("CURLOPT_NOBODY"));
        lines.AddRange(BearerAndProxyLines(options));
        AddIf(lines, options.FailMode == HttpFailMode.Fail, SetoptOn("CURLOPT_FAILONERROR"));
        lines.AddRange(TransferModeLines(options, transfer.UploadFile is not null));
        lines.AddRange(NetrcLines(options));
        AddIf(lines, options.Credentials is not null, () => Setopt("CURLOPT_USERPWD", QuoteCString($"{options.Credentials!.UserName}:{options.Credentials.Password}")));
        AddStringIf(lines, "CURLOPT_RANGE", options.Range);
        AddIf(lines, options.MaxTime > TimeSpan.Zero, () => SetoptMilliseconds("CURLOPT_TIMEOUT_MS", options.MaxTime!.Value));
        lines.AddRange(RequestBodyLines(options, variables));
        AddIf(lines, options.FormEscape, SetoptOn("CURLOPT_MIME_OPTIONS"));
        lines.AddRange(HttpAuthLines(options));
        AddStringListIf(lines, "CURLOPT_HTTPHEADER", [.. HttpHeaderLines(options), .. transfer.IfNoneMatchHeaders], variables);
        AddStringIf(lines, "CURLOPT_REFERER", options.Referer);
        lines.Add(Setopt("CURLOPT_USERAGENT", QuoteCString(options.UserAgent ?? DefaultUserAgent)));
        lines.AddRange(SchemeLines(options, scheme, variables));
        lines.AddRange(SpeedAndResumeLines(options, ResumeOffsetOf(transfer)));
        lines.AddRange(TlsLines(transfer, scheme));
        lines.AddRange(PathFileTimeAndConditionLines(options, variables));
        lines.AddRange(RequestAndConnectionLines(options, variables));
        lines.AddRange(SocksAndServiceLines(options));
        lines.AddRange(SocketLines(options));
        lines.AddRange(MailFileModeAndProtocolLines(options, variables));
        AddStringListIf(lines, "CURLOPT_RESOLVE", options.ResolveEntries, variables);
        AddStringListIf(lines, "CURLOPT_CONNECT_TO", options.ConnectToEntries, variables);
        lines.AddRange(DelegationAndSaslLines(options));
        lines.AddRange(UnixSocketAndUrlLines(options));
        lines.AddRange(UploadFlagLines(options));
        AddIf(lines, transfer.UploadFileSize > 0, () => Setopt("CURLOPT_INFILESIZE_LARGE", $"(curl_off_t){transfer.UploadFileSize}"));
        return lines;
    }

    private static void AddIf(List<string> lines, bool condition, string line) => AddIf(lines, condition, () => line);

    private static void AddIf(List<string> lines, bool condition, Func<string> line)
    {
        if (condition)
        {
            lines.Add(line());
        }
    }

    private static void AddStringListIf(List<string> lines, string option, IReadOnlyList<string> items, LibcurlSourceVariables variables) =>
        AddIf(lines, items.Count > 0, () => Setopt(option, variables.AddStringList(items)));

    /// <summary>
    /// The request body's lines: the <c>-F</c> form as <c>curl_mime</c> calls and <c>CURLOPT_MIMEPOST</c>, or
    /// the <c>-d</c> family's bytes as <c>CURLOPT_POSTFIELDS</c> and, when not empty, their size; nothing
    /// when there is neither, or when <c>-G</c> moves the data into the URL.
    /// </summary>
    private static List<string> RequestBodyLines(CommandLineOptions options, LibcurlSourceVariables variables)
    {
        if (options.FormParts.Count > 0)
        {
            List<string> lines = MimeLines(options.FormParts, variables, out int mime);
            lines.Add(Setopt("CURLOPT_MIMEPOST", $"mime{mime}"));
            return lines;
        }

        if (options.PostData is not { } data || options.DataInQuery)
        {
            return [];
        }

        List<string> postLines = [Setopt("CURLOPT_POSTFIELDS", QuoteCBytes(data.Span))];
        AddIf(postLines, data.Length > 0, () => Setopt("CURLOPT_POSTFIELDSIZE_LARGE", $"(curl_off_t){data.Length}"));
        return postLines;
    }

    /// <summary>The <c>-H</c> lines in order, then the <c>--json</c> ones a <c>-H</c> did not already give.</summary>
    private static List<string> HttpHeaderLines(CommandLineOptions options)
    {
        List<string> headers = [.. options.Headers];
        if (options.SendsJson)
        {
            AddJsonHeader(headers, "Content-Type");
            AddJsonHeader(headers, "Accept");
        }

        return headers;
    }

    private static void AddJsonHeader(List<string> headers, string name) =>
        AddIf(headers, !headers.Any(header => header.StartsWith(name + ":", StringComparison.OrdinalIgnoreCase)), $"{name}: application/json");

    /// <summary>Makes the next <c>mime</c> variable and writes the lines that build <paramref name="parts" /> into it.</summary>
    private static List<string> MimeLines(IReadOnlyList<FormPartSpecification> parts, LibcurlSourceVariables variables, out int mime)
    {
        int number = variables.AddMime();
        List<string> lines = [$"  mime{number} = curl_mime_init(curl);"];
        foreach (FormPartSpecification part in parts)
        {
            lines.Add($"  part{number} = curl_mime_addpart(mime{number});");
            lines.AddRange(PartLines(part, number, variables));
        }

        mime = number;
        return lines;
    }

    /// <summary>One part's lines, in curl's order: its content, encoder, file name, name, type and headers.</summary>
    private static List<string> PartLines(FormPartSpecification part, int number, LibcurlSourceVariables variables)
    {
        string partVariable = $"part{number}";
        List<string> lines = PartContentLines(part, partVariable, variables);
        AddIf(lines, part.Encoder is not null, () => $"  curl_mime_encoder({partVariable}, {QuoteCString(part.Encoder!)});");
        string? fileName = PartFileNameArgument(part);
        AddIf(lines, fileName is not null, () => $"  curl_mime_filename({partVariable}, {fileName});");
        AddIf(lines, part.Name is not null, () => $"  curl_mime_name({partVariable}, {QuoteCString(part.Name!)});");
        AddIf(lines, part.ContentType is not null, () => $"  curl_mime_type({partVariable}, {QuoteCString(part.ContentType!)});");
        if (part.Headers.Count > 0)
        {
            string list = variables.AddStringList(part.Headers);
            lines.AddRange([$"  curl_mime_headers({partVariable}, {list}, 1);", $"  {list} = NULL;"]);
        }

        return lines;
    }

    private static List<string> PartContentLines(FormPartSpecification part, string partVariable, LibcurlSourceVariables variables)
    {
        switch (part.Kind)
        {
            case FormPartKind.Text:
                return [$"  curl_mime_data({partVariable}, {QuoteCString(part.Content)}, CURL_ZERO_TERMINATED);"];
            case FormPartKind.Multipart:
                List<string> lines = MimeLines(part.Parts, variables, out int inner);
                lines.AddRange([$"  curl_mime_subparts({partVariable}, mime{inner});", $"  mime{inner} = NULL;"]);
                return lines;
            default:
                return part.Content == "-"
                    ?
                    [
                        $"  curl_mime_data_cb({partVariable}, -1, (curl_read_callback)fread, \\",
                        "                    (curl_seek_callback)fseek, NULL, stdin);",
                    ]
                    : [$"  curl_mime_filedata({partVariable}, {QuoteCString(part.Content)});"];
        }
    }

    /// <summary>
    /// The <c>curl_mime_filename</c> argument curl 8.21.0 writes for <paramref name="part" />, or
    /// <see langword="null" /> for none: <c>&lt;file</c> clears the name <c>curl_mime_filedata</c> set, as
    /// <c>NULL</c>, and drops any <c>;filename=</c>; <c>&lt;-</c> writes none; <c>@-</c> is named <c>-</c>
    /// unless <c>;filename=</c> names it; any other part writes its <c>;filename=</c>.
    /// </summary>
    private static string? PartFileNameArgument(FormPartSpecification part) =>
        part.Content == "-" && part.Kind is FormPartKind.FileContent or FormPartKind.FileUpload
            ? StandardInputFileNameArgument(part)
            : part.Kind == FormPartKind.FileContent ? "NULL" : QuotedOrNull(part.FileName);

    private static string? StandardInputFileNameArgument(FormPartSpecification part) =>
        part.Kind == FormPartKind.FileContent ? null : QuoteCString(part.FileName ?? "-");

    private static string? QuotedOrNull(string? text) => text is null ? null : QuoteCString(text);

    /// <summary>
    /// The lines curl 8.21.0 writes for the scheme: for HTTP the redirect, <c>--compressed</c> and cookie
    /// options and the redirect limit, which it writes for no other scheme; for FTP the passive-IP skip.
    /// </summary>
    private static List<string> SchemeLines(CommandLineOptions options, string scheme, LibcurlSourceVariables variables) => scheme switch
    {
        "http" or "https" => HttpLines(options, scheme, variables),
        "ftp" or "ftps" => FtpLines(options),
        _ => [],
    };

    private static List<string> HttpLines(CommandLineOptions options, string scheme, LibcurlSourceVariables variables)
    {
        List<string> lines = [];
        AddIf(lines, options.FollowRedirects, () => FollowLocationLine(options));
        AddIf(lines, options.SendCredentialsToRedirectHosts, SetoptOn("CURLOPT_UNRESTRICTED_AUTH"));
        AddStringIf(lines, "CURLOPT_AWS_SIGV4", options.AwsSigV4);
        AddIf(lines, options.AutoReferer, SetoptOn("CURLOPT_AUTOREFERER"));
        AddStringListIf(lines, "CURLOPT_PROXYHEADER", options.ProxyHeaders, variables);
        lines.Add(Setopt("CURLOPT_MAXREDIRS", $"{options.MaxRedirects}L"));
        lines.AddRange(HttpVersionAndPostRedirectLines(options));
        AddIf(lines, options.Compressed, Setopt("CURLOPT_ACCEPT_ENCODING", "\"\""));
        lines.AddRange(HttpTransferLines(options));
        string[] cookieStrings = [.. options.Cookies.Where(cookie => cookie.IsCookieString).Select(cookie => cookie.Value)];
        AddIf(lines, cookieStrings.Length > 0, () => Setopt("CURLOPT_COOKIE", QuoteCString(string.Join("; ", cookieStrings))));
        lines.AddRange(options.Cookies.Where(cookie => !cookie.IsCookieString).Select(cookie => Setopt("CURLOPT_COOKIEFILE", QuoteCString(cookie.Value))));
        AddStringIf(lines, "CURLOPT_COOKIEJAR", options.CookieJar);
        AddIf(lines, options.JunkSessionCookies, SetoptOn("CURLOPT_COOKIESESSION"));
        AddIf(lines, SeparatesProxyHeaders(options, scheme), SetoptOn("CURLOPT_HEADEROPT"));
        return lines;
    }

    /// <summary>
    /// The scheme curl 8.21.0's tool finds for <paramref name="url" />, lowercase: its own, the
    /// <c>--proto-default</c> one or the guessed one; empty for a URL holding a space or control
    /// character, which curl's URL parser refuses, so it sets none of the scheme's options.
    /// </summary>
    private static string SchemeOf(CommandLineOptions options, string url)
    {
        if (url.Any(character => character <= ' ' || character == '\x7F'))
        {
            return string.Empty;
        }

        string withScheme = UrlSchemeGuesser.AddScheme(url, options.DefaultProtocol);
        return withScheme[..withScheme.IndexOf(':', StringComparison.Ordinal)].ToLowerInvariant();
    }
}
