using System.Text;

using Curl.Core;
using Curl.Protocol.Abstractions;
using Curl.Testing;

namespace Curl.Console;

/// <summary>
/// Pins <c>-b</c>, <c>-c</c> and <c>-j</c> end to end through the production handler set over a
/// <see cref="ScriptedConnector" /> and an <see cref="InMemoryFileSystem" />. Every expected byte
/// was measured on 2026-09-26 with curl 8.21.0 (mingw, Schannel) against
/// <c>Record-CurlExchange.ps1</c> answering <c>HTTP/1.1 200 OK</c>, <c>Set-Cookie: got=g1</c>,
/// <c>Content-Length: 0</c>, with <c>in.txt</c> holding the session cookie <c>sess=s1</c> and the
/// persistent cookie <c>keep=k1</c> for <c>127.0.0.1</c> (BL-237 Notes).
/// </summary>
[TestClass]
public sealed class CurlCommandRunnerCookieTests
{
    private const string Url = "http://127.0.0.1:18231/";

    private const string Head = "Host: 127.0.0.1:18231\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n";

    private const string SetsCookie = "HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 0\r\n\r\n";

    private const string RedirectSetsCookie =
        "HTTP/1.1 302 Found\r\nLocation: /2\r\nSet-Cookie: got=g1\r\nContent-Length: 0\r\n\r\n";

    private const string CookieFile =
        "# Netscape HTTP Cookie File\n127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\ts1\n127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tkeep\tk1\n";

    private const string StandardInputCookies =
        "127.0.0.1\tFALSE\t/\tFALSE\t0\tname\tvalue\n127.0.0.1\tFALSE\t/\tFALSE\t0\tother\ttwo\n";

    private const string JarHeader =
        "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";

    private const string GotLine = "127.0.0.1\tFALSE\t/\tFALSE\t0\tgot\tg1\n";

    private const string KeepLine = "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tkeep\tk1\n";

    private const string SessLine = "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\ts1\n";

    private readonly InMemoryFileSystem fileSystem = new();

    private readonly MemoryStream standardOutput = new();

    private readonly MemoryStream standardError = new();

    public TestContext TestContext { get; set; } = null!;

    private TestDiagnostics Diagnostics => TestDiagnostics.For(TestContext);

    private string StandardOutputText => Encoding.Latin1.GetString(standardOutput.ToArray());

    [TestInitialize]
    public void AddCookieFile() => fileSystem.ExistingContent["in.txt"] = Encoding.Latin1.GetBytes(CookieFile);

    [TestMethod]
    [DataRow(new[] { "-b", "in.txt" }, "Cookie: keep=k1; sess=s1\r\n", DisplayName = "-b file")]
    [DataRow(new[] { "-b", "in.txt", "-j" }, "Cookie: keep=k1\r\n", DisplayName = "-b file -j")]
    [DataRow(new[] { "-b", "a=1; b=2" }, "Cookie: a=1; b=2\r\n", DisplayName = "-b string")]
    [DataRow(new[] { "-b", "missing.txt" }, "", DisplayName = "-b missing file")]
    [DataRow(new[] { "-c", "jar.txt" }, "", DisplayName = "-c alone")]
    public async Task RunAsync_CookieOption_SendsTheCookieHeaderCurlSends(string[] arguments, string expectedCookieHeader)
    {
        fileSystem.UnreadablePaths.Add("missing.txt");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", .. arguments, Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("request bytes", $"GET / HTTP/1.1\r\n{Head}{expectedCookieHeader}\r\n", Latin1(server.Written));
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual($"GET / HTTP/1.1\r\n{Head}{expectedCookieHeader}\r\n", Latin1(server.Written));
    }

    /// <summary>
    /// Measured 2026-09-27 with <c>Record-CurlExchange.ps1 -StandardInput</c> holding
    /// <see cref="StandardInputCookies" /> (BL-316 Notes).
    /// </summary>
    [TestMethod]
    [DataRow(new[] { "-b", "-" }, "Cookie: other=two; name=value\r\n", DisplayName = "-b -")]
    [DataRow(new[] { "-b", "-", "-b", "s=1" }, "Cookie: other=two; name=value; s=1\r\n", DisplayName = "-b - -b s=1")]
    [DataRow(new[] { "-b", "-", "-b", "-" }, "Cookie: other=two; name=value\r\n", DisplayName = "-b - -b -")]
    public async Task RunAsync_CookieFileOnStandardInput_SendsItsCookies(string[] arguments, string expectedCookieHeader)
    {
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", .. arguments, "http://127.0.0.1:18316/x"], StandardInputCookies);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request starts with the expected cookie header",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n{expectedCookieHeader}\r\n",
                StringComparison.Ordinal));
        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            $"GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n{expectedCookieHeader}\r\n",
            Latin1(server.Written));
    }

    /// <summary>
    /// curl 8.21.0 reads <c>-b -</c> only at the first HTTP transfer, so a <c>telnet</c> transfer
    /// before it sends standard input and the HTTP one sends no cookie (measured 2026-09-27, BL-316 Notes).
    /// </summary>
    [TestMethod]
    public async Task RunAsync_CookieFileOnStandardInputAfterATelnetTransfer_LeavesStandardInputToTelnet()
    {
        ScriptedConnector server = Serve(string.Empty, SetsCookie);

        int exitCode = await RunAsync(
            server,
            ["-s", "-b", "-", "telnet://127.0.0.1:18316", "http://127.0.0.1:18316/x"],
            StandardInputCookies);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request starts with standard input then the HTTP request",
            true,
            Latin1(server.Written).StartsWith(
                StandardInputCookies + "GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n\r\n",
                StringComparison.Ordinal));
        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            StandardInputCookies + "GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n\r\n",
            Latin1(server.Written));
    }

    /// <summary>
    /// Measured 2026-09-27 with <c>curl -s -v -b cf.txt -c - http://127.0.0.1:&lt;port&gt;/</c>: each refused
    /// <c>Set-Cookie:</c> line of the file prints its line before the connection's, and the
    /// accepted one is sent (BL-461 Notes). The scripted connector prints no <c>Trying</c> lines.
    /// </summary>
    [TestMethod]
    public async Task RunAsync_VerboseCookieFileWithRefusedSetCookieLines_PrintsCurlsRefusalLines()
    {
        fileSystem.ExistingContent["cf.txt"] =
            Encoding.Latin1.GetBytes("Set-Cookie: g=v; X=\u0001\nSet-Cookie: c\nSet-Cookie: s=v; Secure\n");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-v", "-b", "cf.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "stderr starts with the refusal lines",
            true,
            Latin1(standardError.ToArray()).StartsWith(
                "* invalid octets in value, cookie dropped\r\n* invalid cookie, dropped\r\n* using HTTP/1.x\r\n",
                StringComparison.Ordinal));
        Diagnostics.Diff("request bytes", $"GET / HTTP/1.1\r\n{Head}Cookie: s=v\r\n\r\n", Latin1(server.Written));
        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            "* invalid octets in value, cookie dropped\r\n* invalid cookie, dropped\r\n* using HTTP/1.x\r\n",
            Latin1(standardError.ToArray()));
        Assert.AreEqual($"GET / HTTP/1.1\r\n{Head}Cookie: s=v\r\n\r\n", Latin1(server.Written));
    }

    /// <summary>
    /// curl 8.21.0 sends at most 150 cookies and, under <c>-v</c>, says so while it builds the request,
    /// before the request's header lines (<c>lib/cookie.c</c>, BL-1108): a <c>-b</c> file holding 151
    /// cookies for the host prints the line and sends 150 of them.
    /// </summary>
    [TestMethod]
    public async Task RunAsync_VerboseCookieFileWithMoreThanTheMostCookiesSent_PrintsCurlsLimitLineBeforeTheRequest()
    {
        StringBuilder cookieFile = new();
        foreach (int number in Enumerable.Range(1, 151))
        {
            cookieFile.Append(System.Globalization.CultureInfo.InvariantCulture, $"127.0.0.1\tFALSE\t/\tFALSE\t0\tk{number}\tv\n");
        }

        fileSystem.ExistingContent["many.txt"] = Encoding.Latin1.GetBytes(cookieFile.ToString());
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-v", "-b", "many.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "stderr has the max-cookies line before the request",
            true,
            Latin1(standardError.ToArray()).Contains(
                "* using HTTP/1.x\r\n* Included max number of cookies (150) in request!\r\n> GET / HTTP/1.1\r\r\n",
                StringComparison.Ordinal));
        Diagnostics.Assert("cookies sent", 150, SentCookies(server).Length);
        Assert.AreEqual(0, exitCode);
        StringAssert.Contains(
            Latin1(standardError.ToArray()),
            "* using HTTP/1.x\r\n* Included max number of cookies (150) in request!\r\n> GET / HTTP/1.1\r\r\n");
        Assert.HasCount(150, SentCookies(server));
    }

    /// <summary>
    /// Measured 2026-10-01 with <c>curl -s -v -b big.txt http://127.0.0.1:&lt;port&gt;/</c>, <c>big.txt</c>
    /// holding the cookies <c>aaa</c>, <c>bb</c> and <c>c</c> of 4000 characters each for the host: curl
    /// 8.21.0 sends <c>aaa</c> and <c>bb</c>, leaves <c>c</c> out because the header would pass 8183
    /// characters, and prints the line between <c>* using HTTP/1.x</c> and <c>&gt; GET</c> (BL-1136 Notes).
    /// </summary>
    [TestMethod]
    public async Task RunAsync_VerboseCookieFileLongerThanTheLongestCookieHeader_PrintsCurlsRestrictedLineBeforeTheRequest()
    {
        string value = new('x', 4000);
        fileSystem.ExistingContent["big.txt"] = Encoding.Latin1.GetBytes(
            $"127.0.0.1\tFALSE\t/\tFALSE\t0\taaa\t{value}\n127.0.0.1\tFALSE\t/\tFALSE\t0\tbb\t{value}\n127.0.0.1\tFALSE\t/\tFALSE\t0\tc\t{value}\n");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-v", "-b", "big.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "stderr has the restricted line before the request",
            true,
            Latin1(standardError.ToArray()).Contains(
                "* using HTTP/1.x\r\n* Restricted outgoing cookies due to header size, 'c' not sent\r\n> GET / HTTP/1.1\r\r\n",
                StringComparison.Ordinal));
        Diagnostics.Assert("cookies sent", string.Join("; ", $"aaa={value}", $"bb={value}"), string.Join("; ", SentCookies(server)));
        Assert.AreEqual(0, exitCode);
        StringAssert.Contains(
            Latin1(standardError.ToArray()),
            "* using HTTP/1.x\r\n* Restricted outgoing cookies due to header size, 'c' not sent\r\n> GET / HTTP/1.1\r\r\n");
        CollectionAssert.AreEqual(new[] { $"aaa={value}", $"bb={value}" }, SentCookies(server));
    }

    private static string[] SentCookies(ScriptedConnector server) =>
        Latin1(server.Written).Split("\r\n").Single(line => line.StartsWith("Cookie: ", StringComparison.Ordinal))["Cookie: ".Length..].Split("; ");

    /// <summary>
    /// Measured 2026-09-27 with <c>curl -s -v -b sub\missing.txt http://127.0.0.1:&lt;port&gt;/</c>: the warning is
    /// the first line on standard error, with the path as given, and the transfer goes on to exit 0 (BL-487 Notes).
    /// </summary>
    [TestMethod]
    public async Task RunAsync_VerboseCookieFileThatCannotBeOpened_PrintsCurlsWarningFirst()
    {
        fileSystem.UnreadablePaths.Add("sub\\missing.txt");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-v", "-b", "sub\\missing.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "stderr starts with the warning",
            true,
            Latin1(standardError.ToArray()).StartsWith(
                "* WARNING: failed to open cookie file \"sub\\missing.txt\"\r\n* using HTTP/1.x\r\n",
                StringComparison.Ordinal));
        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            "* WARNING: failed to open cookie file \"sub\\missing.txt\"\r\n* using HTTP/1.x\r\n",
            Latin1(standardError.ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarFile_WritesTheReceivedCookieInThePlatformsLineEndings()
    {
        int exitCode = await RunAsync(Serve(SetsCookie), ["-s", "-c", "jar.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("jar.txt", Lf(NativeLines(JarHeader + GotLine)), Lf(Latin1(fileSystem.Written["jar.txt"].ToArray())));
        Assert.AreEqual(NativeLines(JarHeader + GotLine), Latin1(fileSystem.Written["jar.txt"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieFileJunkedAndJar_WritesTheReceivedAndPersistentCookiesNewestFirst()
    {
        int exitCode = await RunAsync(Serve(SetsCookie), ["-s", "-b", "in.txt", "-j", "-c", "jarj.txt", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("jarj.txt", Lf(NativeLines(JarHeader + GotLine + KeepLine)), Lf(Latin1(fileSystem.Written["jarj.txt"].ToArray())));
        Assert.AreEqual(NativeLines(JarHeader + GotLine + KeepLine), Latin1(fileSystem.Written["jarj.txt"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputAfterABodyThere_WritesTheJarWithLineFeeds()
    {
        int exitCode = await RunAsync(Serve(SetsCookie), ["-s", "-b", "in.txt", "-c", "-", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", JarHeader + GotLine + KeepLine + SessLine, StandardOutputText);
        Assert.AreEqual(JarHeader + GotLine + KeepLine + SessLine, StandardOutputText);
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputWithTheBodyInAFile_WritesTheJarInTextMode()
    {
        int exitCode = await RunAsync(
            Serve("HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 5\r\n\r\nbody\n"),
            ["-s", "-c", "-", "-o", "out.bin", Url]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", (JarHeader + GotLine).Replace("\n", "\r\n", StringComparison.Ordinal), StandardOutputText);
        Diagnostics.Diff("out.bin", "body\n", Latin1(fileSystem.Written["out.bin"].ToArray()));
        Assert.AreEqual((JarHeader + GotLine).Replace("\n", "\r\n", StringComparison.Ordinal), StandardOutputText);
        Assert.AreEqual("body\n", Latin1(fileSystem.Written["out.bin"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputForTwoUrls_WritesTheJarAfterEachTransfersWriteOut()
    {
        const string Response = "HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 5\r\n\r\nbody\n";
        ScriptedConnector server = Serve(Response, Response);

        int exitCode = await RunAsync(server, ["-s", "-c", "-", "-w", "[w]\\n", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        string jar = JarHeader + GotLine;
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", $"body\n[w]\n{jar}body\n[w]\n{jar}", StandardOutputText);
        Diagnostics.Assert(
            "request bytes start with both requests",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.AreEqual($"body\n[w]\n{jar}body\n[w]\n{jar}", StandardOutputText);
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieStringOnlyForTwoUrls_NeverSendsTheReceivedCookie()
    {
        ScriptedConnector server = Serve(SetsCookie, SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-b", "a=1", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request bytes start with both requests",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_EmptyCookieFileNameForTwoUrls_SendsTheReceivedCookieOnTheSecond()
    {
        ScriptedConnector server = Serve(SetsCookie, SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-b", "", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request bytes start with both requests",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_FollowedRedirectWithEmptyCookieFileName_SendsTheCookieSetByTheFirstHop()
    {
        ScriptedConnector server = Serve(RedirectSetsCookie, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n");

        int exitCode = await RunAsync(server, ["-s", "-L", "-b", "", "http://127.0.0.1:18231/1"]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request bytes start with both hops",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_FollowedRedirectWithCookieStringOnly_NeverSendsTheCookieSetByTheFirstHop()
    {
        ScriptedConnector server = Serve(RedirectSetsCookie, "HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n");

        int exitCode = await RunAsync(server, ["-s", "-L", "-b", "a=1", "http://127.0.0.1:18231/1"]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request bytes start with both hops",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieFileAndStringForTwoUrls_SendsTheReceivedCookieBeforeTheString()
    {
        ScriptedConnector server = Serve(SetsCookie, SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-b", "in.txt", "-b", "a=1", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert(
            "request bytes start with both requests",
            true,
            Latin1(server.Written).StartsWith(
                $"GET /1 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; a=1\r\n\r\n"
                + $"GET /2 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; got=g1; a=1\r\n\r\n",
                StringComparison.Ordinal));
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; a=1\r\n\r\n"
            + $"GET /2 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; got=g1; a=1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarAndTheConnectionFails_WritesTheEmptyJar()
    {
        int exitCode = await RunAsync(
            new RecordingConnector(CurlExitCode.CouldntConnect, "Failed to connect"),
            ["-s", "-c", "jarfail.txt", "http://127.0.0.1:1/"]);

        Diagnostics.Assert("exit code", 7, exitCode);
        Diagnostics.Diff("jarfail.txt", Lf(NativeLines(JarHeader)), Lf(Latin1(fileSystem.Written["jarfail.txt"].ToArray())));
        Assert.AreEqual(7, exitCode);
        Assert.AreEqual(NativeLines(JarHeader), Latin1(fileSystem.Written["jarfail.txt"].ToArray()));
    }

    [TestMethod]
    [DataRow("dict://127.0.0.1:1/x", DisplayName = "dict")]
    [DataRow("dict://exa mple.com/x", DisplayName = "malformed")]
    public async Task RunAsync_CookieJarAndAUrlThatIsNotHttp_WritesNoJar(string url)
    {
        int exitCode = await RunAsync(Serve(), ["-s", "-b", "in.txt", "-c", "j4.txt", url]);

        Diagnostics.Act("exit code seen by the test", exitCode);
        Diagnostics.Assert("jar written", false, fileSystem.Written.ContainsKey("j4.txt"));
        Assert.IsFalse(fileSystem.Written.ContainsKey("j4.txt"));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnAFailedStandardOutput_WritesNothingAndReportsTheWriteFailure()
    {
        using FailingWriteStream closed = new();
        string[] arguments = ["-s", "-c", "-", Url];
        Diagnostics.Arrange("command line", string.Join(" ", arguments));
        Diagnostics.Arrange("standard output", "a stream whose every write fails");

        int exitCode;
        using (Diagnostics.Phase("run"))
        {
            exitCode = await new CurlCommandRunner(
                    options => CreateTransferDispatch(Serve("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nbody\n"), options),
                    fileSystem,
                    fileSystem,
                    closed,
                    new MemoryStream(),
                    new MemoryStream(),
                    runsOnWindows: true)
                .RunAsync(arguments);
        }

        Diagnostics.Act("exit code", exitCode);
        Diagnostics.Assert("exit code", 23, exitCode);
        Assert.AreEqual(23, exitCode);
    }

    /// <summary>A connector whose connections answer <paramref name="responses" /> in turn.</summary>
    private ScriptedConnector Serve(params string[] responses)
    {
        Diagnostics.Arrange(
            "scripted responses",
            responses.Length == 0 ? "<none>" : string.Join(" | ", responses.Select(response => response.Length == 0 ? "<empty>" : response)));
        return new(responses.Select(Encoding.Latin1.GetBytes));
    }

    /// <summary>
    /// Runs <paramref name="arguments" /> as on Windows over <paramref name="connector" /> and the
    /// in-memory disk, with <paramref name="standardInput" /> (Latin-1) on standard input.
    /// </summary>
    private async Task<int> RunAsync(IConnector connector, string[] arguments, string standardInput = "")
    {
        Diagnostics.Arrange("command line", string.Join(" ", arguments));
        Diagnostics.Arrange("standard input", standardInput.Length == 0 ? "<empty>" : standardInput);
        foreach (KeyValuePair<string, byte[]> file in fileSystem.ExistingContent)
        {
            Diagnostics.Bytes($"input file {file.Key}", file.Value);
        }

        int exitCode;
        using (Diagnostics.Phase("run"))
        {
            exitCode = await new CurlCommandRunner(
                    options => CreateTransferDispatch(connector, options),
                    fileSystem,
                    fileSystem,
                    standardOutput,
                    standardError,
                    new MemoryStream(Encoding.Latin1.GetBytes(standardInput)),
                    runsOnWindows: true)
                .RunAsync(arguments);
        }

        Diagnostics.Act("exit code", exitCode);
        Diagnostics.Bytes("stdout", standardOutput.ToArray());
        Diagnostics.Bytes("stderr", standardError.ToArray());
        if (connector is ScriptedConnector scripted)
        {
            Diagnostics.Bytes("request bytes", scripted.Written);
        }

        foreach (KeyValuePair<string, MemoryStream> file in fileSystem.Written)
        {
            Diagnostics.Bytes($"written file {file.Key}, platform newlines as LF", Lf(file.Value.ToArray()));
        }

        return exitCode;
    }

    /// <summary>The production handler set over <paramref name="connector" />, with the run's cookies.</summary>
    private static TransferDispatch CreateTransferDispatch(IConnector connector, Cli.CommandLineOptions options)
    {
        CookieEngine? cookies = CookieEngine.FromCommandLine(options);
        IReadOnlyList<IProtocolHandler> handlers = CurlComposition.CreateProtocolHandlers(
            connector,
            new RecordingDatagramConnector(CurlExitCode.CouldntConnect, "unused"),
            new PassThroughTlsProvider(),
            new LoopbackDnsResolver(),
            cookies?.HandlerStore);

        return new TransferDispatch(new ProtocolDispatcher(handlers), [], cookies);
    }

    /// <summary>The jar-file lines as <see cref="Cookies.CookieStore.SaveCookieJarAsync" /> ends them: CR LF on Windows, as measured.</summary>
    private static string NativeLines(string text) => text.Replace("\n", Environment.NewLine, StringComparison.Ordinal);

    /// <summary>The text with each platform newline written as LF, so what a test prints does not depend on the OS.</summary>
    private static string Lf(string text) => text.Replace(Environment.NewLine, "\n", StringComparison.Ordinal);

    /// <summary>The bytes with each platform newline written as LF, so what a test prints does not depend on the OS.</summary>
    private static byte[] Lf(byte[] bytes) => Encoding.Latin1.GetBytes(Lf(Encoding.Latin1.GetString(bytes)));

    private static string Latin1(byte[] bytes) => Encoding.Latin1.GetString(bytes);
}
