using System.Text;

using Curl.Core;
using Curl.Protocol.Abstractions;
using Curl.Testing;

namespace Curl.Console;

/// <summary>
/// Pins how the runner runs the <c>-:</c> / <c>--next</c> option groups: each group's URLs with its
/// own options, <c>%{urlnum}</c>, <c>%{xfer_id}</c> and <c>%{conn_id}</c> counted on across groups,
/// one cookie store shared by every group, and the exit code of the last transfer. Every expected
/// byte was measured on 2026-09-28 with curl 8.21.0 (mingw, Schannel) against
/// <c>Record-CurlExchange.ps1</c> answering <c>HTTP/1.1 200 OK</c>, <c>Content-Length: 2</c>, <c>hi</c>,
/// with <c>http://127.0.0.1:1/</c> as the URL that cannot connect (BL-509 Notes).
/// </summary>
[TestClass]
public sealed class CurlCommandRunnerNextGroupTests
{
    private const string A = "http://127.0.0.1:45909/a";

    private const string B = "http://127.0.0.1:45909/b";

    private const string C = "http://127.0.0.1:45909/c";

    private const string Unreachable = "http://127.0.0.1:1/x";

    private const string Head = "Host: 127.0.0.1:45909\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n";

    private const string Hi = "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nhi";

    private const string CouldNotConnect = "Failed to connect to 127.0.0.1:1 after 2018 ms: Could not connect to server";

    private const string JarHeader =
        "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";

    private const string K1Line = "127.0.0.1\tFALSE\t/\tFALSE\t0\tk1\tv1\n";

    private const string K2Line = "127.0.0.1\tFALSE\t/\tFALSE\t0\tk2\tv2\n";

    private static readonly string NewLine = Environment.NewLine;

    private readonly InMemoryFileSystem fileSystem = new();

    private readonly MemoryStream standardOutput = new();

    private readonly MemoryStream standardError = new();

    public TestContext TestContext { get; set; } = null!;

    private TestDiagnostics Diagnostics => TestDiagnostics.For(TestContext);

    private string StandardOutputText => Encoding.Latin1.GetString(standardOutput.ToArray());

    private string StandardErrorText => Encoding.UTF8.GetString(standardError.ToArray());

    [TestMethod]
    public async Task RunAsync_DataThenNext_PostsTheFirstUrlAndGetsTheSecond()
    {
        ScriptedConnector server = Serve(Hi, Hi);

        int exitCode = await RunAsync(server, ["-s", "-d", "a", A, "--next", B]);

        string expectedRequests = $"POST /a HTTP/1.1\r\n{Head}Content-Length: 1\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\na"
            + $"GET /b HTTP/1.1\r\n{Head}\r\n";
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hihi", StandardOutputText);
        Diagnostics.Diff("requests written", expectedRequests, Latin1(server.Written));
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hihi", StandardOutputText);
        Assert.AreEqual(
            expectedRequests,
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_FailingFirstGroup_RunsTheNextAndExitsWithItsCode()
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, ["-s", "-S", Unreachable, "--next", B]);

        Diagnostics.Act("transfers handled", http.Contexts.Count);
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hi", StandardOutputText);
        Diagnostics.Diff("stderr", $"curl: (7) {CouldNotConnect}\n", Lf(StandardErrorText));
        Diagnostics.Assert("transfers handled", 2, http.Contexts.Count);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hi", StandardOutputText);
        Assert.AreEqual($"curl: (7) {CouldNotConnect}{NewLine}", StandardErrorText);
        Assert.HasCount(2, http.Contexts);
    }

    [TestMethod]
    [DataRow(new[] { "-s", "-S", "--fail-early", Unreachable, "--next", B }, DisplayName = "--fail-early in the first group")]
    [DataRow(new[] { "-s", "-S", Unreachable, "--next", "--fail-early", B }, DisplayName = "--fail-early in the second group")]
    public async Task RunAsync_FailEarlyAnywhere_StopsAtTheFirstGroupsFailure(string[] arguments)
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, arguments);

        Diagnostics.Act("transfers handled", http.Contexts.Count);
        Diagnostics.Assert("exit code", 7, exitCode);
        Diagnostics.Diff("stdout", string.Empty, StandardOutputText);
        Diagnostics.Diff("stderr", $"curl: (7) {CouldNotConnect}\n", Lf(StandardErrorText));
        Diagnostics.Assert("transfers handled", 1, http.Contexts.Count);
        Assert.AreEqual(7, exitCode);
        Assert.AreEqual(string.Empty, StandardOutputText);
        Assert.AreEqual($"curl: (7) {CouldNotConnect}{NewLine}", StandardErrorText);
        Assert.HasCount(1, http.Contexts);
    }

    [TestMethod]
    public async Task RunAsync_FailingLastGroup_ExitsWithItsCode()
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, ["-s", "-S", A, "--next", Unreachable]);

        Diagnostics.Assert("exit code", 7, exitCode);
        Diagnostics.Diff("stdout", "hi", StandardOutputText);
        Diagnostics.Diff("stderr", $"curl: (7) {CouldNotConnect}\n", Lf(StandardErrorText));
        Assert.AreEqual(7, exitCode);
        Assert.AreEqual("hi", StandardOutputText);
        Assert.AreEqual($"curl: (7) {CouldNotConnect}{NewLine}", StandardErrorText);
    }

    [TestMethod]
    public async Task RunAsync_TwoFailingGroupsThenAGoodOne_ReportsBothAndExitsZero()
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, ["-s", "-S", Unreachable, "--next", "nosuch://h/", "--next", A]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hi", StandardOutputText);
        Diagnostics.Diff(
            "stderr",
            $"curl: (7) {CouldNotConnect}\ncurl: (1) Protocol \"nosuch\" not supported\n",
            Lf(StandardErrorText));
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hi", StandardOutputText);
        Assert.AreEqual(
            $"curl: (7) {CouldNotConnect}{NewLine}curl: (1) Protocol \"nosuch\" not supported{NewLine}",
            StandardErrorText);
    }

    [TestMethod]
    public async Task RunAsync_WriteOutInEachGroup_CountsUrlsTransfersAndConnectionsAcrossGroups()
    {
        const string Template = "%{urlnum} %{xfer_id} %{conn_id}\\n";
        Diagnostics.Arrange("write-out template", Template);

        int exitCode = await RunAsync(ConnectingHttp(), ["-s", "-w", Template, A, B, "--next", "-w", Template, C]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hi0 0 0\nhi1 1 1\nhi2 2 2\n", StandardOutputText);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hi0 0 0\nhi1 1 1\nhi2 2 2\n", StandardOutputText);
    }

    [TestMethod]
    public async Task RunAsync_WriteOutOnlyInTheFirstGroup_WritesItForTheFirstGroupOnly()
    {
        int exitCode = await RunAsync(ConnectingHttp(), ["-s", "-w", "[w]", A, "--next", B]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hi[w]hi", StandardOutputText);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hi[w]hi", StandardOutputText);
    }

    [TestMethod]
    public async Task RunAsync_OutputOnlyInTheFirstGroup_SendsTheSecondGroupsBodyToStandardOutput()
    {
        int exitCode = await RunAsync(ConnectingHttp(), ["-s", "-o", "f", A, "--next", B]);

        string writtenFile = Latin1(fileSystem.Written["f"].ToArray());
        Diagnostics.Act("file f", writtenFile);
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hi", StandardOutputText);
        Diagnostics.Diff("file f", "hi", writtenFile);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hi", StandardOutputText);
        Assert.AreEqual("hi", Latin1(fileSystem.Written["f"].ToArray()));
    }

    [TestMethod]
    [DataRow(new[] { "-o", "NUL" }, "0\r\n", DisplayName = "second group to a file: CR LF")]
    [DataRow(new string[0], "0\nhi", DisplayName = "second group to standard output: LF")]
    public async Task RunAsync_WriteOutBeforeALaterGroup_EndsItsLinesAsTheLaterGroupLeavesStandardOutput(
        string[] secondGroupOutput,
        string expectedStandardOutput)
    {
        Diagnostics.Arrange("second group output options", string.Join(' ', secondGroupOutput));

        int exitCode = await RunAsync(ConnectingHttp(), ["-s", "-o", "NUL", "-w", "%{exitcode}\\n", A, "--next", .. secondGroupOutput, B]);

        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", expectedStandardOutput, StandardOutputText);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual(expectedStandardOutput, StandardOutputText);
    }

    [TestMethod]
    public async Task RunAsync_OutputLeftOverInTheFirstGroup_RunsNoLaterGroup()
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, ["--no-progress-meter", "-o", "nul", "-o", "nul2", A, "--next", B]);

        Diagnostics.Act("transfers handled", http.Contexts.Count);
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Assert("transfers handled", 1, http.Contexts.Count);
        Diagnostics.Diff(
            "stderr",
            "Warning: Got more output options than URLs\nWarning: Got more output options than URLs\n",
            Lf(StandardErrorText));
        Assert.AreEqual(0, exitCode);
        Assert.HasCount(1, http.Contexts);
        string warning = "Warning: Got more output options than URLs" + NewLine;
        Assert.AreEqual(warning + warning, StandardErrorText);
    }

    [TestMethod]
    public async Task RunAsync_RequestMethodsConflictInALaterGroup_RunsTheGroupsBeforeItThenRefuses()
    {
        RecordingProtocolHandler http = ConnectingHttp();

        int exitCode = await RunAsync(http, [A, "--next", "-I", "-d", "x", B, "--next", A]);

        string expectedStandardError = "Warning: You can only select one HTTP request method! You asked for both POST " + NewLine
            + "Warning: (-d, --data) and HEAD (-I, --head)." + NewLine;
        Diagnostics.Act("transfers handled", http.Contexts.Count);
        Diagnostics.Assert("exit code", 2, exitCode);
        Diagnostics.Diff("stdout", "hi", StandardOutputText);
        Diagnostics.Assert("transfers handled", 1, http.Contexts.Count);
        Diagnostics.Diff("stderr", Lf(expectedStandardError), Lf(StandardErrorText));
        Assert.AreEqual(2, exitCode);
        Assert.AreEqual("hi", StandardOutputText);
        Assert.HasCount(1, http.Contexts);
        Assert.AreEqual(
            expectedStandardError,
            StandardErrorText);
    }

    [TestMethod]
    public async Task RunAsync_SameHeaderFileInTwoGroups_KeepsOnlyTheSecondGroupsHead()
    {
        ScriptedConnector server = Serve(
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 1\r\n\r\nhi",
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 2\r\n\r\nhi");

        int exitCode = await RunAsync(server, ["-s", "-D", "h1", A, "--next", "-D", "h1", B]);

        const string ExpectedHead = "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 2\r\n\r\n";
        string writtenHead = Latin1(fileSystem.Written["h1"].ToArray());
        Diagnostics.Act("file h1", writtenHead);
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("file h1", ExpectedHead, writtenHead);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual(ExpectedHead, Latin1(fileSystem.Written["h1"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_HeaderFileInTheFirstGroupOnly_KeepsTheFirstGroupsHead()
    {
        ScriptedConnector server = Serve(
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 1\r\n\r\nhi",
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 2\r\n\r\nhi");

        int exitCode = await RunAsync(server, ["-s", "-D", "h2", A, "--next", B]);

        const string ExpectedHead = "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nX-N: 1\r\n\r\n";
        string writtenHead = Latin1(fileSystem.Written["h2"].ToArray());
        Diagnostics.Act("file h2", writtenHead);
        Diagnostics.Assert("exit code", 0, exitCode);
        Diagnostics.Diff("stdout", "hihi", StandardOutputText);
        Diagnostics.Diff("file h2", ExpectedHead, writtenHead);
        Assert.AreEqual(0, exitCode);
        Assert.AreEqual("hihi", StandardOutputText);
        Assert.AreEqual(ExpectedHead, Latin1(fileSystem.Written["h2"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_JarInTheFirstGroupOnly_SendsTheSecondGroupNoCookieAndKeepsOnlyTheFirstCookie()
    {
        ScriptedConnector server = ServeCookies();

        await RunAsync(server, ["-s", "-c", "jar1", A, "--next", B]);

        string expectedRequests = $"GET /a HTTP/1.1\r\n{Head}\r\nGET /b HTTP/1.1\r\n{Head}\r\n";
        string writtenJar = Latin1(fileSystem.Written["jar1"].ToArray());
        Diagnostics.Act("file jar1", Lf(writtenJar));
        Diagnostics.Diff("requests written", expectedRequests, Latin1(server.Written));
        Diagnostics.Diff("file jar1", JarHeader + K1Line, Lf(writtenJar));
        Assert.AreEqual(expectedRequests, Latin1(server.Written));
        Assert.AreEqual(NativeLines(JarHeader + K1Line), Latin1(fileSystem.Written["jar1"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_JarInTheSecondGroupOnly_KeepsOnlyTheSecondCookie()
    {
        await RunAsync(ServeCookies(), ["-s", A, "--next", "-c", "jar2", B]);

        string writtenJar = Latin1(fileSystem.Written["jar2"].ToArray());
        Diagnostics.Act("file jar2", Lf(writtenJar));
        Diagnostics.Diff("file jar2", JarHeader + K2Line, Lf(writtenJar));
        Assert.AreEqual(NativeLines(JarHeader + K2Line), Latin1(fileSystem.Written["jar2"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_JarInBothGroups_SharesTheCookiesBetweenThem()
    {
        ScriptedConnector server = ServeCookies();

        await RunAsync(server, ["-s", "-c", "jar4", A, "--next", "-c", "jar5", B]);

        string expectedRequests = $"GET /a HTTP/1.1\r\n{Head}\r\nGET /b HTTP/1.1\r\n{Head}Cookie: k1=v1\r\n\r\n";
        string writtenFirstJar = Latin1(fileSystem.Written["jar4"].ToArray());
        string writtenSecondJar = Latin1(fileSystem.Written["jar5"].ToArray());
        Diagnostics.Act("file jar4", Lf(writtenFirstJar));
        Diagnostics.Act("file jar5", Lf(writtenSecondJar));
        Diagnostics.Diff("requests written", expectedRequests, Latin1(server.Written));
        Diagnostics.Diff("file jar4", JarHeader + K1Line, Lf(writtenFirstJar));
        Diagnostics.Diff("file jar5", JarHeader + K2Line + K1Line, Lf(writtenSecondJar));
        Assert.AreEqual(expectedRequests, Latin1(server.Written));
        Assert.AreEqual(NativeLines(JarHeader + K1Line), Latin1(fileSystem.Written["jar4"].ToArray()));
        Assert.AreEqual(NativeLines(JarHeader + K2Line + K1Line), Latin1(fileSystem.Written["jar5"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieStringInTheSecondGroupAfterAJar_SendsOnlyTheString()
    {
        ScriptedConnector server = ServeCookies();

        await RunAsync(server, ["-s", "-c", "jar6", A, "--next", "-b", "x=y", B]);

        string expectedRequests = $"GET /a HTTP/1.1\r\n{Head}\r\nGET /b HTTP/1.1\r\n{Head}Cookie: x=y\r\n\r\n";
        string writtenJar = Latin1(fileSystem.Written["jar6"].ToArray());
        Diagnostics.Act("file jar6", Lf(writtenJar));
        Diagnostics.Diff("requests written", expectedRequests, Latin1(server.Written));
        Diagnostics.Diff("file jar6", JarHeader + K1Line, Lf(writtenJar));
        Assert.AreEqual(expectedRequests, Latin1(server.Written));
        Assert.AreEqual(NativeLines(JarHeader + K1Line), Latin1(fileSystem.Written["jar6"].ToArray()));
    }

    /// <summary>A connector answering the first request with cookie <c>k1</c> and the second with <c>k2</c>.</summary>
    private static ScriptedConnector ServeCookies() =>
        Serve(
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nSet-Cookie: k1=v1\r\n\r\nhi",
            "HTTP/1.1 200 OK\r\nContent-Length: 2\r\nSet-Cookie: k2=v2\r\n\r\nhi");

    /// <summary>A connector whose connections answer <paramref name="responses" /> in turn.</summary>
    private static ScriptedConnector Serve(params string[] responses) => new(responses.Select(Encoding.Latin1.GetBytes));

    /// <summary>
    /// An <c>http</c> handler that fails a URL on port 1 with exit 7, as curl fails to connect there, and
    /// writes <c>hi</c> for any other.
    /// </summary>
    private static RecordingProtocolHandler ConnectingHttp() =>
        new("http", async context =>
        {
            if (context.Url.Port == 1)
            {
                return TransferResult.Failure(CurlExitCode.CouldntConnect, CouldNotConnect);
            }

            await context.Output.WriteAsync("hi"u8.ToArray(), context.CancellationToken);
            return TransferResult.Success(2);
        });

    /// <summary>Runs <paramref name="arguments" /> as on Windows through <paramref name="handler" /> alone.</summary>
    private Task<int> RunAsync(IProtocolHandler handler, string[] arguments)
    {
        Diagnostics.Arrange("handler", "recording http handler: port 1 fails with exit 7, any other port writes hi");
        return RunAndReportAsync(CreateRunner(_ => new TransferDispatch(new ProtocolDispatcher([handler]))), arguments);
    }

    /// <summary>
    /// Runs <paramref name="arguments" /> as on Windows through the production handler set over
    /// <paramref name="connector" />, every option group's cookies sharing the run's store.
    /// </summary>
    private Task<int> RunAsync(IConnector connector, string[] arguments)
    {
        Diagnostics.Arrange("handler", "production handlers over a scripted connector, cookies shared across groups");
        return RunAndReportAsync(
            CreateRunner(CurlComposition.SharingRunCookies((_, cookies) => CreateTransferDispatch(connector, cookies))),
            arguments);
    }

    private async Task<int> RunAndReportAsync(CurlCommandRunner runner, string[] arguments)
    {
        Diagnostics.Arrange("command line", string.Join(' ', arguments));
        int exitCode;
        using (Diagnostics.Phase("run"))
        {
            exitCode = await runner.RunAsync(arguments);
        }

        Diagnostics.Act("exit code", exitCode);
        Diagnostics.Act("stdout", Lf(StandardOutputText));
        Diagnostics.Act("stderr", Lf(StandardErrorText));
        return exitCode;
    }

    private CurlCommandRunner CreateRunner(Func<Cli.CommandLineOptions, TransferDispatch> createTransferDispatch) =>
        new(createTransferDispatch, fileSystem, fileSystem, standardOutput, standardError, new MemoryStream(), runsOnWindows: true);

    /// <summary>The production handler set over <paramref name="connector" />, with the group's cookies.</summary>
    private static TransferDispatch CreateTransferDispatch(IConnector connector, CookieEngine? cookies)
    {
        IReadOnlyList<IProtocolHandler> handlers = CurlComposition.CreateProtocolHandlers(
            connector,
            new RecordingDatagramConnector(CurlExitCode.CouldntConnect, "unused"),
            new PassThroughTlsProvider(),
            new LoopbackDnsResolver(),
            cookies?.HandlerStore);

        return new TransferDispatch(new ProtocolDispatcher(handlers), [], cookies);
    }

    /// <summary>The jar-file lines as <see cref="Cookies.CookieStore.SaveCookieJarAsync" /> ends them: CR LF on Windows, as measured.</summary>
    private static string NativeLines(string text) => text.Replace("\n", Environment.NewLine, StringComparison.Ordinal);

    private static string Lf(string text) => text.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string Latin1(byte[] bytes) => Encoding.Latin1.GetString(bytes);
}
