using System.Text;

using Curl.Core;
using Curl.Protocol.Abstractions;

namespace Curl.Console;

/// <summary>
/// Pins <c>-b</c>, <c>-c</c> and <c>-j</c> end to end through the production handler set over a
/// <see cref="ScriptedConnector" /> and an <see cref="InMemoryFileSystem" />. Every expected byte
/// was measured on 2026-09-26 with curl 8.21.0 (mingw, Schannel) against
/// <c>Record-CurlExchange.ps1</c> answering <c>HTTP/1.1 200 OK</c>, <c>Set-Cookie: got=g1</c>,
/// <c>Content-Length: 0</c>, with <c>in.txt</c> holding the session cookie <c>sess=s1</c> and the
/// persistent cookie <c>keep=k1</c> for <c>127.0.0.1</c> (BL-237 Notes).
/// </summary>
[TestClass]
public sealed class CurlCommandRunnerCookieTests
{
    private const string Url = "http://127.0.0.1:18231/";

    private const string Head = "Host: 127.0.0.1:18231\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n";

    private const string SetsCookie = "HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 0\r\n\r\n";

    private const string CookieFile =
        "# Netscape HTTP Cookie File\n127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\ts1\n127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tkeep\tk1\n";

    private const string StandardInputCookies =
        "127.0.0.1\tFALSE\t/\tFALSE\t0\tname\tvalue\n127.0.0.1\tFALSE\t/\tFALSE\t0\tother\ttwo\n";

    private const string JarHeader =
        "# Netscape HTTP Cookie File\n# https://curl.se/docs/http-cookies.html\n# This file was generated by libcurl! Edit at your own risk.\n\n";

    private const string GotLine = "127.0.0.1\tFALSE\t/\tFALSE\t0\tgot\tg1\n";

    private const string KeepLine = "127.0.0.1\tFALSE\t/\tFALSE\t4102444800\tkeep\tk1\n";

    private const string SessLine = "127.0.0.1\tFALSE\t/\tFALSE\t0\tsess\ts1\n";

    private readonly InMemoryFileSystem fileSystem = new();

    private readonly MemoryStream standardOutput = new();

    private readonly MemoryStream standardError = new();

    private string StandardOutputText => Encoding.Latin1.GetString(standardOutput.ToArray());

    [TestInitialize]
    public void AddCookieFile() => fileSystem.ExistingContent["in.txt"] = Encoding.Latin1.GetBytes(CookieFile);

    [TestMethod]
    [DataRow(new[] { "-b", "in.txt" }, "Cookie: keep=k1; sess=s1\r\n", DisplayName = "-b file")]
    [DataRow(new[] { "-b", "in.txt", "-j" }, "Cookie: keep=k1\r\n", DisplayName = "-b file -j")]
    [DataRow(new[] { "-b", "a=1; b=2" }, "Cookie: a=1; b=2\r\n", DisplayName = "-b string")]
    [DataRow(new[] { "-b", "missing.txt" }, "", DisplayName = "-b missing file")]
    [DataRow(new[] { "-c", "jar.txt" }, "", DisplayName = "-c alone")]
    public async Task RunAsync_CookieOption_SendsTheCookieHeaderCurlSends(string[] arguments, string expectedCookieHeader)
    {
        fileSystem.UnreadablePaths.Add("missing.txt");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", .. arguments, Url]);

        Assert.AreEqual(0, exitCode);
        Assert.AreEqual($"GET / HTTP/1.1\r\n{Head}{expectedCookieHeader}\r\n", Latin1(server.Written));
    }

    /// <summary>
    /// Measured 2026-09-27 with <c>Record-CurlExchange.ps1 -StandardInput</c> holding
    /// <see cref="StandardInputCookies" /> (BL-316 Notes).
    /// </summary>
    [TestMethod]
    [DataRow(new[] { "-b", "-" }, "Cookie: other=two; name=value\r\n", DisplayName = "-b -")]
    [DataRow(new[] { "-b", "-", "-b", "s=1" }, "Cookie: other=two; name=value; s=1\r\n", DisplayName = "-b - -b s=1")]
    [DataRow(new[] { "-b", "-", "-b", "-" }, "Cookie: other=two; name=value\r\n", DisplayName = "-b - -b -")]
    public async Task RunAsync_CookieFileOnStandardInput_SendsItsCookies(string[] arguments, string expectedCookieHeader)
    {
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", .. arguments, "http://127.0.0.1:18316/x"], StandardInputCookies);

        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            $"GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n{expectedCookieHeader}\r\n",
            Latin1(server.Written));
    }

    /// <summary>
    /// curl 8.21.0 reads <c>-b -</c> only at the first HTTP transfer, so a <c>telnet</c> transfer
    /// before it sends standard input and the HTTP one sends no cookie (measured 2026-09-27, BL-316 Notes).
    /// </summary>
    [TestMethod]
    public async Task RunAsync_CookieFileOnStandardInputAfterATelnetTransfer_LeavesStandardInputToTelnet()
    {
        ScriptedConnector server = Serve(string.Empty, SetsCookie);

        int exitCode = await RunAsync(
            server,
            ["-s", "-b", "-", "telnet://127.0.0.1:18316", "http://127.0.0.1:18316/x"],
            StandardInputCookies);

        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            StandardInputCookies + "GET /x HTTP/1.1\r\nHost: 127.0.0.1:18316\r\nUser-Agent: curl/8.21.0\r\nAccept: */*\r\n\r\n",
            Latin1(server.Written));
    }

    /// <summary>
    /// Measured 2026-09-27 with <c>curl -s -v -b cf.txt -c - http://127.0.0.1:&lt;port&gt;/</c>: each refused
    /// <c>Set-Cookie:</c> line of the file prints its line before the connection's, and the
    /// accepted one is sent (BL-461 Notes). The scripted connector prints no <c>Trying</c> lines.
    /// </summary>
    [TestMethod]
    public async Task RunAsync_VerboseCookieFileWithRefusedSetCookieLines_PrintsCurlsRefusalLines()
    {
        fileSystem.ExistingContent["cf.txt"] =
            Encoding.Latin1.GetBytes("Set-Cookie: g=v; X=\u0001\nSet-Cookie: c\nSet-Cookie: s=v; Secure\n");
        ScriptedConnector server = Serve(SetsCookie);

        int exitCode = await RunAsync(server, ["-s", "-v", "-b", "cf.txt", Url]);

        Assert.AreEqual(0, exitCode);
        Assert.StartsWith(
            "* invalid octets in value, cookie dropped\r\n* invalid cookie, dropped\r\n* using HTTP/1.x\r\n",
            Latin1(standardError.ToArray()));
        Assert.AreEqual($"GET / HTTP/1.1\r\n{Head}Cookie: s=v\r\n\r\n", Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarFile_WritesTheReceivedCookieInThePlatformsLineEndings()
    {
        await RunAsync(Serve(SetsCookie), ["-s", "-c", "jar.txt", Url]);

        Assert.AreEqual(NativeLines(JarHeader + GotLine), Latin1(fileSystem.Written["jar.txt"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieFileJunkedAndJar_WritesTheReceivedAndPersistentCookiesNewestFirst()
    {
        await RunAsync(Serve(SetsCookie), ["-s", "-b", "in.txt", "-j", "-c", "jarj.txt", Url]);

        Assert.AreEqual(NativeLines(JarHeader + GotLine + KeepLine), Latin1(fileSystem.Written["jarj.txt"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputAfterABodyThere_WritesTheJarWithLineFeeds()
    {
        await RunAsync(Serve(SetsCookie), ["-s", "-b", "in.txt", "-c", "-", Url]);

        Assert.AreEqual(JarHeader + GotLine + KeepLine + SessLine, StandardOutputText);
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputWithTheBodyInAFile_WritesTheJarInTextMode()
    {
        await RunAsync(
            Serve("HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 5\r\n\r\nbody\n"),
            ["-s", "-c", "-", "-o", "out.bin", Url]);

        Assert.AreEqual((JarHeader + GotLine).Replace("\n", "\r\n", StringComparison.Ordinal), StandardOutputText);
        Assert.AreEqual("body\n", Latin1(fileSystem.Written["out.bin"].ToArray()));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnStandardOutputForTwoUrls_WritesTheJarAfterEachTransfersWriteOut()
    {
        const string Response = "HTTP/1.1 200 OK\r\nSet-Cookie: got=g1\r\nContent-Length: 5\r\n\r\nbody\n";
        ScriptedConnector server = Serve(Response, Response);

        await RunAsync(server, ["-s", "-c", "-", "-w", "[w]\\n", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        string jar = JarHeader + GotLine;
        Assert.AreEqual($"body\n[w]\n{jar}body\n[w]\n{jar}", StandardOutputText);
        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: got=g1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieStringOnlyForTwoUrls_NeverSendsTheReceivedCookie()
    {
        ScriptedConnector server = Serve(SetsCookie, SetsCookie);

        await RunAsync(server, ["-s", "-b", "a=1", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\nGET /2 HTTP/1.1\r\n{Head}Cookie: a=1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieFileAndStringForTwoUrls_SendsTheReceivedCookieBeforeTheString()
    {
        ScriptedConnector server = Serve(SetsCookie, SetsCookie);

        await RunAsync(server, ["-s", "-b", "in.txt", "-b", "a=1", "http://127.0.0.1:18231/1", "http://127.0.0.1:18231/2"]);

        Assert.StartsWith(
            $"GET /1 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; a=1\r\n\r\n"
            + $"GET /2 HTTP/1.1\r\n{Head}Cookie: keep=k1; sess=s1; got=g1; a=1\r\n\r\n",
            Latin1(server.Written));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarAndTheConnectionFails_WritesTheEmptyJar()
    {
        int exitCode = await RunAsync(
            new RecordingConnector(CurlExitCode.CouldntConnect, "Failed to connect"),
            ["-s", "-c", "jarfail.txt", "http://127.0.0.1:1/"]);

        Assert.AreEqual(7, exitCode);
        Assert.AreEqual(NativeLines(JarHeader), Latin1(fileSystem.Written["jarfail.txt"].ToArray()));
    }

    [TestMethod]
    [DataRow("dict://127.0.0.1:1/x", DisplayName = "dict")]
    [DataRow("dict://exa mple.com/x", DisplayName = "malformed")]
    public async Task RunAsync_CookieJarAndAUrlThatIsNotHttp_WritesNoJar(string url)
    {
        await RunAsync(Serve(), ["-s", "-b", "in.txt", "-c", "j4.txt", url]);

        Assert.IsFalse(fileSystem.Written.ContainsKey("j4.txt"));
    }

    [TestMethod]
    public async Task RunAsync_CookieJarOnAFailedStandardOutput_WritesNothingAndReportsTheWriteFailure()
    {
        using FailingWriteStream closed = new();

        int exitCode = await new CurlCommandRunner(
                options => CreateTransferDispatch(Serve("HTTP/1.1 200 OK\r\nContent-Length: 5\r\n\r\nbody\n"), options),
                fileSystem,
                fileSystem,
                closed,
                new MemoryStream(),
                new MemoryStream(),
                runsOnWindows: true)
            .RunAsync(["-s", "-c", "-", Url]);

        Assert.AreEqual(23, exitCode);
    }

    /// <summary>A connector whose connections answer <paramref name="responses" /> in turn.</summary>
    private static ScriptedConnector Serve(params string[] responses) => new(responses.Select(Encoding.Latin1.GetBytes));

    /// <summary>
    /// Runs <paramref name="arguments" /> as on Windows over <paramref name="connector" /> and the
    /// in-memory disk, with <paramref name="standardInput" /> (Latin-1) on standard input.
    /// </summary>
    private Task<int> RunAsync(IConnector connector, string[] arguments, string standardInput = "") =>
        new CurlCommandRunner(
                options => CreateTransferDispatch(connector, options),
                fileSystem,
                fileSystem,
                standardOutput,
                standardError,
                new MemoryStream(Encoding.Latin1.GetBytes(standardInput)),
                runsOnWindows: true)
            .RunAsync(arguments);

    /// <summary>The production handler set over <paramref name="connector" />, with the run's cookies.</summary>
    private static TransferDispatch CreateTransferDispatch(IConnector connector, Cli.CommandLineOptions options)
    {
        CookieEngine? cookies = CookieEngine.FromCommandLine(options);
        IReadOnlyList<IProtocolHandler> handlers = CurlComposition.CreateProtocolHandlers(
            connector,
            new RecordingDatagramConnector(CurlExitCode.CouldntConnect, "unused"),
            new PassThroughTlsProvider(),
            new LoopbackDnsResolver(),
            cookies?.HandlerStore);

        return new TransferDispatch(new ProtocolDispatcher(handlers), [], cookies);
    }

    /// <summary>The jar-file lines as <see cref="Cookies.CookieStore.SaveCookieJarAsync" /> ends them: CR LF on Windows, as measured.</summary>
    private static string NativeLines(string text) => text.Replace("\n", Environment.NewLine, StringComparison.Ordinal);

    private static string Latin1(byte[] bytes) => Encoding.Latin1.GetString(bytes);
}
