using System.Globalization;
using System.Net;
using System.Net.Sockets;
using System.Text;

namespace Curl.Core.AltSvc;

/// <summary>
/// The alt-svc cache behind <c>--alt-svc</c>: reads curl 8.21.0's alt-svc file, learns from
/// <c>Alt-Svc</c> headers, answers the alternative for an origin, and writes the file back
/// byte for byte as curl does, measured on 2026-09-29 UTC (BL-622's notes, ADR-0174).
/// </summary>
/// <remarks>
/// Entries keep the order they were read or learned in, and the first one that matches wins.
/// An entry expires when its expiry is before the current second of the injected
/// <see cref="TimeProvider" />: it is dropped when read, and when a lookup passes it, but an
/// entry already held is written back whether or not it has expired, as curl does.
/// </remarks>
/// <param name="timeProvider">The clock expiries are counted on.</param>
public sealed class AltSvcCache(TimeProvider timeProvider)
{
    /// <summary>The two comment lines curl writes at the top of the file, without line endings.</summary>
    public static readonly IReadOnlyList<string> FileHeaderLines =
    [
        "# Your alt-svc cache. https://curl.se/docs/alt-svc.html",
        "# This file was generated by libcurl! Edit at your own risk.",
    ];

    /// <summary>
    /// The longest file line curl reads, without its line ending: 4093 characters, measured
    /// (libcurl's <c>MAX_ALTSVC_LINE</c> of 4095 bytes holds the LF and a terminator too).
    /// </summary>
    public const int MaxFileLineLength = 4093;

    private static readonly long LatestExpiry = DateTimeOffset.MaxValue.ToUnixTimeSeconds();

    private readonly List<AltSvcEntry> entries = [];

    /// <summary>Gets the entries held, in order.</summary>
    public IReadOnlyList<AltSvcEntry> Entries => entries;

    /// <summary>
    /// Adds the entries of an alt-svc file's text after those already held, skipping every
    /// line <see cref="AltSvcFileLineParser" /> reads no entry from and every entry that has
    /// expired. A line longer than <see cref="MaxFileLineLength" />, comment or not, ends the
    /// reading there, as it ends curl's.
    /// </summary>
    /// <param name="fileText">The whole file, lines ending in LF or CR LF.</param>
    public void ReadFile(string fileText)
    {
        ArgumentNullException.ThrowIfNull(fileText);

        long now = NowSeconds();
        foreach (string line in fileText.Split('\n'))
        {
            if (line.AsSpan().TrimEnd('\r').Length > MaxFileLineLength)
            {
                break;
            }

            AltSvcEntry? entry = AltSvcFileLineParser.Parse(line);
            if (entry is not null && entry.Expires.ToUnixTimeSeconds() >= now)
            {
                entries.Add(entry);
            }
        }
    }

    /// <summary>
    /// Learns from one <c>Alt-Svc</c> header received from an origin, as libcurl 8.21.0's
    /// <c>Curl_altsvc_parse</c> does: <c>clear</c> removes the origin's entries; otherwise the
    /// first alternative with a known ALPN removes them and each such alternative is added,
    /// expiring its <c>ma</c> seconds from now.
    /// </summary>
    /// <param name="headerValue">The header value, as received.</param>
    /// <param name="sourceAlpn">The HTTP version the response came over.</param>
    /// <param name="sourceHost">The origin's host, an IPv6 address without brackets, as curl passes it.</param>
    /// <param name="sourcePort">The origin's port.</param>
    public void ApplyHeader(string headerValue, AltSvcAlpn sourceAlpn, string sourceHost, int sourcePort)
    {
        ArgumentNullException.ThrowIfNull(headerValue);
        ArgumentNullException.ThrowIfNull(sourceHost);

        AltSvcHeader header = AltSvcHeaderParser.Parse(headerValue);
        if (header.IsClear || header.Alternatives.Count > 0)
        {
            entries.RemoveAll(entry => entry.IsFor(sourceAlpn, sourceHost, sourcePort));
        }

        long now = NowSeconds();
        foreach (AltSvcAlternative alternative in header.Alternatives)
        {
            Add(AltSvcEntry.Create(
                sourceAlpn,
                sourceHost,
                sourcePort,
                alternative.Alpn,
                alternative.Host ?? sourceHost,
                alternative.Port,
                ExpiryAfter(now, alternative.MaxAgeSeconds),
                alternative.Persist));
        }
    }

    /// <summary>
    /// Finds the alternative for an origin as libcurl 8.21.0's <c>Curl_altsvc_lookup</c>
    /// does: the first entry for the origin whose destination version is allowed, removing
    /// each expired entry passed on the way.
    /// </summary>
    /// <param name="sourceAlpn">The HTTP version the origin would be reached over.</param>
    /// <param name="sourceHost">
    /// The origin's host, an IPv6 address without brackets, matched case-insensitively,
    /// ignoring a trailing dot.
    /// </param>
    /// <param name="sourcePort">The origin's port.</param>
    /// <param name="allowedDestinationAlpns">The versions the transfer may switch to.</param>
    /// <returns>The entry, or <see langword="null" /> when none applies.</returns>
    public AltSvcEntry? Find(AltSvcAlpn sourceAlpn, string sourceHost, int sourcePort, IReadOnlySet<AltSvcAlpn> allowedDestinationAlpns)
    {
        ArgumentNullException.ThrowIfNull(sourceHost);
        ArgumentNullException.ThrowIfNull(allowedDestinationAlpns);

        long now = NowSeconds();
        int index = 0;
        while (index < entries.Count)
        {
            AltSvcEntry entry = entries[index];
            if (entry.Expires.ToUnixTimeSeconds() < now)
            {
                entries.RemoveAt(index);
                continue;
            }

            if (entry.IsFor(sourceAlpn, sourceHost, sourcePort) && allowedDestinationAlpns.Contains(entry.DestinationAlpn))
            {
                return entry;
            }

            index++;
        }

        return null;
    }

    /// <summary>
    /// Writes the file as libcurl 8.21.0's <c>Curl_altsvc_save</c> does: the two header
    /// comments, then one line per entry, an IPv6 host in brackets, the expiry in UTC and the
    /// priority always 0.
    /// </summary>
    /// <param name="lineEnding">
    /// What ends each line: curl writes the file in text mode, so its Windows build ends lines
    /// in CR LF and its Linux and macOS builds in LF. Pass <see cref="Environment.NewLine" />.
    /// </param>
    /// <returns>The file's text.</returns>
    public string FormatFile(string lineEnding)
    {
        ArgumentNullException.ThrowIfNull(lineEnding);

        StringBuilder text = new();
        foreach (string line in FileHeaderLines)
        {
            text.Append(line).Append(lineEnding);
        }

        foreach (AltSvcEntry entry in entries)
        {
            text.Append(CultureInfo.InvariantCulture, $"{AltSvcAlpnToken.Format(entry.SourceAlpn)} {FormatHost(entry.SourceHost)} {entry.SourcePort} ")
                .Append(CultureInfo.InvariantCulture, $"{AltSvcAlpnToken.Format(entry.DestinationAlpn)} {FormatHost(entry.DestinationHost)} {entry.DestinationPort} ")
                .Append(CultureInfo.InvariantCulture, $"\"{entry.Expires.UtcDateTime:yyyyMMdd HH:mm:ss}\" {(entry.Persist ? 1 : 0)} 0")
                .Append(lineEnding);
        }

        return text.ToString();
    }

    private static string FormatHost(string host) =>
        IPAddress.TryParse(host, out IPAddress? address) && address.AddressFamily == AddressFamily.InterNetworkV6 && !host.Contains('%')
            ? $"[{host}]"
            : host;

    /// <summary>
    /// The expiry <paramref name="maxAgeSeconds" /> from <paramref name="now" />, held at the last
    /// second <see cref="DateTimeOffset" /> can hold.
    /// </summary>
    private static DateTimeOffset ExpiryAfter(long now, long maxAgeSeconds) =>
        DateTimeOffset.FromUnixTimeSeconds(maxAgeSeconds > LatestExpiry - now ? LatestExpiry : now + maxAgeSeconds);

    private void Add(AltSvcEntry? entry)
    {
        if (entry is not null)
        {
            entries.Add(entry);
        }
    }

    private long NowSeconds() => timeProvider.GetUtcNow().ToUnixTimeSeconds();
}
