using System.Security.Cryptography;
using System.Text;

using Curl.Tls;

namespace Curl.Networking;

[TestClass]
public sealed class TlsSessionCacheTests
{
    private const string PeerKey = "example.com:443:IMPL-Curl:G";

    private static readonly DateTimeOffset Received = DateTimeOffset.FromUnixTimeSeconds(1_800_000_000);

    private static readonly byte[] Salt = [.. Enumerable.Range(0, 32).Select(value => (byte)value)];

    [TestMethod]
    public void PeerKey_NamesHostPortVerificationCaFileAndImplementation()
    {
        Assert.AreEqual("example.com:443:IMPL-Curl:G", TlsSessionCache.PeerKey("example.com", 443, new TlsClientOptions()));
        Assert.AreEqual("h:8443:NO-VRFY-PEER:NO-VRFY-HOST:VRFY-STATUS:IMPL-Curl:G", TlsSessionCache.PeerKey("h", 8443, new TlsClientOptions(Insecure: true, CaCertificateFile: "ca.pem", RequireCertificateStatus: true)));
        Assert.AreEqual($"h:1:CA-{Path.GetFullPath("ca.pem")}:IMPL-Curl:G", TlsSessionCache.PeerKey("h", 1, new TlsClientOptions(CaCertificateFile: "ca.pem")));
        Assert.ThrowsExactly<ArgumentNullException>(() => TlsSessionCache.PeerKey("h", 1, null!));
    }

    [TestMethod]
    public void Constructor_WithoutClock_Throws() =>
        Assert.AreEqual("timeProvider", Assert.ThrowsExactly<ArgumentNullException>(() => new TlsSessionCache(null!)).ParamName);

    [TestMethod]
    public void NewRandomSalt_Called_Returns32Bytes() =>
        Assert.HasCount(32, TlsSessionCache.NewRandomSalt());

    [TestMethod]
    public void Export_WithNoSession_IsEmpty() =>
        Assert.AreEqual(string.Empty, new TlsSessionCache(new FixedClock(Received)).Export());

    // The file bytes for a fixed session: curl's two comment lines, then the salt and the
    // HMAC-SHA256 of the peer key under it, and the packed SSL_SESSION.
    [TestMethod]
    public void Export_TrackedSession_WritesCurlsLine()
    {
        var cache = new TlsSessionCache(new FixedClock(Received), () => Salt);
        var session = Session(maxEarlyData: 16384);
        cache.Track(PeerKey, () => [session]);

        var text = cache.Export();

        byte[] shmac = [.. Salt, .. HMACSHA256.HashData(Salt, Encoding.ASCII.GetBytes(PeerKey))];
        byte[] packed = TlsSessionPacking.Pack(new PackedTlsSession(TlsSessionCodec.Encode(session), 0x0304, 1_800_007_200, "http/1.1", 16384, null));
        Assert.AreEqual(
            "# Your SSL session cache. https://curl.se/docs/ssl-sessions.html\n# This file was generated by libcurl! Edit at your own risk.\n"
                + $"{Convert.ToBase64String(shmac)}:{Convert.ToBase64String(packed)}\n",
            text);
        Assert.AreEqual(text, cache.Export(), "a tracked connection is read once and its peer keeps its salt");
    }

    [TestMethod]
    public void Import_ExportedFile_ResumesTheSessionForTheSamePeerOnly()
    {
        var writer = new TlsSessionCache(new FixedClock(Received), () => Salt);
        writer.Track(PeerKey, () => [Session()]);
        var text = writer.Export();

        var reader = new TlsSessionCache(new FixedClock(Received.AddSeconds(10)));
        Assert.AreEqual(0, reader.Import(text.Replace("\n", "\r\n", StringComparison.Ordinal) + "\n  \n", "f").Count);

        Assert.IsNull(reader.Take("other:443:IMPL-Curl:G"));
        var resumed = reader.Take(PeerKey);
        Assert.IsNotNull(resumed);
        CollectionAssert.AreEqual(Session().Ticket, resumed.Ticket);
        Assert.IsNull(reader.Take(PeerKey), "a TLS 1.3 session is taken out when offered");
        Assert.AreEqual(string.Empty, reader.Export());
    }

    [TestMethod]
    public void Import_UnusedLine_IsWrittenBackUnchanged()
    {
        var writer = new TlsSessionCache(new FixedClock(Received), () => Salt);
        writer.Track(PeerKey, () => [Session()]);
        var text = writer.Export();
        var reader = new TlsSessionCache(new FixedClock(Received));

        reader.Import(text, "f");

        Assert.AreEqual(text, reader.Export());
    }

    [TestMethod]
    public void Import_BadLines_WarnsAsCurlDoes()
    {
        var shmac = Convert.ToBase64String(new byte[64]);
        var packed = Convert.ToBase64String(TlsSessionPacking.Pack(new PackedTlsSession([1], 0x0304, 1, null, 0, null)));
        var text = string.Join('\n',
            "# comment: with a colon",
            "no colon here",
            "QQ=:" + packed,
            shmac + ":Q Q=",
            shmac + ":" + Convert.ToBase64String([9]),
            Convert.ToBase64String(new byte[10]) + ":" + packed,
            "QUJD===:" + packed,
            ":" + packed,
            "QU*D:" + packed);

        var warnings = new TlsSessionCache(new FixedClock(Received)).Import(text, "s.txt");

        CollectionAssert.AreEqual(
            new[]
            {
                "Warning: unrecognized line 1 in SSL session file s.txt",
                "Warning: invalid shmax base64 encoding in line 2",
                "Warning: invalid sdata base64 encoding in line 3: Q Q=",
                "Warning: import of session from line 4 rejected(26)",
                "Warning: import of session from line 5 rejected(43)",
                "Warning: invalid shmax base64 encoding in line 6",
                "Warning: invalid shmax base64 encoding in line 7",
                "Warning: invalid shmax base64 encoding in line 8",
            },
            warnings.ToArray());
        Assert.ThrowsExactly<ArgumentNullException>(() => new TlsSessionCache(new FixedClock(Received)).Import(null!, "f"));
    }

    // Sessions not from TLS 1.3, or whose bytes are not an SSL_SESSION, are never offered;
    // one not from TLS 1.3 replaces the others, and a TLS 1.3 one replaces those.
    [TestMethod]
    public void Take_SkipsSessionsItCannotResume()
    {
        var shmac = Convert.ToBase64String([.. Salt, .. HMACSHA256.HashData(Salt, Encoding.ASCII.GetBytes(PeerKey))]);
        string Line(PackedTlsSession session) => shmac + ":" + Convert.ToBase64String(TlsSessionPacking.Pack(session));
        var good = new PackedTlsSession(TlsSessionCodec.Encode(Session()), 0x0304, Received.ToUnixTimeSeconds() + 100, null, 0, null);
        var cache = new TlsSessionCache(new FixedClock(Received));

        cache.Import(string.Join('\n', Line(good), Line(good with { ProtocolId = 0x0303 })), "f");
        Assert.IsNull(cache.Take(PeerKey), "the TLS 1.2 session replaced the TLS 1.3 one and is not offered");

        cache.Import(string.Join('\n', Line(good with { ProtocolId = 0x0303 }), Line(good), Line(good with { SessionData = [1, 2] })), "f");
        Assert.IsNotNull(cache.Take(PeerKey), "the undecodable newest is dropped, the one before it offered");
    }

    [TestMethod]
    public void Track_KeepsTheNewestTwoUnexpiredSessionsPerPeer()
    {
        var clock = new FixedClock(Received);
        var cache = new TlsSessionCache(clock, () => Salt);
        var sessions = Enumerable.Range(1, 3).Select(value => Session(ticket: (byte)value)).ToArray();
        cache.Track(PeerKey, () => sessions);
        cache.Track("short:443:IMPL-Curl:G", () => [Session(lifetime: 10)]);

        clock.Now = Received.AddSeconds(60);
        var lines = cache.Export().Split('\n', StringSplitOptions.RemoveEmptyEntries).Skip(2).ToArray();

        Assert.HasCount(2, lines);
        Assert.AreEqual(3, cache.Take(PeerKey)!.Ticket[0]);
        Assert.AreEqual(2, cache.Take(PeerKey)!.Ticket[0]);
        Assert.IsNull(cache.Take(PeerKey), "the oldest of three was dropped");
    }

    private static TlsSessionRecord Session(uint maxEarlyData = 0, byte ticket = 7, uint lifetime = 7200) =>
        new(0x0304, 0x1301, new byte[32], new byte[32], [ticket, 1, 2], lifetime, 5, maxEarlyData, Received)
        {
            ServerName = "example.com",
            ApplicationProtocol = "http/1.1",
            Group = 0x001D,
        };

    private sealed class FixedClock(DateTimeOffset now) : TimeProvider
    {
        public DateTimeOffset Now { get; set; } = now;

        public override DateTimeOffset GetUtcNow() => Now;
    }
}
