<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Curl.Protocol.Smb.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Curl.Protocol.Abstractions.UnitLibrary\Curl.Protocol.Abstractions.UnitLibrary.csproj" />
    <ProjectReference Include="..\Curl.Ntlm.UnitLibrary\Curl.Ntlm.UnitLibrary.csproj" />
  </ItemGroup>

</Project>
