using System.Globalization;
using Curl.Core.Fakes;
using Curl.Protocol.Abstractions;

namespace Curl.Core.AltSvc;

/// <summary>
/// Pins <see cref="AltSvcCache" /> against the alt-svc files curl 8.21.0 (mingw, Schannel) wrote on
/// 2026-09-29 UTC with <c>-k --alt-svc cache.txt https://localhost:18443/</c> against
/// <c>Record-CurlExchange.ps1 -Tls</c>, byte for byte; each test's clock is the second curl ran
/// at, read back from the expiries it wrote. The commands and files are in BL-622's notes.
/// </summary>
[TestClass]
public sealed class AltSvcCacheTests
{
    private const string Header =
        "# Your alt-svc cache. https://curl.se/docs/alt-svc.html\r\n"
        + "# This file was generated by libcurl! Edit at your own risk.\r\n";

    private static readonly HashSet<AltSvcAlpn> AnyAlpn = [AltSvcAlpn.H1, AltSvcAlpn.H2, AltSvcAlpn.H3];

    [TestMethod]
    public void FormatFile_AfterTwoAlternatives_WritesCurlsFile()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 5);

        cache.ApplyHeader("h2=\":8443\"; ma=60, h3=\":443\"", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(
            Header
            + "h1 localhost 18443 h2 localhost 8443 \"20260929 05:21:05\" 0 0\r\n"
            + "h1 localhost 18443 h3 localhost 443 \"20260930 05:20:05\" 0 0\r\n",
            cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void FormatFile_WithLineFeed_EndsEveryLineInLineFeed()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 5);

        cache.ApplyHeader("h3=\":443\"", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(
            string.Join('\n', AltSvcCache.FileHeaderLines) + "\nh1 localhost 18443 h3 localhost 443 \"20260930 05:20:05\" 0 0\n",
            cache.FormatFile("\n"));
    }

    [TestMethod]
    public void ApplyHeader_ClearAfterReadingCurlsFile_LeavesOnlyTheComments()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 17);
        cache.ReadFile(
            Header
            + "h1 localhost 18443 h2 localhost 8443 \"20260929 05:21:05\" 0 0\r\n"
            + "h1 localhost 18443 h3 localhost 443 \"20260930 05:20:05\" 0 0\r\n");

        cache.ApplyHeader("clear", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(Header, cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void ApplyHeader_Clear_RemovesOnlyTheOriginsEntries()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 50);
        cache.ReadFile(
            "h1 other.example 443 h2 x.example 443 \"20300101 00:00:00\" 0 0\n"
            + "h2 localhost 18443 h2 x.example 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 localhost 18444 h2 x.example 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 localhost 18443 h2 x.example 443 \"20300101 00:00:00\" 0 0\n");

        cache.ApplyHeader("clear", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(
            Header
            + "h1 other.example 443 h2 x.example 443 \"20300101 00:00:00\" 0 0\r\n"
            + "h2 localhost 18443 h2 x.example 443 \"20300101 00:00:00\" 0 0\r\n"
            + "h1 localhost 18444 h2 x.example 443 \"20300101 00:00:00\" 0 0\r\n",
            cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void ApplyHeader_AfterReadingASeededFile_ReplacesTheOriginAndKeepsTheRest()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 26);
        cache.ReadFile(
            "# comment\n"
            + "h1 other.example 443 h2 x.example 443 \"20200101 00:00:00\" 0 0\n"
            + "h1 keep.example 443 h2 y.example 443 \"20300101 00:00:00\" 1 0\n"
            + "bogus line\n"
            + "h9 a 1 h2 b 2 \"20300101 00:00:00\" 0 0\n"
            + "  h1 LOCALHOST. 18443 h3 z.example 443 \"20300101 00:00:00\" 0 0\n");

        cache.ApplyHeader("h2=\":8443\"; persist=1; ma=10", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(
            Header
            + "h1 keep.example 443 h2 y.example 443 \"20300101 00:00:00\" 1 0\r\n"
            + "h1 localhost 18443 h2 localhost 8443 \"20260929 05:21:36\" 1 0\r\n",
            cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void FormatFile_AfterReadingASeededFile_WritesWhatCurlKept()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 52);
        cache.ReadFile(
            "h1 localhost 18443 h1 localhost 18443 \"20300101 00:00:00\" 0 0\n"
            + "h1 other.example 443 h2 x.example 443 \"20200101 00:00:00\" 0 0\n"
            + "h1 ::1 443 h2 ::1 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 [::2] 443 h2 [::3] 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 a.example 443 h2 b.example 443 \"garbage\" 0 0\n"
            + "h1 a.example 443 h2 b.example 443 \"20300101 00:00:00\" 5 7\n"
            + "h1 c.example 443 h2 b.example 443 \"20300101 00:00:00\" 1 0 extra\n"
            + "h1 d.example 443 h2 b.example 443 20300101 0 0\n"
            + "h1  e.example 443 h2 b.example 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 f.example. 443 h2 b.example. 443 \"20300101 00:00:00\" 0 0\n"
            + "h1 g.example 443 h2 b.example 443 \"20300101 00:00:00\" 0 0");

        Assert.AreEqual(
            Header
            + "h1 localhost 18443 h1 localhost 18443 \"20300101 00:00:00\" 0 0\r\n"
            + "h1 [::1] 443 h2 [::1] 443 \"20300101 00:00:00\" 0 0\r\n"
            + "h1 [::2] 443 h2 [::3] 443 \"20300101 00:00:00\" 0 0\r\n"
            + "h1 f.example 443 h2 b.example. 443 \"20300101 00:00:00\" 0 0\r\n"
            + "h1 g.example 443 h2 b.example 443 \"20300101 00:00:00\" 0 0\r\n",
            cache.FormatFile("\r\n"));
    }

    [TestMethod]
    [DataRow("\n")]
    [DataRow("\r\n")]
    public void ReadFile_LineOfTheLongestLength_ReadsItAndGoesOn(string lineEnding)
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 40, 0);
        string longest = $"h1 {new string('a', 2048)} 1 h2 {new string('b', 2008)} 443 \"20300101 00:00:00\" 0 0";

        cache.ReadFile($"h1 c 1 h2 d 2 \"20300101 00:00:00\" 0 0{lineEnding}{longest}{lineEnding}h1 e 1 h2 d 2 \"20300101 00:00:00\" 0 0{lineEnding}");

        Assert.AreEqual(AltSvcCache.MaxFileLineLength, longest.Length);
        CollectionAssert.AreEqual(new[] { 1, 2048, 1 }, cache.Entries.Select(entry => entry.SourceHost.Length).ToArray());
    }

    [TestMethod]
    [DataRow("h1 {0} 1 h2 {1} 443 \"20300101 00:00:00\" 0 0")]
    [DataRow("# {0}{1}")]
    public void ReadFile_LineLongerThanTheLongest_StopsReadingThere(string format)
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 40, 0);
        string tooLong = string.Format(CultureInfo.InvariantCulture, format, new string('a', 2048), new string('b', 2045));

        cache.ReadFile($"h1 c 1 h2 d 2 \"20300101 00:00:00\" 0 0\n{tooLong}\nh1 e 1 h2 d 2 \"20300101 00:00:00\" 0 0\n");

        Assert.IsTrue(tooLong.Length > AltSvcCache.MaxFileLineLength);
        Assert.AreEqual("c", cache.Entries.Single().SourceHost);
    }

    [TestMethod]
    public void FormatFile_ScopedIpv6Host_WritesItWithoutBrackets()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 40, 0);

        cache.ApplyHeader("h2=\":1\"", AltSvcAlpn.H1, "fe80::1%4", 443);

        StringAssert.EndsWith(cache.FormatFile("\n"), "h1 fe80::1%4 443 h2 fe80::1%4 1 \"20260930 05:40:00\" 0 0\n");
    }

    [TestMethod]
    public void ReadFile_EntryExpiringThisSecond_KeepsIt()
    {
        AltSvcCache cache = CacheAt(2030, 1, 1, 0, 0, 0);

        cache.ReadFile("h1 a 1 h2 b 2 \"20300101 00:00:00\" 0 0\nh1 a 1 h2 b 2 \"20291231 23:59:59\" 0 0\n");

        Assert.AreEqual(1, cache.Entries.Count);
    }

    [TestMethod]
    public void FormatFile_Ipv6Destination_WritesItInBrackets()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 44);

        cache.ApplyHeader("h2=\"[::1]:8443\"", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(Header + "h1 localhost 18443 h2 [::1] 8443 \"20260930 05:21:44\" 0 0\r\n", cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void ApplyHeader_SecondHeader_ReplacesTheFirstHeadersEntries()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 24);

        cache.ApplyHeader("h2=\"[::1]:8443\"; ma=\"30\"", AltSvcAlpn.H1, "localhost", 18443);
        cache.ApplyHeader("h3=\"b.example:1\"", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(Header + "h1 localhost 18443 h3 b.example 1 \"20260930 05:21:24\" 0 0\r\n", cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void ApplyHeader_ZeroAndUnreadableMaxAges_WritesNowAndADayAhead()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);

        cache.ApplyHeader("h2=\":1\";ma=abc, h3=\":2\";ma=0, h2=\":3\"; ma=99999999999999999999", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(
            Header
            + "h1 localhost 18443 h2 localhost 1 \"20260930 05:21:46\" 0 0\r\n"
            + "h1 localhost 18443 h3 localhost 2 \"20260929 05:21:46\" 0 0\r\n"
            + "h1 localhost 18443 h2 localhost 3 \"20260930 05:21:46\" 0 0\r\n",
            cache.FormatFile("\r\n"));
    }

    [TestMethod]
    public void ApplyHeader_MaxAgePastTheLastRepresentableSecond_ExpiresAtIt()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 22, 25);

        cache.ApplyHeader("h2=\":8443\"; ma=999999999999999", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(DateTimeOffset.MaxValue.ToUnixTimeSeconds(), cache.Entries[0].Expires.ToUnixTimeSeconds());
    }

    [TestMethod]
    public void ApplyHeader_NoKnownAlternative_KeepsTheOriginsEntries()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h2=\":1\"", AltSvcAlpn.H1, "localhost", 18443);

        cache.ApplyHeader("foo=\":2\"", AltSvcAlpn.H1, "localhost", 18443);

        Assert.AreEqual(1, cache.Entries.Count);
    }

    [TestMethod]
    public void ApplyHeader_OriginHostThatIsOnlyADot_AddsNothing()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);

        cache.ApplyHeader("h2=\":1\"", AltSvcAlpn.H1, ".", 443);

        Assert.AreEqual(0, cache.Entries.Count);
    }

    [TestMethod]
    public void Find_OriginInAnyCaseWithATrailingDot_GivesTheFirstAllowedEntry()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h3=\":1\", h2=\":2\"", AltSvcAlpn.H1, "Example.com.", 443);
        HashSet<AltSvcAlpn> onlyH2 = [AltSvcAlpn.H2];

        Assert.AreEqual(2, cache.Find(AltSvcAlpn.H1, "EXAMPLE.com", 443, onlyH2)?.DestinationPort);
        Assert.AreEqual(2, cache.Find(AltSvcAlpn.H1, "example.COM.", 443, onlyH2)?.DestinationPort);
    }

    [TestMethod]
    [DataRow(AltSvcAlpn.H2, "example.com", 443)]
    [DataRow(AltSvcAlpn.H1, "example.org", 443)]
    [DataRow(AltSvcAlpn.H1, "example.com", 8443)]
    public void Find_AnotherOrigin_GivesNull(AltSvcAlpn sourceAlpn, string sourceHost, int sourcePort)
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h3=\":1\"", AltSvcAlpn.H1, "example.com", 443);

        Assert.IsNull(cache.Find(sourceAlpn, sourceHost, sourcePort, AnyAlpn));
    }

    [TestMethod]
    public void Find_ExpiredEntries_RemovesThosePassedAndKeepsThoseAfterTheMatch()
    {
        FakeTimeProvider clock = new(new DateTimeOffset(2026, 9, 29, 5, 21, 46, TimeSpan.Zero));
        AltSvcCache cache = new(clock);
        cache.ApplyHeader("h2=\":1\"; ma=10", AltSvcAlpn.H1, "a.example", 443);
        cache.ApplyHeader("h2=\":2\"", AltSvcAlpn.H1, "b.example", 443);
        cache.ApplyHeader("h2=\":3\"; ma=10", AltSvcAlpn.H1, "c.example", 443);
        clock.Advance(TimeSpan.FromSeconds(11));

        AltSvcEntry? entry = cache.Find(AltSvcAlpn.H1, "b.example", 443, AnyAlpn);

        Assert.AreEqual(2, entry?.DestinationPort);
        CollectionAssert.AreEqual(new[] { "b.example", "c.example" }, cache.Entries.Select(held => held.SourceHost).ToArray());
    }

    [TestMethod]
    public void Find_EntryExpiringThisSecond_StillMatches()
    {
        FakeTimeProvider clock = new(new DateTimeOffset(2026, 9, 29, 5, 21, 46, TimeSpan.Zero));
        AltSvcCache cache = new(clock);
        cache.ApplyHeader("h2=\":1\"; ma=10", AltSvcAlpn.H1, "a.example", 443);
        clock.Advance(TimeSpan.FromSeconds(10.9));

        Assert.IsNotNull(cache.Find(AltSvcAlpn.H1, "a.example", 443, AnyAlpn));
    }

    [TestMethod]
    public void FindForOrigin_EntriesUnderTwoVersions_GivesTheFirstVersionsEntry()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h2=\":1\"", AltSvcAlpn.H1, "example.com", 443);
        cache.ApplyHeader("h3=\":2\"", AltSvcAlpn.H2, "example.com", 443);

        AltSvcMatch? match = cache.FindForOrigin([AltSvcAlpn.H3, AltSvcAlpn.H2, AltSvcAlpn.H1], "example.com", 443, AnyAlpn);

        Assert.AreEqual(AltSvcAlpn.H2, match?.SourceAlpn);
        Assert.AreEqual(2, match?.Entry.DestinationPort);
        Assert.IsFalse(match?.IsSameDestination);
    }

    [TestMethod]
    public void FindForOrigin_OnlyADisallowedVersionsEntry_FallsThroughToTheNextVersion()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h3=\":2\"", AltSvcAlpn.H2, "example.com", 443);
        cache.ApplyHeader("h2=\":1\"", AltSvcAlpn.H1, "example.com", 443);

        AltSvcMatch? match = cache.FindForOrigin([AltSvcAlpn.H2, AltSvcAlpn.H1], "example.com", 443, new HashSet<AltSvcAlpn> { AltSvcAlpn.H1, AltSvcAlpn.H2 });

        Assert.AreEqual(new AltSvcMatch(AltSvcAlpn.H1, cache.Entries[1], false), match);
    }

    [TestMethod]
    [DataRow("h3=\":443\"", "Example.COM.", true)]
    [DataRow("h3=\"example.com.:443\"", "example.com", true)]
    [DataRow("h3=\":8443\"", "example.com", false)]
    [DataRow("h3=\"other.example:443\"", "example.com", false)]
    public void FindForOrigin_DestinationTheOrigin_IsTheSameDestination(string header, string origin, bool same)
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader(header, AltSvcAlpn.H1, "example.com", 443);

        Assert.AreEqual(same, cache.FindForOrigin([AltSvcAlpn.H1], origin, 443, AnyAlpn)?.IsSameDestination);
    }

    [TestMethod]
    public void FindForOrigin_NoVersionsOrNoEntry_GivesNull()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);
        cache.ApplyHeader("h3=\":2\"", AltSvcAlpn.H1, "example.com", 443);

        Assert.IsNull(cache.FindForOrigin([], "example.com", 443, AnyAlpn));
        Assert.IsNull(cache.FindForOrigin([AltSvcAlpn.H2], "example.com", 443, AnyAlpn));
    }

    [TestMethod]
    public void Methods_NullArguments_Throw()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 21, 46);

        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ReadFile(null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ApplyHeader("clear", AltSvcAlpn.H1, null!, 443));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.ApplyHeader(null!, AltSvcAlpn.H1, "a", 443));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.Find(AltSvcAlpn.H1, null!, 443, AnyAlpn));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.Find(AltSvcAlpn.H1, "a", 443, null!));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.FindForOrigin(null!, "a", 443, AnyAlpn));
        Assert.ThrowsExactly<ArgumentNullException>(() => cache.FormatFile(null!));
    }

    [TestMethod]
    public void ApplyHeader_GoodAlternativeThenBadPort_ReturnsTheAddedOneThenUnknownPortNumber()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 5);

        IReadOnlyList<AltSvcHeaderOutcome> outcomes = cache.ApplyHeader("h2=\"a.test:443\", h2=\":abc\"", AltSvcAlpn.H1, "localhost", 18443);

        CollectionAssert.AreEqual(
            new[]
            {
                AltSvcHeaderOutcome.Adding(new Curl.Protocol.Abstractions.AltSvcAlternative("h2", "a.test", 443)),
                AltSvcHeaderOutcome.Skipping(AltSvcSkipReason.UnknownPortNumber),
            },
            outcomes.ToArray());
    }

    [TestMethod]
    public void ApplyHeader_ReadableHeaderWithoutAStop_ReturnsOnlyTheAddedAlternatives()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 5);

        IReadOnlyList<AltSvcHeaderOutcome> outcomes = cache.ApplyHeader("h3=\"[::1]:8443\"", AltSvcAlpn.H1, "localhost", 18443);

        CollectionAssert.AreEqual(
            new[] { AltSvcHeaderOutcome.Adding(new Curl.Protocol.Abstractions.AltSvcAlternative("h3", "::1", 8443)) },
            outcomes.ToArray());
    }

    [TestMethod]
    public void ApplyHeader_EmptyOriginHost_AddsNothingAndReturnsNoOutcome()
    {
        AltSvcCache cache = CacheAt(2026, 9, 29, 5, 20, 5);

        IReadOnlyList<AltSvcHeaderOutcome> outcomes = cache.ApplyHeader("h2=\":443\"", AltSvcAlpn.H1, string.Empty, 18443);

        Assert.IsEmpty(outcomes);
        Assert.IsEmpty(cache.Entries);
    }

    private static AltSvcCache CacheAt(int year, int month, int day, int hour, int minute, int second) =>
        new(new FakeTimeProvider(new DateTimeOffset(year, month, day, hour, minute, second, TimeSpan.Zero)));
}
